### ISSUE TITLE
Flexibility in User Aliases API - Associate

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#100]
When thinking of how user aliases should function (for #69) in a general case (not MATHia specific),  we came up with the following example.

1. MATHia user that may or may not be initialized in UpGrade
2. Khan user that may or may not be initialized in UpGrade
3. LTI user that is not yet initialized in Upgrade
4. LTI needs to initialize user and link LTI, Khan, and MATHia users together, but does not know which, if any, are initialized and which is a root ID.

In this case, the LTI will always want to call an explicit init call on the LTI user, it will then attempt to associate aliases (the kahn and mathia userids) with it. Currently this will fail if one of those aliases has been initialized.

Proposing that the API needs to be agnostic of root users and whether any aliases have been initialized. We do not expect the frontend to know such things.

The backend can still designate a user as a root user id, or can treat all ids of alias of an internal id. This requires a few changes in flexibility. This requires the merging by association of two userids that may have already been initialized. We should start by handling the simple case of no-overlap in this issue.

**Comment by amurphy-cl** [comment]
Closing since we decided not to move forward with LTI support. FYI @msandbothe
