### ISSUE TITLE
Unknown condition string allowed in `v1/mark

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1005]
**Version where bug was found:**
5.0.2

** Describe the problem **
The `v1/mark` endpoint allows a random string to be passed into condition, whereas the unversioned, v4, and v5 `/mark` endpoints throw a "condition not found" error.

Is this an issue? What's the correct behavior for an unknown condition string?

(Mathia uses v1 endpoints in Java client currently, and has never had an issue as far as I know, but it's worth noting. This definitely a low priority fix, as we're hoping Mathia will be able to push v4 to production and we can then remove v1 support).

**Comment by ppratikcr7** [comment]
@danoswaltCL Its moved to done, can we close this?
