### ISSUE TITLE
[UI] Show available Stratification factor values on design stepper overview page

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1022]
**Is your feature request related to a problem? Please describe.**
We should show the available stratification factor values on design stepper overview page.

**Describe the solution you'd like**
A list of stratification factor values is visible net to stratification factors dropdown on design stepper overview page.

**Comment by ppratikcr7** [comment]
@amurphy-cl Do we still need this ticket, or we can close this?

**Comment by ppratikcr7** [comment]
> @amurphy-cl Do we still need this ticket, or we can close this?

@amurphy-cl @mswartzCL ?

**Comment by amurphy-cl** [comment]
Yes, we can close.
