### ISSUE TITLE
TS Lib gets 400 when marking a valid factorial experiment assignment

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1026]
**Version where bug was found:**
5

**Describe the bug**
When marking a valid factorial experiment condition, I get a 400 stating that the `assignedFactor` is not a valid `Record` type. The v5 TS Library is sending an array with one AssignedFactor.

When I look into this, I see that even though there's a problem with how TS library is handling this, it shouldn't matter because "assignedFactor" is not used from the request! This is another spot where we're throwing a 400 on assignment object properties that do not need to be sent on the mark request object in the first place. 

**To Reproduce**
1. Create a factorial experiment in staging
2. Set to enrolling for all users
3. Use TS library to init and assign a user
4. Mark the decision point with their valid site + target + condition + status from the assigned factorial experiment.

**Expected behavior**
I'm a little confused a this point, does the client need to send anything about assignedFactor in mark? Is the fix just to make sure the TS library doesn't send anything for "assignedFactor?"

**Comment by danoswaltCL** [comment]
@amurphy-cl i'm not sure where this would get prioritized, this is an issue for v5 TS library regarding marking of factorial experiment assignments.

**Comment by amurphy-cl** [comment]
So not needed for MATHia, right? I guess we could add it to v6, but the solution seems like to not throw that 400 in the first place?

**Comment by danoswaltCL** [comment]
QA: Dan
