### ISSUE TITLE
Show stratification factor usage in the stratification table

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1027]
**Is your feature request related to a problem? Please describe.**
Show if a stratification factor is being actively used in any experiment.

**Describe the solution you'd like**
We should show a usage status 'Used/Unused' for each stratification factor in the stratification table on the stratification tab. We should also show the list of experiments where the stratification factors are being used.

**Comment by ppratikcr7** [comment]
QA: Zack can you please QA this?

**Comment by zackcl** [comment]
The usage status for each stratification factor is applied correctly. However, I've observed that these changes take effect only after clicking the 'Experiments' sidebar button. This means if a user updates an experiment, for instance, by adding a stratification factor, and then immediately clicks the 'Participants' sidebar button to navigate to the Stratifications page, the update isn't reflected until they click on 'Experiments' again. This could be confusing for users and should be addressed.

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/12fa9bc5-4a1e-4134-8742-ae6bb1a2cd86

**Comment by ppratikcr7** [comment]
> The usage status for each stratification factor is applied correctly. However, I've observed that these changes take effect only after clicking the 'Experiments' sidebar button. This means if a user updates an experiment, for instance, by adding a stratification factor, and then immediately clicks the 'Participants' sidebar button to navigate to the Stratifications page, the update isn't reflected until they click on 'Experiments' again. This could be confusing for users and should be addressed.
> 
>  Screen.Recording.2023-12-01.at.8.54.20.AM.mov

Sure, I will look into this.

**Comment by bcb37** [comment]
QA: @bcb37

**Comment by bcb37** [comment]
Looks good to me. QA'ed.
