### ISSUE TITLE
Excluded user errors on assign when user excluded from all experiments in a given context

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1031]
**Is your feature request related to a problem? Please describe.**
Currently UpGrade returns an error for some users [elaborate] in an experiment that has 100% of participants assigned to Condition A and 0% assigned to Condition B. 

**Describe the solution you'd like**
MATHstream is already assigning students this way despite the error, because conditions are still being assigned correctly. However, we want to enable this functionality without the error. It's also a step towards allowing support for feature flagging.

**Comment by danoswaltCL** [comment]
Steps to reproduce:

Create simple experiment with 2 conditions, one with 100% of condition A, one with 0% at condition B.
Include all, exclude one user.

You can also use the [100-0 retest](https://upgrade.qa-cli.net/home/detail/edea4c42-b490-4260-8075-ab3a420b4c3a) experiment in CL dev env (https://upgrade.qa-cli.net/)

Assign call for excluded user breaks like so:

```
{
  "query": "SELECT \"mdp\".\"userId\" as userId, \"mdp\".\"site\" as site, \"mdp\".\"target\" as target, COUNT(*) as count FROM \"monitored_decision_point_log\" \"mdpLog\" LEFT JOIN \"monitored_decision_point\" \"mdp\" ON \"mdp\".\"id\"=\"mdpLog\".\"monitoredDecisionPointId\" WHERE \"mdp\".\"userId\" = $1 AND \"mdp\".\"site\" IN () AND \"mdp\".\"target\" IN () GROUP BY \"mdp\".\"userId\" , \"mdp\".\"site\" , \"mdp\".\"target\", \"mdp\".\"id\"",
  "parameters": {},
  "driverError": {
    "length": 91,
    "name": "error",
    "severity": "ERROR",
    "code": "42601",
    "position": "285",
    "file": "scan.l",
    "line": "1181",
    "routine": "scanner_yyerror"
  },
  "length": 91,
  "severity": "ERROR",
  "code": "42601",
  "position": "285",
  "file": "scan.l",
  "line": "1181",
  "routine": "scanner_yyerror",
  "type": "Error in the assignment algorithm",
  "className": "monitoredDecisionPointLogRepository",
  "functionName": "getAllmonitoredDecisionPointLog",
  "details": "Error in assignment"
}
```

**Comment by danoswaltCL** [comment]
Additional wrinkles, @bcb37 has found that this is not actually related to condition weights at all, it will occur specifically when:

- User is explicitly excluded in participants tab
- There are no other experiments that the user is included in for the given context.

So, if 2 experiments are running for a given context, and the user is excluded from both, they will get the error. If the user is included in one of them, they will NOT get the error.

This is same for `assign` no matter which API version is used.

**Comment by danoswaltCL** [comment]
I can see this in logs when this occurs:

```
QueryFailedError: syntax error at or near ")"
    at QueryFailedError.TypeORMError [as constructor] (/usr/src/app/packages/Upgrade/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/usr/src/app/packages/Upgrade/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/usr/src/app/packages/Upgrade/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:124:57)
    at rejected (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
