### ISSUE TITLE
We are not detecting sub segments if they are being used within the main segment

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1038]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
We are not detecting sub segments if they are being used within the main segment which might be used in an experiment.

**To Reproduce**
1. Create an experiment with include or exclude segment which has a subsegment.
2. Check the segments tab on the left menu and we can see the subsegment with status as `Unused` instead of `Used`. 

**Expected behavior**
Subsegment that belong to an used segment, should also be shown `used` as segment status.

**Screenshots**
`Chicago Public School Dist 299` is used as subsegment inside `Exclude From Research`, but shown as unused as shown below:
<img width="1024" alt="Screenshot 2023-10-09 at 3 28 04 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/dc4df4f2-435e-49c9-bcef-f342cecf2262">

Please find the sample segment and subsegment for recreating the bug.
[segments_prod_CL.zip](https://github.com/CarnegieLearningWeb/UpGrade/files/12844695/segments_prod_CL.zip)

**Comment by danoswaltCL** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
This seems to work only up to 2 levels. If the 'grandparent' segment has a 'parent' segment, which in turn has a 'child' segment, including the 'grandparent' in an experiment doesn't update the 'child' segment's status to 'Used'.

<img width="750" alt="Screenshot 2023-11-14 at 9 27 28 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/7cefe158-74fa-4679-8f3f-88f5b3a8fd93">

**Comment by ppratikcr7** [comment]
> This seems to work only up to 2 levels. If the 'grandparent' segment has a 'parent' segment, which in turn has a 'child' segment, including the 'grandparent' in an experiment doesn't update the 'child' segment's status to 'Used'.
> 
> <img alt="Screenshot 2023-11-14 at 9 27 28 AM" width="750" src="https://user-images.githubusercontent.com/90279765/282807330-7cefe158-74fa-4679-8f3f-88f5b3a8fd93.png">

@Yagnik56 Can you please check this?

**Comment by zackcl** [comment]
@Yagnik56 You don't need to check this. We decided to only support up to 2 levels for now and include this in our documentation.
