### ISSUE TITLE
Disable inserting error logs into database

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1040]
Every error to an endpoint is inserted into DB, so every retried error is also inserted into the database. This table is enormous in the prod database. The purpose of this table is that it can be queried easier than logs and it can be used to show errors to the experiment in the UI, but in practice it is producing a firehose of errors that can barely be queried at all.

This could be temporary or permanent, but will help us avoid eating up DB resources when errors start piling up.

https://carnegielearning.slack.com/archives/C055CGCRP6Z/p1696815544069419?thread_ts=1696815538.859709&cid=C055CGCRP6Z

**Comment by amurphy-cl** [comment]
Let's please not link to private Slack conversations. I've pasted what seems to be the most relevant info below. 

![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/961ba9a0-07c4-42c2-81ec-257caa7947c9)
