### ISSUE TITLE
Create a single page application to demo UpGrade's assignment and metric functions

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#105]
Current version: http://upgrade-client-sdk-frontend.s3-website-us-east-1.amazonaws.com/

Need to make changes to this for the new JS client lib.

**Comment by amurphy-cl** [comment]
Noting that this will be used for XPrize. We need a website that can be used as the experimental application, where we make some selection to run the app, and get a visual representation of condition assignment, etc. Sritter will add more details.

**Comment by nirmalpatel** [comment]
Maybe for the start, we can setup a simple login page and a content page:

![image](https://user-images.githubusercontent.com/830400/127494669-6a0ca0b8-98a9-44e9-811f-29e24c5f6f30.png)

![image](https://user-images.githubusercontent.com/830400/127494883-5c1d2360-93ea-4297-9976-b9892b11ea3e.png)

And we can modify these pages over time...

**Comment by amurphy-cl** [comment]
CL team is working on refining spec for what this demo will do (design and functionality).

**Comment by amurphy-cl** [comment]
@zackcl let's discuss this as a task for you. We may want to close this issue since the demo was created and open a new one with more specifics.

**Comment by amurphy-cl** [comment]
Closing this, replacing additional work in #211
