### ISSUE TITLE
Validation errors for segment, conditionPayload and scheduler

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1054]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
When editing an experiment gives a validation error due to conditionPayload validation. Editing an old experiment import causes segment validation issues as segments were not present during those experiment exports. Changing experiment state to Schedule throws error due to strict validations.

**Comment by danoswaltCL** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
I can confirm that this issue has been resolved.

1. I can edit an experiment without a validation error
2. I can edit an old imported experiment without the segment validation error
3. I can change the experiment state to Schedule without a validation error

> When editing an experiment gives a validation error due to conditionPayload validation. Editing an old experiment import causes segment validation issues as segments were not present during those experiment exports. Changing experiment state to Schedule throws error due to strict validations.
