### ISSUE TITLE
UpGrade documentation

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#106]
Need to create different types of documentation:
- Usage guide (for researchers)
- Hosting guide
- Integration guide
- API docs
- Database schema diagram

**Comment by amurphy-cl** [comment]
Gitbook space created at https://app.gitbook.com/@upgrade-platform/s/upgrade-documentation/ 
We still need to integrate it here in Github.

**Comment by nirmalpatel** [comment]
We can link **docs.upgradeplatform.org** to the GitBook page, and then share the docs link on the Wiki and other READMEs.

This is the workflow for custom domain linking:

![image](https://user-images.githubusercontent.com/830400/128303317-ed11570b-cda1-4ce9-8d5b-b01144b647e9.png)

![image](https://user-images.githubusercontent.com/830400/128303288-8c5229e2-fc78-4532-8506-1d3a8c9b561f.png)
![image](https://user-images.githubusercontent.com/830400/128303330-415826e1-44da-4bbf-bd7f-11b1678b6d5f.png)
