### ISSUE TITLE
No error snackbar for validation errors on editing an experiment

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1060]
**Version where bug was found:**
e.g "5.0.9"

**Describe the bug**
No error snackbar pops up for validation errors on editing an experiment in the QA. Currently, we have pushed a commit to disable the validators. But we need this error snackbar when we again enable the class validators.

**Expected behavior**
We should show an error message in the snackbar with the validation error for users to know.

**Comment by danoswaltCL** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
I'm not sure if we really need to show the error snackbar when editing an experiment. I think the validation errors should show up on the stepper as it is now.

**Comment by zackcl** [comment]
@ppratikcr7 Please share more details on what is fixed and how to QA this issue.

**Comment by ppratikcr7** [comment]
> @ppratikcr7 Please share more details on what is fixed and how to QA this issue.

Earlier when we had multiple instances of snackbars (One for success and one for error). For network call errors we were using `angular2-notifications` and for success we were using `MatSnackBar`. But, now we decided to use only a single package `angular2-notifications` as it provides a nice queue system to stack the errors/success etc toast messages on top of one another to give a better readability.

Initially we saw both the error and success snackbars overlapped due to validation errors. Currently, we wont see that scenario now as the bug is resolved and merged in dev. We might see a similar scenario in future, where this fix would be helpful. You can still observe the queuing of snackbars by just running the frontend without starting the backend and you should see a series of network call errors popping on top of one another.

**Comment by zackcl** [comment]
So, if I can confirm that the multiple snackbars are stacking up (in a queue system) when there are multiple errors or successes, does this mean the issue is resolved and the QA has passed?

**Comment by ppratikcr7** [comment]
@zackcl Yes, this means its passed and resolved.
