### ISSUE TITLE
Simple Categorical Metric query statistics are not visible properly on experiment details page

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1086]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
Simple Categorical Metric query statistics are not visible properly on experiment details page.

**To Reproduce**
1. Create experiment with Simple Categorical Metric query like 'workspaceCompletionStatus'.
2. Check experiment details page and you should see only 1 statistic and compare operation and compare value is missing.

**Expected behavior**
We should see the complete statistic for Simple Categorical Metric query.

**Screenshots**
![image (1)](https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/eee5e595-881b-497e-b519-0735e8b31aad)
![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/4be09c73-6b71-48ae-9861-44d6d95c8568)

**Comment by zackcl** [comment]
I need to QA this

**Comment by zackcl** [comment]
I can confirm that Simple Categorical Metric query statistics are visible properly on experiment details page.

<img width="500" alt="Screenshot 2023-11-16 at 7 58 56 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/b3364d7c-1684-4e6e-aa54-0cee1677fd4c">


<img width="500" alt="Screenshot 2023-11-16 at 7 59 12 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/a2a599e5-ad3a-438b-94af-8d9896c4de70">
