### ISSUE TITLE
General /assign call performance issues in production with many decision points and condition payloads

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1089]
**Version where bug was found:**
5

**Describe the bug**
The assign call is taking more time than we can allow to get under 250ms for the Mathia timeout; this has been a persistent characteristic of the codebase first observed with X-Prize experiments that had multiple decision points and and condition payloads, and most recently has been observed caused issues with the "Omnibus" experiment.

The API seems to be able to handle many experiments with individual decision points, but handling one experiment with many decision points seems to make the response times significantly slower on average, and sometimes, very flare up very high.

This is a hypothesis, the root cause could be other things, but we would like to focus on strategizing ways to improve the query and/or code around the assign call.

**Comment by mswartzCL** [comment]
@danoswaltCL please QA this issue
