### ISSUE TITLE
Support multiple stratification CSV uploads

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1094]
**Is your feature request related to a problem? Please describe.**
Currently, we only support uploading one stratification CSV file at a time, but ideally we want to support uploading multiple CSV files at once for ease of use.

**Describe the solution you'd like**
In the Participants -> Stratifications tab, the user should be able to select and import multiple CSV files at once to the Stratifications table.

**Additional context**
* An example showing how it should work:

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/8ce0933e-c008-4953-8750-ee25b7859f18

* The previous PR (closed due to needing more time to review and test)
https://github.com/CarnegieLearningWeb/UpGrade/pull/1088

* The `multer` library should be removed since the files are not being sent as actual file uploads. Instead, they're sent as plain text within the request body.

**Comment by ppratikcr7** [comment]
@zackcl Do we need this ticket now? Or should we reopen the PR and get multer removed?

**Comment by ppratikcr7** [comment]
QA passed
