### ISSUE TITLE
Code cleanup and optimization for /init api call [Improve Latency]

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1096]
**Version where bug was found:**
e.g "5.0.11"

**Describe the bug**
We observed a few possibilities of optimizations in /init api call. We need to remove extra network calls to reduce latency 

**Expected behavior**
We should see an improvement in the latency.

**Comment by danoswaltCL** [comment]
Code Review: @VivekFitkariwala

**Comment by bcb37** [comment]
QA on this: The response object from the /init call doesn't seem to be what code comments are assuming it is.
`  // if reinit call is made with any of the below fields not included in the call,
    // then we will fetch the stored values of the field and return them in the response
    // for consistent init response with 3 fields ['userId', 'group', 'workingGroup']`

Suggests (to me) that the response object will contain, for instance, the value from the "workingGroup" even when the request object only has "id" and "group". This is not the case. I looks like we're (incorrectly) depending on the `save()` method to return the entire row, [ which it does not](https://github.com/typeorm/typeorm/issues/3490).
