### ISSUE TITLE
Code cleanup and optimization for /mark api call [Improve Latency]

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1097]
Version where bug was found:
e.g "5.0.11"

Describe the bug
We observed a few possibilities of optimizations in /mark api call. We need to remove extra network calls to reduce latency.

Expected behavior
We should see an improvement in the latency.

**Comment by danoswaltCL** [comment]
QA: passed. Ran load tests in dev region, definitely faster after the changes. Ran the tests twice to make sure the results were duplicate-able, got same thing

one commit before bugfix:
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/36b5ac5d-4203-4728-9eba-decb5a549356)

After the fix:
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/e1a1e805-0de6-4f58-ac3d-5c960e14c4fc)
