### ISSUE TITLE
Importing a large number of experiments at once (e.g., 16) causes a freeze

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1101]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
I'm not sure if this is really a bug or just the performance issue, but Importing a large number of experiments at once causes UpGrade to freeze. Once this happens, although no error is shown in the backend Terminal console, any further API requests to the backend do not return a response. I need to restart the backend in order to make UpGrade work again. And even if I restart the backend, the imported experiments don't show up in the UI. This issue was observed when attempting to import 16 experiments at once. Importing 3 experiments at once worked fine.

**To Reproduce**
1. Go to the UpGrade Dev (or Prod) instance page and export all experiments.
2. In the local dev branch, click the "IMPORT EXPERIMENT" button and import all the exported experiments.
3. You will see that nothing happens in the UI and when you refresh the page, you will see the loading spinner constantly spinning.

**Expected behavior**
Importing 16 experiments simultaneously should not be considered an excessive load. The system is expected to handle such a batch efficiently and complete the import process within a few seconds without any freezing or errors.

**Screenshots**

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/5d1c82eb-0cf6-4f40-a668-b7bde6a7abc7

**Additional context**
Here are the 16 exported files: [Experiments.zip](https://github.com/CarnegieLearningWeb/UpGrade/files/13282996/Experiments.zip)

**Acceptance Criteria**
 - Scenario:  When importing multiple experiments
     - Given **16 experiments**, when **importing experiments**, then **the experiments should be imported and appear on the UI within 10 seconds.**

**Comment by zackcl** [comment]
I need to find out exactly what (number of) experiments causes the freeze when importing.

**Comment by zackcl** [comment]
Refinement: Zack

**Comment by zackcl** [comment]
I found out that importing up to 9 files works fine, as I tested. However, importing more than 9 files causes the app to freeze.

**Comment by amurphy-cl** [comment]
Check batching - can you import batches of 9? 

Let's aim to support uploading batches of 100 experiments, assuming little to no significant lag.

**Comment by zackcl** [comment]
@amurphy-cl Yes, importing batches of 9 experiments work fine.

**Comment by danoswaltCL** [comment]
@zackcl review!

**Comment by zackcl** [comment]
QA: Passed
