### ISSUE TITLE
Create env variable to toggle error logs feature in the UI

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1105]
#1080 We disabled error-logging in UI due to it being a huge query to run, too much data in the table.

This was disabled via commenting out but in the future it would be easier to toggle on/off via environment variable.

**Comment by amurphy-cl** [comment]
Need to have a larger discussion on how to make this tab and its messages useful to the front-end user (or whoever might be reading these logs).

**Comment by danoswaltCL** [comment]
https://carnegielearning.slack.com/archives/C055CGCRP6Z/p1712780394950259
