### ISSUE TITLE
Research Redis implementation

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1109]
While testing the in-memory caching it was discovered that this will be insufficient in our AWS Beanstalk deployments because we run multiple servers, so cache invalidation events are not shared between instances. We may need a distributed caching setup via Redis, but there are several ways to approach this and we need some input from SRE / Devops to know what is ideal for our application.

@kcalvo-cli @VivekFitkariwala

**Comment by danoswaltCL** [comment]
We are not planning on using Redis right now, and there's no specific plan for this yet, as it was not necessary to get the "Omnibus" experiment running so it is not urgent, but may still want to do this in future.

@amurphy-cl should we close this issue?

**Comment by amurphy-cl** [comment]
Yes let's close for now, we can create a new issue if the Redis conversation returns in another context.
