### ISSUE TITLE
Load test segments/include and exclude lists with large numbers of individual users

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1112]
There is a possible near-future use case in the CL MARCS study in which experiments are created with segments that contain a large number of individual users (10,000-30,000). To date we've collapsed numbers this large into group information like `schoolId` but I think we haven't tried, for example, importing a json with many thousands of individuals. 

Acceptance criteria: summary of outcomes and recommendation of what might be needed to address risks or problems.

**Comment by bcb37** [comment]
The following are results from load tests performed with exclusions on 
a) a segment with 30,000 users, and
b) a specific group

Tested enrolling 1,000 students at 5 students per second. There doesn't seem to be much difference, except a slightly larger initial increase in response time. Based on this, it doesn't seem likely that using large segments would present much risk.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/3885687/0e83d8ec-1750-4efb-b5ab-88f1fbbfda55)


![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/3885687/950f2084-45d6-4b58-9398-b52da54c0fd3)


![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/3885687/dbfb3a50-2a62-446d-b5a7-fdeb54e85929)
