### ISSUE TITLE
Reselecting experiment files causes "duplicate key" error during import

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1114]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
When importing experiment files, if you reselect files through the "Import Experiment" modal (e.g., first select 3 files, and then select one of the 3 files to import), I get the `driverError: error: duplicate key value violates unique constraint "PK_5bdfd20bb9ace3415008c296fff` error in the backend console.

**To Reproduce**
1. Go to the Experiments list page and click the "Import Experiment" button
2. Click the "Choose Files" button and select 3 experiment files and confirm
3. Click the "Choose Files" button again and select one of the 3 experiment files and confirm
4. Click on the "Import" button on the modal
5. You will see the error message on the Snackbar: `Network call failed. See console for details. http://localhost:3030/api/experiments/import`
6. If you refresh the page, you will see the canceled 3 experiment files are actually imported.

**Expected behavior**
Reselecting experiment files shouldn't cause the error and previously selected files should not be imported.

**Screenshots**

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/017bafa4-3087-499b-82fc-f2ba9e77cbda

**Comment by danoswaltCL** [comment]
QA: Dan

**Comment by danoswaltCL** [comment]
QA: Passed
