### ISSUE TITLE
Sorting experiments by status causes "QueryFailedError"

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1128]
**Version where bug was found:**
5.1.0

**Describe the bug**
Clicking the "Status" column header in the Experiment list page to sort the experiments by status results in a "QueryFailedError: function lower(experiment_state_enum) does not exist" error in the backend.

**To Reproduce**
1. Go to the Experiment list page (need to have at least 2 experiments)
2. Click on the 'Status' column header to sort the experiments
3. See the backend console for the "QueryFailedError" error (Now, you might need to log out and log in again)

**Expected behavior**
Sorting the experiments by status should not cause the error.

**Screenshots**
<img width="750" alt="Screenshot 2023-11-16 at 4 07 03 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/d5d59e94-6893-4f4c-b92c-c835912f7363">

**Comment by ppratikcr7** [comment]
QA: Done. Working as expected.
