### ISSUE TITLE
Selecting the "Archived" status disables the "Save" button for other statuses

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1130]
**Version where bug was found:**
5.1.0

**Describe the bug**
In the "Change Experiment Status" modal, when you select the "Archived" status from the dropdown, and then select other statuses, the "Save" button is disabled.

**To Reproduce**
1. Go to the experiment details page
2. Open the "Change Experiment Status" modal
3. Select "Archived" in the New Status dropdown
4. Select other status in the New Status dropdown
5. You will see the "Save" button is disabled

**Expected behavior**
The "Save" button should not be disabled when other status is selected

**Screen recording**

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/71689369-35c8-485c-b408-4c5b28003846

**Comment by ppratikcr7** [comment]
QA: Done. Working as expected.
