### ISSUE TITLE
Research spike to audit backend dependencies.

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1133]
Audit current dependencies in frontend package.json and see what should be updated to latest versions. Output of spike should be a list of what should be updated and any notes for what may be a breaking change and need some care to update properly.

We should specifically look into TypeORM, TypeScript, and Cache-Manager latest major versions.

**Comment by VivekFitkariwala** [comment]
Do we need to keep this story open?

@bcb37 @danoswaltCL
