### ISSUE TITLE
Cherry-pick Java Lib 3x changes down into 4x, 5x

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1139]
Retries were modified in the latest patch of v3 Java lib. These changes need to be merged down so they are in sync with 4x (`release/v4.1 branch`), 5x (`release/v5.0`).

**Comment by danoswaltCL** [comment]
Version 4: #1058
Version 5: 
Dev:

**Comment by danoswaltCL** [comment]
@bcb37 @jerith666 created this story lest we forget to do this, technically both are cherry-picks of the retries commit. Once these changes are merged in I'll republish the Java artifacts for this updated version in Nexus.

**Comment by danoswaltCL** [comment]
Java lib artifacts updated in Nexus:
4.1.14
5.0.13

**Comment by bcb37** [comment]
Tested v5.0 and v4.1 - retry works as expected for 
200s: no regressions
400s: no retries
500s: one retry
