### ISSUE TITLE
Export include/exclude csv files for segmentation

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1141]
**Is your feature request related to a problem? Please describe.**
Currently the UpGrade UI allows for include/exclude members to be exported on a by-individual basis or as a json file. Since we often have large lists (in csv format) of members that we want to import, we need an export function to more easily export list members in a format that most users will have on-hand. 

**Describe the solution you'd like**
The ability to export a csv file, perhaps with fixed headers, in the Segments tab for either include or exclude lists.

**Comment by bcb37** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
@amurphy-cl @danoswaltCL Currently, the format of the expected CSV file looks like the following:

```
UUID,Type
student1,individual
segment1,segment
school1,schoolId
```

Do you think this format is OK, or would you prefer the two columns to be swapped to match the table in the UI?
<img width="750" alt="Screenshot 2024-01-18 at 8 15 21 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/8f0b712d-de3a-428e-893f-87b5585cec4a">

Currently, the type 'individual' and 'segment' are exported in lowercase, but they appear capitalized in the UI. I believe they should also be capitalized when exported. Additionally, we should check the case sensitivity during import. Let me know your thoughts on this.

**Comment by zackcl** [comment]
Currently, when importing from a CSV, the list is appended to the existing ones. It's also possible to import members that are already present in the table as I tested.
<img width="750" alt="Screenshot 2024-01-18 at 8 29 40 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/5ebb73e1-8123-4adc-86ed-10a97190111c">


@amurphy-cl, do you think appending the list to the existing ones is better than replacing them? I think it might be less confusing to allow CSV imports only when the table is empty. However, there could be use cases for importing/upserting CSVs on top of existing data. Let me know your thoughts on this.

**Comment by zackcl** [comment]
Here is the summary of what we discussed today:

1. The order of the `UUID` and `Type` columns needs to be swapped to match the order shown in the table UI.
2. It's acceptable to have "individual" and "segment" in lowercase when exported, and not to check case sensitivity during import. However, ideally, we would like all these types to be capitalized in UpGrade, which we can discuss later.
3. The "Import CSV" button should only be enabled if the table is empty or contains only blank rows; otherwise, the button should be greyed out using the color `var(--light-blue)`.

Therefore, 1 and 3 should be addressed.

**Comment by zackcl** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
I have QA tested this feature and found out that blank rows are not being removed after a CSV file is imported.
> 4. If any blank rows exist when a CSV file is imported, they need to be removed from the table.

Here's the screen recording showing the issue:

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/1089698e-ede1-4403-978d-d6dbd05a80ea

**Comment by zackcl** [comment]
Here's another minor issue I found: the same CSV file cannot be imported twice in a row. Importing a different file works fine though.

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/aa3419b6-c9ee-426a-904b-42fa49905c17

**Comment by Yagnik56** [comment]
I will look into 1st and 3rd issue, but we should discuss 2nd one. Why should we allow importing members after person added empty rows, this way if someone add 1000 rows we have to check all of them if they are empty or not creating unnecessary load on our front-end and keep in mind that we check for validation on every change in members table.

**Comment by zackcl** [comment]
@Yagnik56 I think it's OK to not fix the 2nd issue. It was just to make the UI work consistently for clearer communication, but I don't think it's that important.
