### ISSUE TITLE
Research spike to check dev effort and advantages of using monorepo libraries

### ISSUE THREAD

**Issue by VivekFitkariwala** [CarnegieLearningWeb/UpGrade#1153]
We need to look for these while researching monorepo libraries

- Single package json for running command in multiple repos.
- We need better management of dependencies across various repos in the project.
- The Boilerplate for the code sharing among the repos should be moved to the monorepo library.
- Some out-of-box advantage of the improvement in the build system (by caching)

Nx is preferable as it is already used in CL.

**Comment by VivekFitkariwala** [comment]
Most of the Nx features are not useful for us as they are used for managing large monorepos which have interdependencies on each other. The only features which will be useful are 
[Caching task result](https://nx.dev/core-features/cache-task-results) 
[Enforcing module boundaries](https://nx.dev/core-features/enforce-module-boundaries)

**Comment by ppratikcr7** [comment]
@VivekFitkariwala Can we close this for now?
