### ISSUE TITLE
Refreshing the Participants page empties the Stratifications table

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1155]
**Version where bug was found:**
5.1.0

**Describe the bug**
When the Participants page is refreshed, the Stratifications table fails to display the defined stratification factors. This issue can be resolved only by clicking the 'Experiments' sidebar button and then navigating back to the Stratifications page.

**To Reproduce**
1. Go to Stratifications page and upload one or more stratification factors
2. Refresh the page
3. You will see that the Stratifications table is empty
4. Click the 'Experiments' sidebar button, and navigate back to the Stratifications page to see the defined factors again

**Expected behavior**
The stratification factors should be properly displayed even when the page is refreshed.

**Screenshots**

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/ae6f08d2-b597-48b3-a4a2-b276f1beb8d8

**Comment by bcb37** [comment]
Looks good. Qa'ed!
