### ISSUE TITLE
Address`AuthorizationRequiredError` from UI

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1158]
This is an error that is related to calls that may be happening when the UI tries a couple of calls before the auth window opens; it doesn't hurt anything but it's a little noisy in the logs and indicates that some useless calls are being generated by the UI that may need to be revised so that they don't fire if the user auth flow will need to be initiated first.

Steps to reproduce:

In an environment where the env var AUTH_CHECK is true (such as current Production env):
1. Login
2. Hit refresh
3. You will be prompted to login again in UI 
4. In logs (or new relic) you will observe a handful of `AuthorizationRequiredError`:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/c1134c6d-ccb9-4534-9a3a-a425b298b8b7)

This is not the the expected behavior. This issue #1136 addressed this and this PR #1145 was merged into `dev` to fix it. The issue was that these calls were being attempted in the UI without a Bearer token attached to the headers yet, which caused the backend to refuse them because "AUTH_CHECK" is true. This in-turn resulted in the UI logging out the user.

The fix in #1145 was to make sure that the calls happen in right sequence, with the bearer token present in headers. To observe that this is fixed, `AUTH_CHECK` has been turned on in the dev environment. Now when visiting UpGrade, if one clicks refresh, one will no be forced to re-login, and as a consequence, this error will not be observed in the logs.

**Comment by danoswaltCL** [comment]
@bcb37 I added some elaboration on this issue so it can be QA'd

**Comment by bcb37** [comment]
This now works as expected. QA'ed!
