### ISSUE TITLE
Prod: Validate Enrollment Complete

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1178]
#909 hotfix for enrollment complete status was tested in staging and then deployed to production, but we haven't had an experiment in `assign-prog` that actually needed `enrollment complete` status, so we technically have not yet validating this hotfix in production yet.

Created this task as a reminder so we can move #909 to done as it is otherwise finished.

@amurphy-cl do we want to test this with an AA experiment or anything?

**Comment by amurphy-cl** [comment]
@danoswaltCL that's a good idea. The existing experiments in CL prod aren't scheduled to be set as complete until Jan 2024.

**Comment by amurphy-cl** [comment]
Plan: April will set up the experiment, start, run, then set to enrollment complete with a post rule. Dan will monitor.
