### ISSUE TITLE
Enrolment counts not reflected after mark call optimization due to null DP stored in individual enrolment table.

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1180]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
After mark call optimization PR, the enrolment counts are not reflected on Data Tab due to null DP stored in individual enrolment table. This also results into storing empty data in experiment CSV export.

**To Reproduce**
1. Mark a user in any experiment. 
2. Click on 'Data' Tab for that experiment
3. You would not see the enrolment counts and bar graph in `By Decision Point` section.
4. You would not see the enrolment counts in `By Condition` section.
5. Log a metric data for the marked user. You can now try to export experiment CSV data and you would get empty rows.

**Expected behavior**
We should store the partitionId in the individual enrolment table and that should resolve all the enrolment count queries. The exported CSV data should have proper data rows.

**Screenshots**
<img width="1275" alt="Screenshot 2023-12-13 at 6 59 30 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/4b2870fb-48e1-4c84-a6d1-5ce810caeb71">

**Comment by bcb37** [comment]
Tested locally - the data shows up again. Pass.
