### ISSUE TITLE
Update export format

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1182]
**Is your feature request related to a problem? Please describe.**
Initially we envisioned offering both "Simple" and "Full" data exports; usage suggests just one export format is necessary. Currently the Simple format fails to capture useful information for experiments with multiple decision points, those that use a within-subjects design, and other useful information for analysis.

**Describe the solution you'd like**
The data export should be updated to reflect the new format here: https://docs.google.com/spreadsheets/d/1qAy7SNklPBWTtJed0Bqc8IppZn5DsQ4nBRsjtP-wtm0/edit#gid=1887655424

**Dependencies**
Before updating the export format, we should make sure that the new format doesn't result in overly-large file sizes when exporting data with hundreds of thousands of records.

**Comment by amurphy-cl** [comment]
First assumption is that the new format should be a reasonable file size and go from there. If it fails, we'll have to rethink the format and what we want from the export.

**Comment by ppratikcr7** [comment]
@amurphy-cl So, should we go ahead and update the format as per the above attached csv format? Later we can check if the file size is good to handle or not?

**Comment by amurphy-cl** [comment]
@ppratikcr7 That sounds good, thanks

**Comment by ppratikcr7** [comment]
@amurphy-cl So, we want to store each mark details for a user for the same decision point of an experiment? 
I tried to check and with the above format we can store around 1 Lakh row data within 40mb file approx.
Do we have a rough idea of what maximum number of mark calls can we have?

**Comment by ppratikcr7** [comment]
> @amurphy-cl So, we want to store each mark details for a user for the same decision point of an experiment? I tried to check and with the above format we can store around 1 Lakh row data within 40mb file approx. Do we have a rough idea of what maximum number of mark calls can we have? Note: In this estimate, I haven't added the `experiment state` sheet. Will we be emailing a xlsx file instead of a csv with the main data sheet and the `experiment state` sheet?

@amurphy-cl ?
