### ISSUE TITLE
Epic: Feature flags

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1185]
Tracking code changes and updates to support feature flags

- #1237 Create figma prototype for feature flags
- #1340 Add app context to feature flag table
- #1341 Java library changes for feature flags
- #1342 Typescript library changes for feature flags
- #1308 Remove old feature flags UI elements
- #1306 Add participants rule table to database

**Comment by danoswaltCL** [comment]
Closing as this is an outdated / incomplete view of the work
