### ISSUE TITLE
Remove Dark mode theming in components

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1189]
If we're officially ending support for dark-mode, we should formally disable dark mode toggle in the UI and remove dark-mode theming from the css and code.

Acceptance criteria: 
1) Dark mode is not accessible from profile in UI
2) Dark mode related code has been verified to have been deleted from the Angular project

**Comment by danoswaltCL** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
QA: Passed
