### ISSUE TITLE
Cache-Manager gives undefined values on ENABLE-CACHING=false

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#1199]
To Reproduce:

- When caching-enabled is false and database is started fresh, we will see `memoryStore is undefined`

**Comment by danoswaltCL** [comment]
QA: @danoswaltCL

**Comment by danoswaltCL** [comment]
I set CACHING ENABLED to false and cleared the db in dev environment. I then rebooted instances. I see no undefined errors or anything like that, so I guess that passes?
