### ISSUE TITLE
Reloading of the experiment detail page does not work

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#120]
Right now, when you reload the experiment detail page, you only get the left menu back but the detail section goes blank. See below:

![image](https://user-images.githubusercontent.com/830400/130051910-8b450fff-d420-4c0d-9e33-5f601af6765f.png)

In the network tab, we see a 404 error that might be related:

![image](https://user-images.githubusercontent.com/830400/130051966-80c421ac-3856-4df1-9f1f-1db0475ced08.png)

Vivek suggested a solution where we create a new route in the backend that is missing.

**Comment by amurphy-cl** [comment]
@ppratikcr7 this bug still exists. Let's prioritize this fix.

**Comment by ppratikcr7** [comment]
@amurphy-cl Yes, I am working on it.
