### ISSUE TITLE
All metric queries should not fail if one of the queries fail

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#121]
Right now, on the experiment detail page, we show the results of all of the metric queries at the bottom. A single query goes to the server trying to get results for all of the 'sub queries'. If one of the 'sub queries' fails, we don't see any result.

This is part 2 of issue #19 where Steve mentioned "Also, in the second screenshot, you can see no data under "average time to complete workspace". I had previously seen data for this metric, so that could also be a timeout issue (note, though, that the server recognizes that there is some data - if there's no data, the metric clearly shows the message "No Data"). So this might be a separate bug."

![image](https://user-images.githubusercontent.com/830400/130052431-f6331d1a-b5c6-4d49-a501-bf7882cc8285.png)

We need to make sure that when one query fails, all queries do not fail.

**We also need to log which query failed.**

**Comment by msandbothe** [comment]
@nirmalpatel Was this what we saw during the Battleship NL 2 hour meeting on Sept 8th?

**Comment by nirmalpatel** [comment]
@msandbothe yeah, we added a faulty query and that crashed all other working queries, but when we removed that faulty query, the working queries started showing up correctly.
