### ISSUE TITLE
Simplify CI/CD process for both frontend and backend

### ISSUE THREAD

**Issue by VivekFitkariwala** [CarnegieLearningWeb/UpGrade#122]
Some of tasks

1. Remove separate environment from terraform and use different tfvars to run different environment
2. Merge frontend code in the backend Upgrade and serve the app via a route
3. Remove Terraform script for frontend

Please add other changes if needed

**Comment by msandbothe** [comment]
Copy/Paste from meeting notes
Currently separate repos for frontend/backend and terraform scripts
    We don’t really need separate hosting or terraform scripts anymore, can simplify CI/CD process by not having separate scripts on a per-environment basis. MF also has perspective on this - secrets variable file that is brought in for the environment, use same main.tf file for each env. Vivek will add this in an issue, will assign to Mike F who will create a branch and work on this.

**Comment by amurphy-cl** [comment]
@mfugate1 Are you working on this?

**Comment by mfugate1** [comment]
No, this will have to wait until next year
