### ISSUE TITLE
Import segments dialogue appears even when experiment import fails

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1235]
**Version where bug was found:**
5.0.13

**Describe the bug**
We have a dialogue that appears when an experiment is imported (see screenshot). I'm not sure we need this dialogue at all, but the bug is that it appears even when the experiment fails to import. 

![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/abd39004-e232-4220-af8f-33612e1e5aae)

**To Reproduce**
1. Attempt to import an experiment that will fail (such as an old json that's incompatible)
2. See dialogue that appears briefly at the bottom of the experiment list

**Expected behavior**
When an experiment fails to import, we shouldn't provide dialogue prompting additional actions. In fact, we should instead provide a dialogue that indicates the failure.

**Comment by Yagnik56** [comment]
Hi @amurphy-cl , I think this issue is resolved with current dev branch you can have a look and let me know if you find any issue there.

**Comment by amurphy-cl** [comment]
Closing - issue resolved in dev branch
