### ISSUE TITLE
Create figma prototype of new design for feature flags

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1237]
Create Figma prototype that includes Feature Flags as a new item in the left-hand menu, that fits in with the larger section-based redesign of the experiments. 

Acceptance will depend on review by team.

**Comment by zackcl** [comment]
Here's the link to the Figma prototype for Feature Flags: https://www.figma.com/file/lwW0jUjVbYxbIvUkUzhDLr/UpGrade-UI-Redesign-10-(Feature-Flag-only)?type=design&node-id=0%3A1&mode=design&t=zHKCwNt2Qeh5mbXL-1

**Comment by ppratikcr7** [comment]
@zackcl Can we close this ticket
