### ISSUE TITLE
🐛 Experiment Pools would be affected for competing experiments that are moved to enrolment complete state and has post experiment rule set to assign with default condition

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1240]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
For getting the valid experiments we filter out enrolment complete experiments that has post experiment set to assign with default condition. We filter out enrolment complete experiments with post experiment rule set to default condition and this affects the Experiment Pool. So, earlier if a user was assigned such an experiment, then later they would get different experiment assignments. This [update](https://github.com/CarnegieLearningWeb/UpGrade/pull/1102) was made to handle the production latency [issues](https://github.com/CarnegieLearningWeb/UpGrade/issues/909) for enrolment complete experiments with default condition. 
Please check the current where clause to filter enrolment complete experiments with post experiment rule set to default:
```
const whereExperimentsClause =
      '(experiment.state = :enrolling OR experiment.state = :enrollmentComplete) AND NOT (experiment.state = :enrollmentComplete AND experiment.postExperimentRule = :assign AND experiment.revertTo IS NULL) AND :context ILIKE ANY (ARRAY[experiment.context])';
    const whereClauseParams = {
      enrolling: 'enrolling',
      enrollmentComplete: 'enrollmentComplete',
      assign: 'assign',
      context,
    };
```

**To Reproduce**
1. Create two competing experiments with post experiment rule set to default condition.
2. Hit assign api call. You should get two experiments in pool of valid experiments.
3. Change one experiment state to enrolment complete.
4. Hit assign api call again. You should get one experiment in pool of valid experiments.

**Expected behavior**
The pool of valid experiments should persist for all kind of experiments.

**Comment by bcb37** [comment]
@bcb37 QA

**Comment by bcb37** [comment]
I don't see what problem this is solving. The experiment that has been put in 'enrollment complete' state with assign->default post rule is indeed now not being filtered out of the pools array, but I can't see what effect that could possibly have on assignment, given that the code [here](https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L1628) assures that the condition will never be assigned from an ENROLLMENT_COMPLETE=>assign=>default experiment.

**Comment by ppratikcr7** [comment]
> I don't see what problem this is solving. The experiment that has been put in 'enrollment complete' state with assign->default post rule is indeed now not being filtered out of the pools array, but I can't see what effect that could possibly have on assignment, given that the code [here](https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L1628) assures that the condition will never be assigned from an ENROLLMENT_COMPLETE=>assign=>default experiment.

This will affect the selection of the experiment from the pool itself. Till the time competing experiments are in Enrollment or Enrollment Complete states, they should be part of the pool that is the assumption unless we decide to not include them in the Pool logic.
Earlier we included all the experiments in the Enrolling and Enrollment Complete state but because of the caching optimisation we removed Enrollment Complete experiments with specific states this changed the behaviour of the pool logic.
Please go through this and let me know if this makes sense.

**Comment by bcb37** [comment]
> > I don't see what problem this is solving. The experiment that has been put in 'enrollment complete' state with assign->default post rule is indeed now not being filtered out of the pools array, but I can't see what effect that could possibly have on assignment, given that the code [here](https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L1628) assures that the condition will never be assigned from an ENROLLMENT_COMPLETE=>assign=>default experiment.
> 
> This will affect the selection of the experiment from the pool itself. Till the time competing experiments are in Enrollment or Enrollment Complete states, they should be part of the pool that is the assumption unless we decide to not include them in the Pool logic. Earlier we included all the experiments in the Enrolling and Enrollment Complete state but because of the caching optimisation we removed Enrollment Complete experiments with specific states this changed the behaviour of the pool logic. Please go through this and let me know if this makes sense.

I'm afraid I'm still confused. I have not been able to get the API to return different responses before and after this change.
I did notice that the pool (when console logged) contains the enrollment complete experiment, but that experiment always gets filtered out by the code I linked to above.

Could you describe steps to reproduce the bug, including any undesired API responses that this fixes? Or is this just an optimization?

**Comment by ppratikcr7** [comment]
@bcb37 So, the issue here is that if the user was assigned Exp1 earlier from 3 experiments (Exp1, Exp2, Exp3) and length of pool was 3 to select the pool from seed-random. Later if Exp3 was made Enrolment Complete with default condition, we would have pool length as 2 based on old code. This might assign Exp2 and user might get different experience, which is not what we want.
<img width="467" alt="Screenshot 2024-01-23 at 2 45 40 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/14ade1f9-9fc3-459b-8f54-6b3f38c8a852">

**Comment by bcb37** [comment]
I could not reproduce this bug with the old code or the new code. Since the new code is simpler, I'm closing this.
