### ISSUE TITLE
Analysis call getting cancelled

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#1242]
**Describe the bug**
Occasionally, when opening the view modal of an experiment or editing and updating the metrics data, multiple analytical calls are triggered. Consequently, this leads to the cancellation of previously initiated calls.

**To Reproduce**
One of the ways to reproduce is:
1. Create an experiment without any metrics data.
2. Navigate to the experiment detail view page.
3. Edit the experiment.
4. After adding some metrics data, save the changes and close the modal.

**Comment by danoswaltCL** [comment]
Code Review: @danoswaltCL

**Comment by danoswaltCL** [comment]
QA: @bcb37
