### ISSUE TITLE
Total Condition Weights Allowable Range Exceeds Expected 100

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1251]
**Version where bug was found:**
5.1.0

**Describe the bug**
You can create an experiment with 3 conditions weighted at 33.3, 33.5, and 33.6, which totals 100.4. You can also create an experiment with 2 conditions weighted at 50 and 50.4 (or 49 and 50.5). I assume this occurs because the system validates whether the rounded sum equals 100. Although this might not matter in most cases, I believe it could confuse some users. I wonder what others think about this.

**To Reproduce**
1. Go to the Design step in the experiment creation process.
2. Create 2 or 3 conditions.
3. Uncheck the "Weight Equally" checkbox.
4. Set the weights so that their sum is between 99.5 and 100.4.
5. Create the experiment.

**Expected behavior**
The sum of the weights should ideally equal 100, or be closer to it (e.g., between 99.9 and 100.1).

**Screenshots**
<img width="750" alt="Screenshot 2024-01-18 at 2 02 09 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/7f61da19-f540-4463-be31-d9c11c670f6b">

**Comment by Yagnik56** [comment]
I think we round it off, and send it to backend so 50.4 will be taken as 50 I think, not 100% sure I will check

**Comment by ppratikcr7** [comment]
> I think we round it off, and send it to backend so 50.4 will be taken as 50 I think, not 100% sure I will check

We take round off with 1 decimal point, and later add all the weights and round it off to verify against 100. So, if we have 50 and 50.4, we round them to 50.0 and 50.4 and add them (50.0 + 50.4 = 100.4). Then rounding 100.4 gives 100. If we have 50 and 50.6, then it would rounded to 101 and not allowed to move forward.

@zackcl Do you want us to show an error if the sum is out of the range of 99.9 and 100.1?

**Comment by amurphy-cl** [comment]
Pratik's solution sounds good.
