### ISSUE TITLE
Docker build failing for Upgrade

### ISSUE THREAD

**Issue by VivekFitkariwala** [CarnegieLearningWeb/UpGrade#1270]
Backend docker build and deployment failing and this is due to a change that went in with  [https://github.com/CarnegieLearningWeb/UpGrade/commit/2bbe4fa59c18d09254827bf162f86b3c236af461#diff-a5f39b824de5101efc8c[…]e322ec058d056d9bd1ef94L13](https://github.com/CarnegieLearningWeb/UpGrade/commit/2bbe4fa59c18d09254827bf162f86b3c236af461#diff-a5f39b824de5101efc8cbc098013bd6692fc22915de322ec058d056d9bd1ef94L13).  This error is found in the logs, and can be duplicated on local by running docker build . from the backend root.

`#9 1.471 > nps build
#9 1.471 
#9 2.518   _           _ _     _ 
#9 2.518  | |__  _   _(_) | __| |
#9 2.518  | '_ \| | | | | |/ _` |
#9 2.518  | |_) | |_| | | | (_| |
#9 2.518  |_.__/ \__,_|_|_|\__,_|
#9 2.518                         
#9 2.519 
#9 10.03 tsconfig.build.json:18:5 - error TS6053: File '/usr/src/types' not found.
#9 10.03 
#9 10.03 18     {
#9 10.03        ~
#9 10.03 19       "path": "../../../types"
#9 10.03    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#9 10.03 20     }
#9 10.03    ~~~~~
#9 10.03 
#9 10.03 
#9 10.03 Found 1 error in tsconfig.build.json:18
#9 10.03 
------
executor failed running [npm run build:upgrade]: exit code: 2`

**Comment by VivekFitkariwala** [comment]
_What does "references" in tsconfig.json do for us?_
[References](https://www.typescriptlang.org/docs/handbook/project-references.html) allow us to have a monorepo structure.

Because in the docker image, we need only the upgrade backend related source code, the types folder reference is not found during the build time. A simple fix will be to remove the reference from `tsconfig.build.json`.

**Comment by VivekFitkariwala** [comment]
@danoswaltCL This error will come if the `types` folder is missing in the `backend/packages/Upgrade` folder. [This](https://github.com/CarnegieLearningWeb/UpGrade/blob/858d11e86d54c8582bd5797a37a9b3c484bdd161/.github/workflows/backend-deploy.yml#L81) line make sure to copy the types folder in the `backend/packages/Upgrade` folder. Are you able to recreate the issue on your local machine?

**Comment by bcb37** [comment]
> @danoswaltCL This error will come if the `types` folder is missing in the `backend/packages/Upgrade` folder. [This](https://github.com/CarnegieLearningWeb/UpGrade/blob/858d11e86d54c8582bd5797a37a9b3c484bdd161/.github/workflows/backend-deploy.yml#L81) line make sure to copy the types folder in the `backend/packages/Upgrade` folder. Are you able to recreate the issue on your local machine?

The types file is copied over. I've replicated this problem locally by running the commands from `backend-deploy.yml` (including copying over the /types directory). When I move the resulting zip file to another directory, unzip it and run `docker build .` it builds fine, but when I run it with `docker run [container-name]` the 'upgrade_types' module is not found, giving the above error that Dan posted.
