### ISSUE TITLE
🐛 Editing the experiment fails with 400 BadRequestError

### ISSUE THREAD

**Issue by Yagnik56** [CarnegieLearningWeb/UpGrade#1273]
Not able update the experiment, getting the below error from validator for the include/exclude participants array being empty: 
![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/50392803/f109dc4c-4e98-46fb-9eaf-27f9d968bc1b)

If I also turn off the validator, it gives the error stating value is undefined.
Here is the experiment I am trying to edit:
[SE.json](https://github.com/CarnegieLearningWeb/UpGrade/files/14085782/SE.json)

**Comment by ppratikcr7** [comment]
@Yagnik56 For me editing the above experiment works fine in the dev branch.

**Comment by Yagnik56** [comment]
Not able to recreate same error in other local dev environments and in my local dev enviroment after deleting that experiment and importing same experiment again so closing this issue.
