### ISSUE TITLE
Conditions table in stepper for factorial experiment isn't showing condition combinations

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1278]
UpGrade Version: v5.0.13

The conditions table should show the condition combinations by weight, e.g. "Question Type: Control, Motivation: Mindset 25%" in the condition weights table. Currently it is blank when creating, although it will update if you edit it in the stepper. 

<img width="983" alt="image" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/a285f5d3-7e09-472b-8f37-bdbd3116a8e1">

**Comment by zackcl** [comment]
It seems to work fine on the dev environment.

<img width="750" alt="Screenshot 2024-01-30 at 3 29 24 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/edcf9796-5e02-4726-8ea5-bef9af949d43">

**Comment by amurphy-cl** [comment]
Closed until able to replicate (original experiment json file lost).
