### ISSUE TITLE
csv export fails for > 64k users

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1286]
Attempting to export an emailed csv of an experiment with > 64k participants results in a postgres error.
We should be able to support experiments with at least that many users.

Dev note: The query that gets log data has a WHERE clause that parameterizes the entire list of users. We may be able to avoid avoid postgres's 64k limit on parameters by using an array.

**Comment by danoswaltCL** [comment]
ah nice find
