### ISSUE TITLE
Updating condition payload to default condition names will not store that in the DB

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1297]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
Updating condition payload will store the new payload name in db, but upon updating it back to the old condition-names, wont update the payload values in the DB. Do we want to update the payload names or delete the rows as we don't store them unless payload values are updated. They are the same as condition names earlier.

**To Reproduce**
1. Create an experiment.
2. Edit the experiment: Change one of the default condition payload to say `p1`. This would now store the updated values in the DB.
3. Again Edit the experiment: Change the condition payload from `p1` to its default condition name say `add-con1`. This would not store the updated values in the DB.

**Expected behavior**
We can either update the DB rows with the default payload names or else delete the data row from DB, as we dont store them initially for default payload values.

**Comment by danoswaltCL** [comment]
QA: Dan
