### ISSUE TITLE
Export button label on Experiments list 

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1303]
**Version where bug was found:**
5.1.0

Text of export button on experiment list page should read "Export All". Instead it looks like this

<img width="1332" alt="image" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/b7e9abdc-5de4-4dcb-aba7-b392a095e2c6">

**Comment by zackcl** [comment]
@amurphy-cl I can't reproduce that. Can you try hard-refreshing the page with Cmd+Shift+R?

**Comment by amurphy-cl** [comment]
Ok, it's gone -- had to clear my cache. Will close.
