### ISSUE TITLE
Bring back the metrics JSON editor to add metrics

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1316]
**Is your feature request related to a problem? Please describe.**
We should have the ability to add metrics from UI using the JSON editor using [jsoneditor](https://www.npmjs.com/package/jsoneditor)

**Describe the solution you'd like**
We already have that built and removed in the [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/510).

**Additional context**
We had an editor for adding metrics but we removed it in [this](https://github.com/CarnegieLearningWeb/UpGrade/commit/8c0097867fe99d592a5d374291b36a4659939f61) commit and the reason was to reduce the build size [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/510). We can revisit this and split the bundle to load it when the user goes to the page where the editor is used.

**Comment by bcb37** [comment]
@danoswaltCL QA

**Comment by danoswaltCL** [comment]
Passes! I was able to add and delete a new metric variable via the UI, no issues.
