### ISSUE TITLE
UpGradeBot v2 Development

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1330]
**User Story**
Last year, I developed UpGradeBot to assist with designing the new Experiments page and modals. It proved useful for brainstorming, suggesting feature names, description labels, and identifying best design practices. It excelled at generating tutorial-like documentation, aiding in design validation. However, development ceased after completing the Experiments page design due to my focus on LiveHint AI.

Now that we've started the implementation of the new Feature Flags design, updating UpGradeBot could provide dedicated code generation support, and offer improvements and best practice suggestions for the Feature Flags implementation.

UpGradeBot v2 will incorporate detailed context about the latest Feature Flags design, including JSON structures and images, alongside code examples from the Angular Material Design Components documentation page. This enhancement is facilitated by the `gpt-4-vision-preview` model, capable of understanding images and supporting extensive text.

When using UpGradeBot, it would be crucial to validate and test its code and suggestions rigorously to prevent errors. Initially, it should aid in code validation and improvement rather than complete code development.

The initial v2 development checklist includes:

 - [x] Completing the JSON structure for each UI component and storing in "context/design."
 - [x] Exporting and storing Figma design images of Feature Flags pages/modals in "context/images."
 - [x] Gathering example code from Angular Material Design documentation for "context/reference/components."
 - [x] Creating a "context" Python dictionary with all file contents.
 - [x] Developing a system prompt for accurate GPT context referencing.
 - [x] Conducting tests to refine the prompt or context for optimal outcomes.
 - [x] Finalizing with a PR, merging to main, and deploying to AWS.

The goal is to finish the initial development and deployment by Tuesday, March 19, 2024.

**Acceptance Criteria**
Scenario: **Implementing the new Feature Flags design**
Given **Any support needs or questions**, when **Asked**, then **receive assistance from UpGradeBot**.

**Comment by danoswaltCL** [comment]
Neat. I'd like to propose also that UpgradeBot be able to perform read-only queries to certain basic-info endpoints on our servers so we can ask for data in slack, that would be great. I briefly tried to get that going, ran into issues with auth but I understand auth a lot better now.

Would we like this capability for UpgradeBot or is that stretching the scope of this too much? Really, it would just need to be able to securely store and access API KEY and SECRET for our envs so that it can do reads, but maybe there are permissions concerns to think about with a slackbot that can access data.

**Comment by zackcl** [comment]
Sure, I like that idea and we can certainly add such features to UpGradeBot after the initial development.
