### ISSUE TITLE
Remove `addMetrics` from client library?

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1332]
**Is your feature request related to a problem? Please describe.**
The `addMetrics` method is a little out of place in the client library, as it is not tied to user actions in the client, and is an administrative task that would normally require a different kind of authorization. This is a little confusing and incomplete anyway, as one cannot do other CRUD operations other than add.

**Describe the solution you'd like**
1) Remove method from libraries.
2) Remove endpoint from experiment client controller
3) Unify the CRUD operations for metrics so they are all grouped under one controller and one swagger section

Alternatively, we could decide that metrics are fine as a client-initiated task, in which case we should give the client libraries full CRUD access instead of just add.

**Comment by amurphy-cl** [comment]
This exists because of a request from @SritterCL, because the MATHia server sends which metrics can be collected, and it's done through the client-side SDK. Aside from this case (implemented but not used), it doesn't need to be in the client SDK.

**Comment by VivekFitkariwala** [comment]
@danoswaltCL @amurphy-cl Should the endpoint be removed from the latest version or all the versions?
cc - @JayMehta11

**Comment by danoswaltCL** [comment]
just v5, we should make a proper deprecation announcement in documentation that 4 and lower are not officially supported. I don't know if we should ever be modifying old controller versions unless there's something majorly wrong, we have retroactively added new features to old versions before but now that everyone at CL is on the latest major version, we can really drop these old controller versions entirely.

**Comment by JayMehta11** [comment]
I have removed the endpoint in v5, and I have added the code back in the older versions as discussed.

**Comment by danoswaltCL** [comment]
QA passed
