### ISSUE TITLE
ConditionPayload JSON object optimization

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#1339]
**Version where bug was found:**
"5.2.0"

**Describe the bug**
The `ConditionPayload` of experiment JSON on export/import contains full-object reference of `Conditions` and `DecisionPoints`. This needs to change to reference ID.

Old ConditionPayload API object return
```
{
      "createdAt": "2024-02-28T16:41:00.181Z",
      "updatedAt": "2024-02-28T16:41:00.181Z",
      "versionNumber": 1,
      "id": "dc72175a-55fb-40e6-98da-73a6de7744b4",
      "parentCondition": {
          "createdAt": "2024-02-28T16:41:00.181Z",
          "updatedAt": "2024-02-28T16:41:00.181Z",
          "versionNumber": 1,
          "id": "dd60067a-5258-4fde-bdd4-15860dbbf379",
          "twoCharacterId": "3U",
          "name": "",
          "description": null,
          "conditionCode": "question-hint-tutorbot",
          "assignmentWeight": 50,
          "order": 2
      },
      "decisionPoint": {
          "createdAt": "2024-02-28T16:41:00.181Z",
          "updatedAt": "2024-02-28T16:41:00.181Z",
          "versionNumber": 1,
          "id": "007ec826-93a2-40f3-822e-4c489c3280a9",
          "twoCharacterId": "V8",
          "site": "lesson-stream",
          "target": "question-hint",
          "description": "",
          "order": 1,
          "excludeIfReached": false
      },
      "payload": {
          "type": "string",
          "value": "custom-payload"
      }
}
```
New structure
```
{
    "createdAt": "2024-02-28T16:41:00.181Z",
    "updatedAt": "2024-02-28T16:41:00.181Z",
    "versionNumber": 1,
    "id": "dc72175a-55fb-40e6-98da-73a6de7744b4",
    "parentCondition": "dd60067a-5258-4fde-bdd4-15860dbbf379",
    "decisionPoint": "007ec826-93a2-40f3-822e-4c489c3280a9",
    "payload": {
        "type": "string",
        "value": "custom-payload"
    }
}
```
**Expected behavior**

On the frontend side, there will no UI change will be seen, this change will affect the store and storing of ConditionPayload of the experiments. 
Now every API call will send the shorter form of ConditionPayload and no repeat structure of Conditions and Partitions in the JSON object

**To Reproduce**
Create some experiments with ConditionPayload data
Hit any experiments-API-calls, the response object will contain the experiment data with ConditionPayload with entire Condition and Partition data repeated (This data is also Conditions and Partitions array)

**Comment by bcb37** [comment]
QA: This PR introduces a bug. 

To replicate:
- create an experiment in the UI
- After it's created, and you're back on the experiment list page, click on the new experiment name to see the details
- The following error is generated: 
`app-error-handler.service.ts:26 ERROR TypeError: Cannot read properties of undefined (reading 'site')
    at experiment-design-stepper.service.ts:325:35`

It seems to be getting the full decision point data structure, rather than the UUID. But just on the first viewing of an experiment.

**Comment by RidhamShah** [comment]
Solved in [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/1379)
