### ISSUE TITLE
Remove type checking in ts-node to improve dev experience

### ISSUE THREAD

**Issue by VivekFitkariwala** [CarnegieLearningWeb/UpGrade#134]
Because type checking is coupled with traspilation it takes more time to start the server and also restart. So decoupling both of them will create better dev experience.
Type checking should be moved as a separate command and it should also be checked before committing the code and in CI/CD flow.

**Comment by jerith666** [comment]
The code will still be type-checked when it's compiled, though, right?  :)

**Comment by VivekFitkariwala** [comment]
@jerith666 Yup it will a separate npm command. I have also added description.
I am planning to use [husky](https://www.npmjs.com/package/husky) as pre git commit hook for type checking and lints.

Also for local development use `SWAGGER_ENABLED=false` (if swagger end point is not needed) as it takes a lot of time.
