### ISSUE TITLE
Java library changes for feature flags

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1341]
Update Java client library's `getAllFeaturedFlags` and `getFeatureFlag` methods to call POST `/featureflags`.

Use the new structure for request / response as defined in #1340

getAllFeatureFlags will internally call `POST /featureflags` with a similar structure as getAllExperimentConditions(), with userId and context, and will store the list of key strings on the client.

`getFeatureFlag` should take a string and return `true` if the flags list contains that flag key, and `false` if it is not found.

**Comment by danoswaltCL** [comment]
This doesn't seem like it was done, reopening

**Comment by amurphy-cl** [comment]
Closing as done.
