### ISSUE TITLE
Typescript library changes for feature flags

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1342]
Update TS client library's `getAllFeaturedFlags` and `getFeatureFlag` methods to call POST `/featureflags`.

Use the new structure for request / response as defined in #1340

getAllFeatureFlags will internally call `POST /featureflags` with a similar structure as getAllExperimentConditions(), with userId and context, and will store the list of key strings on the client.

`getFeatureFlag` should take a string and return `true` if the flags list contains that flag key, and `false` if it is not found.

**Comment by RidhamShah** [comment]
@amurphy-cl for your discription for the client library
`getFeatureFlag` should take a string and return `true` if the flags list contains that flag key, and `false` if it is not found.

this is already a function for clients that return a single `featureFlag` to the user, but we are now replacing it with true/false so do we need it to name getFeatureFlag or rename it to a different name? Eg: checkFeatureFlag, isFeatureFlagKeyPresent etc.
CC @danoswaltCL @bcb37

**Comment by bcb37** [comment]
QA: I verified that `getAllFeatureFlags()` returns the list of appropriate keys, and that `getFeatureFlag(<key>)` returns true when <key> was in the list of returned values after `getAllFeatureFlags()` had been called.
