### ISSUE TITLE
Changes to feature flag admin endpoints

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1345]
The endpoints used to create, view, and edit feature flags need to be updated to reflect the new functionality.

The existing endpoints support CRUD operations (including a POST endpoint to update a flag's 'status').

- The request and response values should be altered to include participant/segment information, and app-context.
- The DB access methods should be changed to store and retrieve this information from the updated db schema.
- Evaluate whether the existing set of endpoints meets the current needs.

**Comment by amurphy-cl** [comment]
Use the read-replica DB for read methods

**Comment by bcb37** [comment]
QA: I did this so someone else should probably QA it

**Comment by VivekFitkariwala** [comment]
The Lists in the feature flag is using the context of the Feature Flag in which they are created. If the Feature Flag is edited and the context is changed the context value of the lists are not updated.
At present the functionality of the feature flags are not getting affected but we are having an inconsistent state in the database.
An easy way to fix this is to not store the context data for the Private segments.

@bcb37 @RidhamShah

**Comment by VivekFitkariwala** [comment]
Segment status is unused even if the segment is used in the Feature Flag list.

**Comment by ppratikcr7** [comment]
This is now covered in 2 separate tickets (#1959 and #1962). We can close this now.
