### ISSUE TITLE
Condition Table should persist old edits

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1352]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
Condition table columns(payload, weights and include) and weights equally checkbox should persist the users' last edits done before any updates are made to the factor table in the stepper.

**To Reproduce**
1. While creating a factorial experiment, try changing the factor table and observe the Condition payload table and weights equally checkbox, they would not persist the old custom data entered by the experimentor.

**Expected behavior**
Condition payload table columns(payload, weights and include) and weights equally checkbox should persist users' last edits

**Comment by danoswaltCL** [comment]
I can try to review today

**Comment by danoswaltCL** [comment]
finally got around to this, sry i forgot about this @Yagnik56 . I saw some funky behavior with weights after editing the factor level, I think the field I edited is keeping the other edits, but the weights that involve the edited level flip to 0 for some reason, see video:

https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/5546267a-eb48-42b2-9b45-c7795578eaaa

**Comment by Yagnik56** [comment]
Hey @danoswaltCL, We actually kept it that way as condition isn't same after we change the level right? unchanged value will persist old change while new get 0 as weight user get assign weight manually or simple click on equal weight if they want.

**Comment by danoswaltCL** [comment]
won't fix, passes!
