### ISSUE TITLE
Component Playground

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1381]
**Is your feature request related to a problem? Please describe.**
Create a "playground" app in the frontend/projects dir that is just a blank angular app that has its tsconfig paths pointed to the upgrade project so that any standalone components one wants to test out in local can be imported and developed in isolation of the main app.

**Comment by ppratikcr7** [comment]
@danoswaltCL Can we close this?

**Comment by VivekFitkariwala** [comment]
We won't do this.
