### ISSUE TITLE
Java client lib v5 expects `experimentType` in assign response, but that doesn't exist.

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1382]
**Version where bug was found:**
5.1

**Describe the bug**
Java Client Library expect `experimentType` in assignment response, but `experimentType` is not a field on the response.

**To Reproduce**
Run Main.java and see `getExperimentType` always return null. Observe that `experimentType` is not a field in the response.

**Fix**
Could update Java lib to figure this out via using the existence of the `assignedFactor` property for now, which is how the TypeScript library does it. A more thorough fix is probably to just send `experimentType` in the assignment response, but that may be a bit more work and potentially an API breaking change.

**Comment by ppratikcr7** [comment]
@danoswaltCL Should we close this, as its moved to Done Column.
