### ISSUE TITLE
Ability to change Ending Criteria when re-enrolling

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#14]
When an experiment reaches Enrollment Complete, and we want to re-start enrollment, we should be able to make some modifications to the ending criteria (say we originally enrolled 500 students, but want to only enroll 200 more for the second enrollment period). Right now we can't make modifications to those criteria.

**Comment by JD2455** [comment]
@amurphy-cl 
I've created a PR #55  to fix the issue.

It will allow to modify enrollment ending criteria even if experiment is in _Enrollment Complete_ state.

**Comment by ppratikcr7** [comment]
@amurphy-cl This is fixed and PR is merged. If verified, can you please close this issue?

**Comment by amurphy-cl** [comment]
We are waiting to fulfill enrollment on at least one experiment in production before verifying
