### ISSUE TITLE
Common Components: Details Page

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1409]
**Description**
Common Details Page Layout

**Links**
[Link to Page in Figma](https://www.figma.com/file/GaKw3nDscTnMEOzIf4CAa7/UpGrade-UI-Latest-14-(Final)?type=design&node-id=16355-11184&mode=design&t=pC7mrBmoUZsvCTYL-0)

**Dependencies**
None

**Dependent Components**
[Feature Flags Details](https://www.figma.com/file/GaKw3nDscTnMEOzIf4CAa7/UpGrade-UI-Latest-14-(Final)?type=design&node-id=20204-15027&mode=design&t=pC7mrBmoUZsvCTYL-0)
[Segments Details](https://www.figma.com/file/GaKw3nDscTnMEOzIf4CAa7/UpGrade-UI-Latest-14-(Final)?type=design&node-id=20204-15102&mode=design&t=pC7mrBmoUZsvCTYL-0)

**Acceptance Criteria**

- Should project a details header container template as the 'header'
- Should project a section card list component as the 'content'

**Comment by amurphy-cl** [comment]
Closing as done.
