### ISSUE TITLE
User names are missing in audit logs

### ISSUE THREAD

**Issue by Yagnik56** [CarnegieLearningWeb/UpGrade#1413]
Name of user in audit log isn't visible.
![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/50392803/bbdf01d7-2f34-402a-a7fa-b080b1a06c57)

**Comment by zackcl** [comment]
The username in Audit Logs could be empty if the logs are generated with API requests (e.g., create/delete experiment). We should probably make those show up as that specific account user in some way (e.g., service account ID). I will create a separate issue for this, and we can say this has passed.

QA: Passed
