### ISSUE TITLE
Import Validation: If import validation fails, the page hangs

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1422]
Found in 5.2

Related to https://github.com/CarnegieLearningWeb/UpGrade/issues/1423

Expected: When uploading a completely wrong `.json` file, I will get a helpful error message in UI.

Actual:

I tried uploading a wrong kind of .json file to try and fail the validation. It allowed me to select this "segments" object .json and on POST to `/validation` it gets a 500 Server Error, which is not handled in the UI, it just hangs there spinning and I can't close the modal.

In 5.1 I found that when I import this file, I get an syntax error, cannot use `forEach` of undefined. Possibly this code was ported to backend and is now failing the same way.

[Exclude from research NEW!.json](https://github.com/CarnegieLearningWeb/UpGrade/files/14890923/Exclude.from.research.NEW.json)

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/dae7f40e-565e-45e7-b4c3-183eea81c2d4)

**Comment by bcb37** [comment]
QA: empty files and files containing only '"' still allow upload and then fail with a generic toast error
