### ISSUE TITLE
Import Validation: Syntax error for non-experiment json

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1423]
Found in 5.1

Related to #1422

When importing a bad json file, the UI hangs on loading and shows a syntax error. We should get an error message that says that it can't recognize this type of file.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/9f9614b3-f313-4db4-b7af-5a8926f829e9)

**Comment by bcb37** [comment]
Still at least two bad json files (empty and containing only "") allow upload and then produce an error.
