### ISSUE TITLE
Release testing: UX for 5.1 

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1424]
Manual testing of UX for most critical cases

* Basic navigation
* Create/edit/delete simple experiment
* Edit decision points
* Edit conditions
* Edit weights
* Edit payloads
* Edit unit of assignment
* Edit group type
* Edit post rule
* Create/edit ending criteria
* Schedule experiment start/end date
* Add/remove participants or segments in experiment when in Enrolling state
* Experiment state changes
* Data export
* Experiment metrics
* Add/edit metrics when experiment is in Enrolling state
* Importing experiment design
* Import segments
* Tags
* Create/edit/delete segments
* Ensure segment Used status is applied when applicable
* Segment member number should match
* Log in/log out of UpGrade
* Refresh pages (ex: experiment detail page, segments pages, experiment list/homepage) from browser (refresh should keep state)
* Navigate to experiment directly from link (should not require login)
* Search functionality and filtering on root page (experiment list page)
* Search functionality and filtering on segments page
* Export segments

Create Zephyr scale tests while using, if possible.

**Comment by amurphy-cl** [comment]
agree, let's not worry about this and hope encounters are minimal

**Comment by zackcl** [comment]
I'm working on creating the critical test cases for Zephyr Scale on Google Docs: https://docs.google.com/document/d/1cxNNXB8Hu5TNvl03Vn4hDBAgDIcbaFfWoPpmTxbz3iE/edit?usp=sharing
