### ISSUE TITLE
Release testing for 5.1: Admin API endpoint testing

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1425]
Exercise admin API endpoint testing outside the UI (e.g. via Postman or some other tool). Do paths work as expected? Are responses as expected?

**Comment by ppratikcr7** [comment]
Missing unit test cases for:
1. Version Controller

**Comment by ppratikcr7** [comment]
Below are the list of error codes missing in unit test cases as per swagger doc: https://docs.google.com/spreadsheets/d/1hER9O-4fqguM_e8Ls7LzHCKevJKbGSM7GfTR0d0EvxI/edit?usp=sharing
