### ISSUE TITLE
Use upgrade_types package locally

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#143]
We need to start importing the `upgrade_types` package locally. To do this, we need to start using npm workspaces in our mono repo.

**Comment by amurphy-cl** [comment]
@VivekFitkariwala can you add a status update?

**Comment by VivekFitkariwala** [comment]
Its work in progress. We have stopped it in between as the priority shifted.

Update to CD pipeline is left in the issue.
