### ISSUE TITLE
Add variable to .env file that allows toggle of experiment type

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1436]
Add variable to .env file that allows us to toggle on/off experiment type. Currently needed for within-subjects experiments

**Comment by danoswaltCL** [comment]
FYI: https://carnegielearning.slack.com/archives/C055CGCRP6Z/p1712780394950259

**Comment by ppratikcr7** [comment]
> FYI: https://carnegielearning.slack.com/archives/C055CGCRP6Z/p1712780394950259

@danoswaltCL We cant see this in our PlaypowerLabs workspace, its CL workspace slack link. If this is something we need to know for resolving this ticket, do let us know the details. Thanks.

**Comment by danoswaltCL** [comment]
QA: Dan, passed
