### ISSUE TITLE
UI changes of metric page

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#1444]
**Is your feature request related to a problem? Please describe.**
After the metrics change from the issue - [1295](https://github.com/CarnegieLearningWeb/UpGrade/issues/1295). We need to update the UI table to show context along with metrics.

A tree structure is created for group metrics, so what should be the new table to show this tree structure and context?
![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/49234788/c4ca9802-2d0c-4f2f-9bea-eabff0326b9e)

**Additional context**
Along with this, we need to add a way to select the contexts (drop-down or multi-input chip) for the JSON-editor.
Color change of the current line
![image](https://github.com/CarnegieLearningWeb/UpGrade/assets/49234788/d6ee7a76-ebce-45b5-b07e-5f2965f97664)

C.C. @zackcl @danoswaltCL

**Comment by danoswaltCL** [comment]
@zackcl hey we may need some quick designs around what this could look like. see #1295 for the new structure of app context

**Comment by zackcl** [comment]
Since it's already in JSON format, can the `context` simply be included in the structure?

**Comment by amurphy-cl** [comment]
Add drop-down menu to select context from list. Add outside the editor so users can view metrics within a single context at a time. 
@zackcl can you suggest how to show the context in the tree structure?

**Comment by zackcl** [comment]
@RidhamShah @amurphy-cl @danoswaltCL Here's my suggested design for the Metrics page: I simply added the `Context` column to the table, but removed the `ID` column, and enabled filtering of the metrics by context. I believe this design is consistent with other pages and requires minimal changes. Let me know what you think.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/40ce4c44-7e6e-42f5-9226-2915b81e57a1)
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/c7041e55-5c30-4108-bea3-1216666f512f)
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/bfb7473d-8db8-426f-b8a3-a93e52379e99)
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/c1b3decf-6791-426d-883e-3f0ad8b1942a)

**Comment by danoswaltCL** [comment]
#1984 Add metrics fails

I'm not sure what exactly the use-case is for Read-mode, maybe it's just to protect deletion, but when it's on the user can still add metrics, which was a little confusing to me.

It's also very unclear what JSON object was actually expected here, even when getting back good 400 Bad Request messages, because the JSON being sent in isn't the full request body. @amurphy-cl @zackcl adding metrics needs some hand holding, some UI hints at least for how to add a metric if sticking with JSON

**Comment by danoswaltCL** [comment]
Also I can add / delete as a user who is not admin ("reader"), that seems like an issue.

**Comment by zackcl** [comment]
For future reference, I can confirm that I don't see the buttons to add or delete a metric as a user with the 'Reader' role in the latest dev branch.

<img width="1000" alt="Screenshot 2024-10-04 at 10 58 58 PM" src="https://github.com/user-attachments/assets/ab0156a4-de1a-4b63-8f27-b30c984a81eb">
