### ISSUE TITLE
"Export" button on the "Export Experiment" modal is not disabled when the "Export Type" drop-down is empty

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1454]
**Version where bug was found:**
5.1.5

**Describe the bug**
The "Export" button at the bottom of the "Export Experiment" modal is not disabled when the "Export Type" drop-down is empty. Also, the "Export Type" drop-down is not focused when the modal is opened.

**To Reproduce**
1. Go to the Experiment details page.
2. Click on the "Export" button.
3. On the "Export Experiment" modal, click the "Export" button when the "Export Type" drop-down is unset.

**Expected behavior**
The "Export" button on the "Export Experiment" modal should be disabled when the "Export Type" drop-down is unset. Also, the "Export Type" drop-down should be focused when the modal is opened.

**Screenshots**
<img width="1000" alt="Screenshot 2024-04-16 at 3 23 33 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/2bb17c24-898f-4710-850e-d0781a3c98c1">

**Comment by bcb37** [comment]
QA: this works as expected
