### ISSUE TITLE
Snackbar doesn't show up when exporting an experiment

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1455]
**Version where bug was found:**
5.1.5

**Describe the bug**
A snackbar doesn't show up when exporting an experiment. The snackbar should appear when the "Export" button on the "Export Experiment" modal is clicked (regardless of the Export Type).

**To Reproduce**
1. Go to the Experiment details page.
2. Click on the "Export" button.
3. Select the "Export Type" (either "Download Experiment Design (JSON)" or "Email Experiment Data (CSV)").
4. Click the "Export" button on the modal.
5. Observe that a snackbar does not show up on export.

**Expected behavior**
A snackbar should show up when an experiment is exported.

**Comment by Yagnik56** [comment]
@zackcl snackbar logic is already there for the export of experiments for both `JSON` and `CSV` methods. I think staging had some issues showing them properly but they are already there. Can you check locally and confirm, so we can close this issue?

**Comment by zackcl** [comment]
The snackbar shows up on the locally running UpGrade, but not on the deployed QA and Staging environments. I'm not sure what is causing this.

**Comment by zackcl** [comment]
@Yagnik56 I think I found out what is causing the issue. Please check out this issue: https://github.com/CarnegieLearningWeb/UpGrade/issues/1497

I think we can close this one once that issue is resolved.

**Comment by ppratikcr7** [comment]
@zackcl We can close this now?
