### ISSUE TITLE
Status changes to "Unused" when the Segment details page is refreshed

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1456]
**Version where bug was found:**
5.1.5

**Describe the bug**
The status changes to "Unused" when the Segment details page is refreshed.

**To Reproduce**
1. Go to the Segment details page of a segment with either "Used" or "Global" status.
2. Refresh the page.
3. Observe that the status has changed to "Unused".

**Expected behavior**
The status should remain unchanged after the page is refreshed.

**Screenshots**
<img width="1000" alt="Screenshot 2024-04-16 at 4 12 37 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/c35e2659-7dad-4801-8d41-0cd05331128a">

**Comment by zackcl** [comment]
@danoswaltCL Should we close this if this works fine in the `dev` branch? I believe you fixed this issue.

**Comment by JayMehta11** [comment]
I have created a PR for it. Please review it - #1586

**Comment by danoswaltCL** [comment]
seems old, but QA'd again and passed
