### ISSUE TITLE
Bug: Segments cache missing prefix, segments cache not retrievable

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1476]
Found in 5.1

In `CacheService.ts` in 5.0 and below, the `wrapFunction` method gets and sets data in cache by "prefix" + "key". When the this was updated for 5.1, the getter did not carry over the "prefix":

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/044c4730-2383-4640-b810-992ba2674c4d)
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/d154c15c-4ad1-4ac9-b91e-ff226aab055d)

`wrapFunction`, despite it's general name, is specifically only used with Segments.

The result is that in 5.1, segments aren't being cached, which is highly likely to be the cause of [slow performance under load](url). This is supported by the fact that segments sql statements show up prominently in the db in 5.1 for high-usage queries but don't even show up on radar for 5.0. That would make perfect sense of segments caches are not reachable due to this key lookup error, as the db would then be getting hit much more often for these frequent calls.

The solution is to add the prefix. PR forthcoming.

**Comment by ppratikcr7** [comment]
@danoswaltCL Should we close this as its in Done?
