### ISSUE TITLE
UpgradeClient's methods not accepting JavaScript object type as arguments

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#148]
I followed the [sample code](https://gist.github.com/JD2455/819b178bd43fc3da376eb2d6ddc55c3b) which I got from @VivekFitkariwala and found out that `UpgradeClient`'s `init()`, `setGroupMembership()`, and `setWorkingGroup()` methods do not accept JavaScript object type as arguments unlike what is written in the [sample code](https://gist.github.com/JD2455/819b178bd43fc3da376eb2d6ddc55c3b#file-upgrade_sample-js-L14-L20).

For example, if I call `setGroupMembership()` by passing an object `{ class: ["class1", "class2"] }` as an argument just like in the [sample code](https://gist.github.com/JD2455/819b178bd43fc3da376eb2d6ddc55c3b#file-upgrade_sample-js-L34), I get the following error message in the browser:
```
Uncaught (in promise) Error: Group type should be Map<string, Array<string>>
    at Object.<anonymous> (bundle.js:16)
    at Generator.next (<anonymous>)
    at bundle.js:16
    at new Promise (<anonymous>)
    at Module.f (bundle.js:16)
    at Object.e.default (bundle.js:16)
    at e.default.<anonymous> (bundle.js:16)
    at Generator.next (<anonymous>)
    at bundle.js:16
    at new Promise (<anonymous>)
```

This is because the `setGroupMembership()` function in the [UpGradeClient.ts](https://github.com/CarnegieLearningWeb/UpGrade/blob/main/clientlibs/js/src/UpgradeClient.ts#L72) file expects the `Map<string, Array<string>>` type and not object type.
```
async setGroupMembership(group: Map<string, Array<string>>): Promise<Interfaces.IUser> {
        this.validateClient();
        let response: Interfaces.IUser = await setGroupMembership(this.api.setGroupMemberShip, this.userId, this.token, group);
        if (response.id) {
            // If it does not throw error from setGroupMembership
            this.group = group;
            response = {
                ...response,
                workingGroup: this.workingGroup
            }
        }
        return response;
    }
```

I can fix the error by passing the correct `Map<string, Array<string>>` type which the function expects:
```
const groupMembership = new Map();
groupMembership.set("class", ["class1", "class2"]);
await upClient.setGroupMembership(groupMembership); 
```

But I personally think passing the argument as an object type is easier and more common for the user to write code. 

Can we fix the 3 methods (`init()`, `setGroupMembership()`, and `setWorkingGroup()`) so they can accept JavaScript object instead of `Map`? (So the current sample code can work)

**Comment by VivekFitkariwala** [comment]
I agree with @zackcl. We can use [Typescript Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype) instead of Map.

**Comment by jerith666** [comment]
A bit of an aside, but is something misconfigured that prevented this error from being caught at compile time?

**Comment by msandbothe** [comment]
As expected, portal create a map in the way that works.
`map(classes => {
                  const memberships = new Map<string, string[]>();
                  memberships.set("schoolId", schools);
                  memberships.set("classId", Array.from(classes.keys()));
                  memberships.set("instructorId", ... )
                  );`

**Comment by VivekFitkariwala** [comment]
@amurphy-cl we have not started on this issue.

**Comment by jreddig** [comment]
Library now uses Record instead of Map. Moving to Done
