### ISSUE TITLE
Calling /api/assign immediately after /api/init results in 500 Server Error

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#15]
See below for curl/response. Subsequent calls to assign succeed.

`curl -X POST "https://upgradeapi.qa-cli.com/api/init" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"id\": \"thisisafakestudent3\",  \"group\": {    \"schoolId\": [\"fake1\", \"fake2\"]   },  \"workingGroup\": {}}"`

Returns 200

`curl -X POST "https://upgradeapi.qa-cli.com/api/assign" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"userId\": \"thisisafakestudent3\",  \"context\": \"assign-prog\"}"`

Returns 500

`{
  "name": "Error",
  "message": "Assignment Error: Error: {\"type\":\"Query Failed\",\"message\":\"{\\n  \\\"Class Name\\\": \\\"GroupAssignmentRepository\\\",\\n  \\\"Function Name\\\": \\\"saveRawJson\\\",\\n  \\\"Parameters\\\": {\\n    \\\"rawData\\\": {\\n      \\\"experiment\\\": {\\n        \\\"createdAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n        \\\"updatedAt\\\": \\\"2021-02-08T14:05:47.674Z\\\",\\n        \\\"versionNumber\\\": 5,\\n        \\\"id\\\": \\\"2c98eb69-ee80-4be8-a74a-51dcb3ec7f75\\\",\\n        \\\"name\\\": \\\"AA2 - Course 3\\\",\\n        \\\"description\\\": \\\"Module: Applying Powers Unit: Properties of Powers with Integer Exponents\\\",\\n        \\\"context\\\": [\\n          \\\"assign-prog\\\"\\n        ],\\n        \\\"state\\\": \\\"enrolling\\\",\\n        \\\"startDate\\\": \\\"2021-02-08T14:05:47.671Z\\\",\\n        \\\"startOn\\\": null,\\n        \\\"endDate\\\": null,\\n        \\\"consistencyRule\\\": \\\"individual\\\",\\n        \\\"assignmentUnit\\\": \\\"group\\\",\\n        \\\"postExperimentRule\\\": \\\"assign\\\",\\n        \\\"enrollmentCompleteCondition\\\": {\\n          \\\"userCount\\\": 20,\\n          \\\"groupCount\\\": 50\\n        },\\n        \\\"endOn\\\": null,\\n        \\\"revertTo\\\": null,\\n        \\\"tags\\\": [\\n          \\\"aa\\\"\\n        ],\\n        \\\"group\\\": \\\"school\\\",\\n        \\\"partitions\\\": [\\n          {\\n            \\\"createdAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n            \\\"updatedAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n            \\\"versionNumber\\\": 1,\\n            \\\"id\\\": \\\"simplify_exponents_2_power_selectSection\\\",\\n            \\\"twoCharacterId\\\": \\\"06\\\",\\n            \\\"expPoint\\\": \\\"selectSection\\\",\\n            \\\"expId\\\": \\\"simplify_exponents_2_power\\\",\\n            \\\"description\\\": \\\"\\\"\\n          }\\n        ],\\n        \\\"conditions\\\": [\\n          {\\n            \\\"createdAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n            \\\"updatedAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n            \\\"versionNumber\\\": 1,\\n            \\\"id\\\": \\\"9df08638-6bfa-432e-ba6b-60f34d6331fa\\\",\\n            \\\"twoCharacterId\\\": \\\"3H\\\",\\n            \\\"name\\\": \\\"\\\",\\n            \\\"description\\\": \\\"First Condition\\\",\\n            \\\"conditionCode\\\": \\\"control\\\",\\n            \\\"assignmentWeight\\\": 50\\n          },\\n          {\\n            \\\"createdAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n            \\\"updatedAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n            \\\"versionNumber\\\": 1,\\n            \\\"id\\\": \\\"4ece12b8-681b-4481-8fed-acad7e672f54\\\",\\n            \\\"twoCharacterId\\\": \\\"O0\\\",\\n            \\\"name\\\": \\\"\\\",\\n            \\\"description\\\": \\\"Second Condition\\\",\\n            \\\"conditionCode\\\": \\\"variant\\\",\\n            \\\"assignmentWeight\\\": 50\\n          }\\n        ],\\n        \\\"queries\\\": [\\n          {\\n            \\\"createdAt\\\": \\\"2021-02-03T16:27:20.166Z\\\",\\n            \\\"updatedAt\\\": \\\"2021-02-03T16:27:20.166Z\\\",\\n            \\\"versionNumber\\\": 1,\\n            \\\"id\\\": \\\"55c63c40-3782-4b89-9692-9c066f460c2f\\\",\\n            \\\"name\\\": \\\"Avg time to complete\\\",\\n            \\\"query\\\": {\\n              \\\"operationType\\\": \\\"avg\\\"\\n            },\\n            \\\"repeatedMeasure\\\": \\\"MOST_RECENT\\\",\\n            \\\"metric\\\": {\\n              \\\"createdAt\\\": \\\"2020-10-26T18:47:56.131Z\\\",\\n              \\\"updatedAt\\\": \\\"2020-10-26T18:47:56.131Z\\\",\\n              \\\"versionNumber\\\": 1,\\n              \\\"key\\\": \\\"masteryWorkspace@__@simplify_exponents_2_power@__@timeSeconds\\\",\\n              \\\"type\\\": \\\"continuous\\\",\\n              \\\"allowedData\\\": null\\n            }\\n          },\\n          {\\n            \\\"createdAt\\\": \\\"2021-02-03T16:27:42.393Z\\\",\\n            \\\"updatedAt\\\": \\\"2021-02-03T16:27:42.393Z\\\",\\n            \\\"versionNumber\\\": 1,\\n            \\\"id\\\": \\\"133334bd-8518-412f-8374-963b4fb18e2e\\\",\\n            \\\"name\\\": \\\"Avg hint count \\\",\\n            \\\"query\\\": {\\n              \\\"operationType\\\": \\\"avg\\\"\\n            },\\n            \\\"repeatedMeasure\\\": \\\"MOST_RECENT\\\",\\n            \\\"metric\\\": {\\n              \\\"createdAt\\\": \\\"2020-10-26T18:47:56.131Z\\\",\\n              \\\"updatedAt\\\": \\\"2020-10-26T18:47:56.131Z\\\",\\n              \\\"versionNumber\\\": 1,\\n              \\\"key\\\": \\\"masteryWorkspace@__@simplify_exponents_2_power@__@hintCount\\\",\\n              \\\"type\\\": \\\"continuous\\\",\\n              \\\"allowedData\\\": null\\n            }\\n          },\\n          {\\n            \\\"createdAt\\\": \\\"2021-02-03T16:28:10.820Z\\\",\\n            \\\"updatedAt\\\": \\\"2021-02-03T16:28:10.820Z\\\",\\n            \\\"versionNumber\\\": 1,\\n            \\\"id\\\": \\\"73de6b74-7ba8-4bfa-972d-bab7b9486231\\\",\\n            \\\"name\\\": \\\"Median probs completed\\\",\\n            \\\"query\\\": {\\n              \\\"operationType\\\": \\\"median\\\"\\n            },\\n            \\\"repeatedMeasure\\\": \\\"MOST_RECENT\\\",\\n            \\\"metric\\\": {\\n              \\\"createdAt\\\": \\\"2020-10-26T18:47:56.131Z\\\",\\n              \\\"updatedAt\\\": \\\"2020-10-26T18:47:56.131Z\\\",\\n              \\\"versionNumber\\\": 1,\\n              \\\"key\\\": \\\"masteryWorkspace@__@simplify_exponents_2_power@__@problemsCompleted\\\",\\n              \\\"type\\\": \\\"continuous\\\",\\n              \\\"allowedData\\\": null\\n            }\\n          }\\n        ]\\n      },\\n      \\\"condition\\\": {\\n        \\\"createdAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n        \\\"updatedAt\\\": \\\"2021-02-03T15:04:30.702Z\\\",\\n        \\\"versionNumber\\\": 1,\\n        \\\"id\\\": \\\"4ece12b8-681b-4481-8fed-acad7e672f54\\\",\\n        \\\"twoCharacterId\\\": \\\"O0\\\",\\n        \\\"name\\\": \\\"\\\",\\n        \\\"description\\\": \\\"Second Condition\\\",\\n        \\\"conditionCode\\\": \\\"variant\\\",\\n        \\\"assignmentWeight\\\": 50\\n      }\\n    }\\n  },\\n  \\\"Error\\\": {\\n    \\\"message\\\": \\\"null value in column \\\\\\\"groupId\\\\\\\" violates not-null constraint\\\",\\n    \\\"name\\\": \\\"QueryFailedError\\\",\\n    \\\"length\\\": 370,\\n    \\\"severity\\\": \\\"ERROR\\\",\\n    \\\"code\\\": \\\"23502\\\",\\n    \\\"detail\\\": \\\"Failing row contains (2021-03-10 19:49:27.891524, 2021-03-10 19:49:27.891524, 1, 2c98eb69-ee80-4be8-a74a-51dcb3ec7f75_undefined, null, 2c98eb69-ee80-4be8-a74a-51dcb3ec7f75, 4ece12b8-681b-4481-8fed-acad7e672f54).\\\",\\n    \\\"schema\\\": \\\"public\\\",\\n    \\\"table\\\": \\\"group_assignment\\\",\\n    \\\"column\\\": \\\"groupId\\\",\\n    \\\"file\\\": \\\"execMain.c\\\",\\n    \\\"line\\\": \\\"2035\\\",\\n    \\\"routine\\\": \\\"ExecConstraints\\\",\\n    \\\"query\\\": \\\"INSERT INTO \\\\\\\"group_assignment\\\\\\\"(\\\\\\\"createdAt\\\\\\\", \\\\\\\"updatedAt\\\\\\\", \\\\\\\"versionNumber\\\\\\\", \\\\\\\"id\\\\\\\", \\\\\\\"groupId\\\\\\\", \\\\\\\"experimentId\\\\\\\", \\\\\\\"conditionId\\\\\\\") VALUES (DEFAULT, DEFAULT, 1, $1, DEFAULT, $2, $3) RETURNING *\\\",\\n    \\\"parameters\\\": [\\n      \\\"2c98eb69-ee80-4be8-a74a-51dcb3ec7f75_undefined\\\",\\n      \\\"2c98eb69-ee80-4be8-a74a-51dcb3ec7f75\\\",\\n      \\\"4ece12b8-681b-4481-8fed-acad7e672f54\\\"\\n    ]\\n  }\\n}\"}",
  "endPoint": "/api/assign",
  "errorCode": null,
  "type": "Error in the assignment algorithm",
  "createdAt": "2021-03-10T19:49:27.902Z",
  "updatedAt": "2021-03-10T19:49:27.902Z",
  "versionNumber": 1,
  "id": 31223
}`

**Comment by amurphy-cl** [comment]
@msandbothe will test this after making changes to Locust script

**Comment by msandbothe** [comment]
Testing revealed another 500 error, but relating to /mark. See #52 

No 500 errors from /assign. Closing.
