### ISSUE TITLE
Importing the UpGrade client library (JS) without Webpack

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#150]
As discussed in the meeting, I was able to import the UpGrade client library with the following steps:

1. Run `npm install upgrade_client_lib`.
2. Make the library file accessible from the client by adding `app.use(express.static(path.join(__dirname, "node_modules/upgrade_client_lib/dist")));` in the node express server.
3. Import the bundle.js file by adding `import "/bundle.js";` in the client JavaScript module.
4. Access the UpgradeClient class with `const UpgradeClient = window["upgrade-client-lib"].UpgradeClient;` in JavaScript.

And after learning that the library exists in [JSDelivr](https://www.jsdelivr.com/package/npm/upgrade_client_lib), I could use the library without having to npm install the upgrade_client_lib package, which is like the following:

1. Add `<script src="https://cdn.jsdelivr.net/npm/upgrade_client_lib@1.1.7/dist/bundle.min.js"></script>` into the HTML `<head>` tag.
2. Access the UpgradeClient class with `const UpgradeClient = window["upgrade-client-lib"].UpgradeClient;` in JavaScript.

While this works, accessing the UpgradeClient with `window["upgrade-client-lib"].UpgradeClient;` is not a clean way to write code.

So I think we should produce a separate JS file with Webpack that would allow users to directly access the `UpgradeClient` class by simply adding a script tag to HTML. I think the ideal process would be like the following:

1. Add `<script src="https://cdn.jsdelivr.net/npm/upgrade_client_lib@1.1.7/dist/upgrade_client_lib.min.js"></script>` into the HTML `<head>` tag.
2. In JavaScript, the user can directly construct the `UpgradeClient` class with `const upClient = new UpgradeClient(userId, hostUrl);`

I'm not familiar with producing a JS file with Webpack, so I would like to ask if what I described above is possible and if this makes sense. Let me know if anyone has any concerns or suggestions regarding this issue.

**Comment by amurphy-cl** [comment]
@nirmalpatel Can you review Zack's suggestion here and share thoughts?

**Comment by mswartzCL** [comment]
@zackcl Do you think this is something that we still need to do or shall we close it?

**Comment by zackcl** [comment]
I think this should remain open, we would need to discuss this.
