### ISSUE TITLE
Disable suggested password popup for the Experiment point input in Chrome

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#151]
When I add a new experiment and click on the Experiment point text input, Chrome shows a suggested password popup that blocks the autocompleted list, and also it doesn't make sense because the Experiment point is not a password.

<img width="1648" alt="Screen Shot 2021-09-23 at 6 14 01 PM" src="https://user-images.githubusercontent.com/90279765/134598819-d3b43577-6d3f-45ae-b5a3-da02e32e425d.png">

I'm pretty sure there's a way to disable this in the Chrome settings but I think it would be annoying for users who have this feature enabled in Chrome which I think is the default setting. 

I tried to fix this through the inspector but I wasn't able to find a solution. It would be nice to disable the password suggestion if anyone knows an easy way to do this. 

(Sometimes the password suggestion popup doesn't show up, but it seems to always show up right after refreshing the page.)

**Comment by amurphy-cl** [comment]
@nirmalpatel Status update?

**Comment by zackcl** [comment]
@amurphy-cl Sure, I will try to fix this.

**Comment by zackcl** [comment]
I'm able to confirm that this issue has been resolved with https://github.com/CarnegieLearningWeb/UpGrade/commit/9f4778ddc249845a914917e51556762945d918c7
