### ISSUE TITLE
Feature Flag Root Section Card

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1529]
https://www.figma.com/design/GaKw3nDscTnMEOzIf4CAa7/UpGrade-UI-Latest-14-(Final)?node-id=20204-15006

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/1bea99af-89d9-479c-8b3b-f9460884a3c1)

Dependent on some common child view-components yet to be developed

Layout:

1) should implement `header` with a Section Card Table Search Widget on left side and Section Card Action Buttons on the right side.

2) should implement `content` with a Section Card Table (TBD if this is a Common component)

Data:

This is a stateful component that should act as a controller for its child view elements

3) should dispatch the `api/flags/paginated` data fetch action on load

4) should show a load-spinner over the entire section-card while table data is pending (TBD, should discuss)

**Comment by ppratikcr7** [comment]
All looks fine except the spinner loader coming on the left section instead of center and also the size seems to be bigger than what we have in experiments table.

![Image](https://github.com/user-attachments/assets/9616b05d-82ea-4eed-ba7a-d3b1931fc046)
