### ISSUE TITLE
Assignment Weights can't be negative and Home Page experiment detail time trims a '0' in minutes and hours

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#155]
Currently the condition assignment weights allow negative values, which should not be the case. 
Also, the home page experiment detail time trims a '0' for minute and hours.
<img width="932" alt="Screenshot 2021-09-28 at 1 08 36 PM" src="https://user-images.githubusercontent.com/33730817/135044140-15974433-49aa-4305-aea4-0ed8714c59f6.png">

**Comment by amurphy-cl** [comment]
@ppratikcr7 If this is fixed, can we close this issue?

**Comment by ppratikcr7** [comment]
@amurphy-cl Yes, it is fixed. You can merge the [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/157) and close the issue.
