### ISSUE TITLE
Feature-flag root section card table

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1555]
Implement the _basic_ root section card table, which should use mat-table to show paginated-flag details data.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/111d7bf2-92b6-4b58-b1c8-b29665b7ffc0)

- For this story, the concentration should be getting the basic layout and component wiring right and not worry about behavior yet like sort / filter / contex-chip / navigation / to next task so it's simple to review.

- Should also handle the "empty" case also though (when no data is loaded):

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/a95e3635-1caf-4185-be56-dd760c5c52d5)

- Otherwise, will need a load-spinner when data is pending.

**Comment by VivekFitkariwala** [comment]
The loader appears in the top left.

![Image](https://github.com/user-attachments/assets/ebe216eb-4fd5-447b-b6dc-d2112aba4e67)

**Comment by Yagnik56** [comment]
@VivekFitkariwala I created PR for it [here](https://github.com/CarnegieLearningWeb/UpGrade/pull/1908).

**Comment by ppratikcr7** [comment]
QA Done: Working as expected.

**Comment by ppratikcr7** [comment]
QA: @Yagnik56 I observed the same spinner top left issue in feature flag details page. Can you please resolve this as well?
<img width="945" alt="Screenshot 2024-10-03 at 2 17 14 PM" src="https://github.com/user-attachments/assets/9b85124f-f5aa-4807-9848-efd38403ef8e">
