### ISSUE TITLE
FF Root Table filtering with the search widget

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1575]
Add filtering functionality to the root table.

- The search widget should affect filtering in the table as you type
- Clicking a tag chip should also affect filtering in the table

Bonus points if we can make this filtering functionality part of a general shared "table utility" service. We'll need this behavior for any table, and as you can see in the existing code in the experiments and segments for example, filtering and sorting code is heavily duplicated and very confusing to figure out, so let's keep it clean and not repeat that!

**Comment by zackcl** [comment]
@Yagnik56 Is this Done? I think we should allow searching by "Tag", and also allow searching by "Tag" by clicking on a tag chip on the table (see my last comment).

**Comment by zackcl** [comment]
@Yagnik56 For your information, since now we support capital letters for user-entered values/tags (#1927), the tags shouldn’t be case-sensitive in matching. If it’s “mathia” in one feature flag but “MATHia” in another, we should be able to click (or search) one and see both.
