### ISSUE TITLE
FF Root page table: Pagination on scroll

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1576]
Additional calls to fetch the next 'page' of paginated results should happen 'on scroll', per the existing behavior in other table.

While new data is pending, the "progress-indicator" banner at the very top of the table should "spin" like it does for experiments (aka, don't hide the table with the spinner used for loading initial data).

**Comment by ppratikcr7** [comment]
@danoswaltCL I dont see paginated scroll happening for feature flags page as we have in experiments. All flags are shown on the page at once and a side scroll will scroll through the entire page.

**Comment by ppratikcr7** [comment]
> [@danoswaltCL](https://github.com/danoswaltCL) I dont see paginated scroll happening for feature flags page as we have in experiments. All flags are shown on the page at once and a side scroll will scroll through the entire page.
> 
>  Screen.Recording.2024-09-12.at.2.05.33.PM.mov

@danoswaltCL Any views on this?

**Comment by ppratikcr7** [comment]
> > [@danoswaltCL](https://github.com/danoswaltCL) I dont see paginated scroll happening for feature flags page as we have in experiments. All flags are shown on the page at once and a side scroll will scroll through the entire page.
> > Screen.Recording.2024-09-12.at.2.05.33.PM.mov
> 
> [@danoswaltCL](https://github.com/danoswaltCL) Any views on this?

@danoswaltCL ?

**Comment by ppratikcr7** [comment]
@zackcl So I confirmed, its still a bug, paginated nodes in 1st load itself is total Feature Flags: 22
It should be 20 as per skip/take.
![Image](https://github.com/user-attachments/assets/d76f94e0-df61-4f71-af11-c714eef042e0)

**Comment by ppratikcr7** [comment]
I will QA this.

**Comment by ppratikcr7** [comment]
QA passed
