### ISSUE TITLE
FF Root table: Empty state:

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1577]
After inititial data has been successfully fetched for feature flags, if there are no flags, show the "empty" table view:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/c37bae93-f8c1-45c7-8f46-f2c47f898489)

**Comment by ppratikcr7** [comment]
@danoswaltCL @Yagnik56 Do we want the table column headers to be CAPS, as we have in other pages like experiments, segments etc.
Seems odd for feature flags page.

Refer this:
![Image](https://github.com/user-attachments/assets/54f4694d-163c-430a-bd68-ea44d2c932ca)
![Image](https://github.com/user-attachments/assets/940b528e-138f-4b77-8dc3-cb5c7e52506c)

**Comment by ppratikcr7** [comment]
@zackcl What do you think?

**Comment by ppratikcr7** [comment]
> [@ppratikcr7](https://github.com/ppratikcr7) I think title case is more common and readable for table headers than all caps. I know it's not consistent with other pages currently, but I think we'll also update those page designs in the near future.
> 
> References:
> 
> * https://ux.stackexchange.com/questions/110135/table-headers-uppercase-or-lowercase-left-or-center-aligned-top-or-bottom
> * https://ux.stackexchange.com/questions/97051/does-uppercase-all-caps-text-in-headings-and-navigation-reduce-the-overall-use
> * https://carbondesignsystem.com/components/data-table/usage/

Okay, got it. Thanks for those references.
