### ISSUE TITLE
Common Section Card: Expand/Collapse Functionality

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1580]
A Common Section Card should include an Input boolean for state of expanded or collapsed content section. The result will be a that only the header is shown when collapsed.

Implement the content hiding / showing behavior. I'm not sure if we care if this is animated or not?

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/361b39b9-9100-4c98-894f-eb4e65fca328)

**Comment by zackcl** [comment]
QA Passed. 

The Expand/Collapse works as expected for all section card. I think we can consider applying animation later.
