### ISSUE TITLE
Integrate get flag details by id on nav to details page

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1590]
On nav / load of the feature flags details page, we should us the id from the url routerparams to fetch feature flag details by id on the page load, either from data store, or if not exist, from db.

Note: I *think* that we shouldn't need to fetch additional data if we already have private segment data and all that in the data store, but should discuss...

GET /flags/{id}:

This should also load accurately when the page is reloaded or opened directly!

Other elements on the page will need to some loadspinner indicators, so the action to dispatch this change should do the "isLoadingSelectedFeatureFlags" thing

**Comment by zackcl** [comment]
I can confirm that it makes the `GET /flags/{id}` request when navigating to the details page. However, directly opening a details page with a URL (`featureflags/detail/{id}`) redirects the page to the Experiments root page.

I think we can consider this as "QA passed" and move the status to Done, as we have a separate ticket for this issue: #1904.
