### ISSUE TITLE
FF Details Overview Section Card content

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1593]
Implement the details overview section card content.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/d0ae7390-300a-4cee-83fc-96289991cea3)

This will require feature flag data inputs from the section card parent.

**Comment by zackcl** [comment]
QA: Passed

```
<app-feature-flag-overview-details-section-card
  [data]="featureFlag"
  [isSectionCardExpanded]="isSectionCardExpanded"
  (sectionCardExpandChange)="onSectionCardExpandChange($event)"
  section-card
></app-feature-flag-overview-details-section-card>
```
