### ISSUE TITLE
Add support for using mysql database

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#16]
Let's start by getting an idea of the level of effort it will take to switch from postgres to mysql.

The goal is to be able to use an aurora mysql database in the CL UpGrade environments

Related issue: https://github.com/CarnegieLearningWeb/UpGrade/issues/1160

**Comment by amurphy-cl** [comment]
Closing as will-not-do, if we change course on this, we'll create an updated issue.
