### ISSUE TITLE
Exports: optimizations based on CLAC recommendations

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1603]
Some recommendations were made by the architecture council for handling the export/read replica issue.

We should:
1. Find optimizations based on the query plan (possibly using the postgres 'explain' command
2. If we can implement optimizations allow us to use large, unpaginated queries in a reasonable time, we should implement those.
3. If not, we can try using 'materialized view'

NOTE: Pagination might actually be the main reason the read replica isn't working. But, based on the conversation with CLAC, we shouldn't need pagination.

**Comment by ppratikcr7** [comment]
@bcb37 Its in Done column, can we close this?
