### ISSUE TITLE
Error interceptor swallows error propagation

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1604]
**Version where bug was found:**
all

**Describe the bug**
`catchError` code used in most http effects is rendered unreachable by http-interceptor that swallows the error.

**Expected behavior**
It should be allowed to let the error keep propagating so that we can pass control back to the component to do its own error-handling.

**Comment by ppratikcr7** [comment]
@danoswaltCL Should we close this?

**Comment by ppratikcr7** [comment]
@danoswaltCL Should we close this?
