### ISSUE TITLE
FF Add Feature Flag Tag Input

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1609]
Dependent on #1607, replace the current placeholder tag input field in add-feature-flag modal with the "real" tag input component.

Note, this does not need an 'import/export' button on the right hand side.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/f500056c-e9d6-4bf8-8b38-e9dc0a1a9df2)

**Comment by bcb37** [comment]
QA: looks good.
