### ISSUE TITLE
FF Delete Feature Flag Modal + Functionality

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1610]
Implement the delete feature flag modal, which is launched from the details page overview section card menu.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/3150fec5-6b06-4db1-8f44-c3fe4498a4b5)

- When user types 'delete' exactly into the form, the button should become enabled.
- On click, the button should be disabled and the user should remain on the modal until the call has completed
- On success, the deleted item should be removed from the flags entity list in the data store and the modal should close and navigate back to root.
- On fail, the form should be reenabled and the snackbar will show failure. the user should be able to try again or exit the modal to close.

**Comment by Yagnik56** [comment]
@danoswaltCL will it use common modal or it will independent component only

**Comment by danoswaltCL** [comment]
yeah every modal in zack's designs will want to use common-modal.

**Comment by zackcl** [comment]
QA: Passed
