### ISSUE TITLE
FF Import Modal (large import button layout)

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1611]
The import modal has a lot going on, so this one should be broken into bits.

We should start it with creating the modal layout without functionality bound to the button or forms yet. The content area will first show a large input area that is drag-and-drop capable.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/47950a69-aabe-4dff-911d-987e9b39b571)

**Comment by bcb37** [comment]
QA: Import modal looks good.
