### ISSUE TITLE
FF Implement Edit Feature Flag Modal

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1612]
This is visually the same as the Add Feature Flag modal (as well as the Duplicate Flag modal), but it probably is wise to keep 'em separated so we're not stumbling over which "mode" we are in in the code. This is one place where I think code duplication is better than trying to be too clever with DRY.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/e9c2188e-b425-4482-b2ec-355a72f2d6cb)

**Comment by ppratikcr7** [comment]
QA passed
