### ISSUE TITLE
FF Inclusions Section Card Table Content

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1619]
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/13fa6338-01c9-4720-8d8e-18d6ffdaad6f)

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/e95ef96e-4f71-428c-af15-79d63b9d5fe0)

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/db39c76b-0fb0-40ef-bd03-6a359e38e8ab)

**Notes:** 
- Type for global include should be "All". 
- Type field will be determined by array of lists 
- Organization of Types: subSegments, groupForSegment, individualForSegment
-  Display in UI: 
   - All: All
   - SubSegments: Segment 
   - groupForSegment: display group type (e.g. Teacher) and Group in parentheses: Teacher (Group)
   - individualForSegment: Individual
-

**Comment by Yagnik56** [comment]
@danoswaltCL did you pick this one? you didn't assign it to anyone so khanjan started working on this one...

**Comment by danoswaltCL** [comment]
@Yagnik56 @KD1712 apologies, yes I did, in fact there's a [PR.](https://github.com/CarnegieLearningWeb/UpGrade/pull/1670) I thought that I had assigned that to my self.
