### ISSUE TITLE
JS Client lib integration for new logger

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#163]
Integrate new logging format in the JS client library.

Client libs should have provision to pass session id to the logger instance or else Upgrade will create a random session id for a new user-specific session

**Comment by ppratikcr7** [comment]
@amurphy-cl Session id part was completed but the new logger format was in progress.

**Comment by RidhamShah** [comment]
I have added 2 new parts for the headers: 
`URL` - The URL from where the call is given, 
`Client Source` - tells whether the User had given a call from a browser or from node command
