### ISSUE TITLE
FF Root Table use status-indicator chip.

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1637]
Currently the Status column shows just the text as a placeholder, but we now have the "Common-Status-Chip-Indicator" which can now be implemented for this in the table rows.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/4cb01fad-1c09-4dc7-8a0c-04659777c734)

**Comment by bcb37** [comment]
QA: looks good.
