### ISSUE TITLE
Logger format change in all client controller functions

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#164]
We need to add logging in the client controllers to track the flow of client lib API calls.

**Comment by amurphy-cl** [comment]
@ppratikcr7 status update on this issue?

**Comment by ppratikcr7** [comment]
@amurphy-cl This is almost completed in [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/176). Vivek is looking into one small issue and code review. Will get back to you on this.

**Comment by nirmalpatel** [comment]
Pratik will finish this first as this affects many files in the backend.

**Comment by ppratikcr7** [comment]
@amurphy-cl Yes, this is done, I am testing on our development environment, will soon create a final PR and then start with the replica DB issue from monday.

**Comment by ppratikcr7** [comment]
We are opening this ticket to add few more logging changes:

1. Banner logs formatted in new logger format
2. Logs during email sent for exporting data
3. Adding creation time of user for logging and debugging null ids issue.
