### ISSUE TITLE
FF fix Delete Modal: wait on http response before close

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1648]
Modals should stay open after primary button click. All of our modals should follow this same UX pattern if there's an http call that is fired on primary click:

- Disable the primary button so that the user doesn't double-click
- Close on success response received.
- OR if error, stay open and re-enable the button.

**Comment by ppratikcr7** [comment]
@Yagnik56 @zackcl The delete modal seems to be bit off in size as compared to other modals.
![Image](https://github.com/user-attachments/assets/ba53a569-f0a2-47b8-a58a-c7bb7e4fec35)

**Comment by zackcl** [comment]
The width of the "Delete Feature Flag" modal is 480px in the original design in Figma. I think that should be correct in size.

<img width="512" alt="Delete Feature Flag" src="https://github.com/user-attachments/assets/ca969927-7426-412f-a9f4-bb71f2ec2489">
