### ISSUE TITLE
FF Fix: Status-Indicator-Chip text not updating when status is toggled

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1655]
Challenge:
Status-Indicator-Chip text not updating when status is toggled.
But the style does. They are based on the same data, so...

I couldn't figure it out at end of day, maybe you will be the hero.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/e0817d3d-ed8f-4117-9027-05d22c8e919c)

**Comment by bcb37** [comment]
QA: this works now
