### ISSUE TITLE
FF fix: styling in overview page details header

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1675]
Details page styling has been put on back-burner develop quicker, we should take a second and make this look at least closer to correct as in the Figma.

Zack will undoubtedly want to go through look through all of the styling, but we can at least get it looking pretty closer.

Check:
- Font sizing / weight in titles, subtitles
- Tab sizing
- Correct colors 

These are how it should look:

Figma: https://www.figma.com/design/GaKw3nDscTnMEOzIf4CAa7/UpGrade-UI-Latest-14-(Final)?node-id=24221-32109&t=TjNVTQ9hhOLwM0tC-0

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/01bf00d3-883c-427f-b0c0-42af251c7751)

Currently in dev:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/676fbaf7-b5fe-4031-b977-3529045287b5)

**Comment by Yagnik56** [comment]
QA passed
