### ISSUE TITLE
Stratifications Page Auto Refresh Not working as expected

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1689]
**Version where bug was found:**
e.g "5.2"

**Describe the bug**
After deleting strata, it doesn't remove the entry without refreshing the page or moving to another page. Also, Multiple imports also show 1st one at first, then on refresh we see others.

**Expected behavior**
The delete/import of stratas should reflect instantly on the UI.

**Comment by ppratikcr7** [comment]
@JayMehta11 Please look into this.

**Comment by JayMehta11** [comment]
Sure, I am working on this.
