### ISSUE TITLE
Export CSV Query Metrics Columns Missing due to absence of first user's query data

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1690]
**Version where bug was found:**
"5.2"

**Describe the bug**
Export CSV edge case: If the first user in the CSV rows is not having any query logs data, the metrics columns wont be shown in CSV data.

**Expected behavior**
We should store the metrics columns irrespective of users not having query logs data.

**Comment by bcb37** [comment]
QA: all metrics columns are shown, even without data.
