### ISSUE TITLE
Metrics Delete Modal, type 'delete'

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1694]
Instead of typing in the whole path of a metric to delete it, the modal should ask for them to type 'delete' like we do elsewhere

**Comment by ppratikcr7** [comment]
Also update the message on modal from "Type the metric path separated by space to confirm deletion:" to "Type 'delete' to confirm deletion:".

Use the env text "global.delete-confirmation.message.text" from en.json

**Comment by zackcl** [comment]
QA: Passed
