### ISSUE TITLE
Add common header and exposure data content components 

### ISSUE THREAD

**Issue by Yagnik56** [CarnegieLearningWeb/UpGrade#1696]
Add common header left and right component dor exposures and exposures content component.
Integrate include/exclude table context with the expand button.
Fix Alignment for mat-tabs to align it with other details on the page.

**Comment by zackcl** [comment]
QA Passed. I can confirm the `FeatureFlagExposuresSectionCardComponent` and `FeatureFlagExposuresDataComponent` exist although these are currently not visible since the "Data" tab is disabled for v1.
