### ISSUE TITLE
FF: Add description under flag name with tooltip

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1704]
We should be showing a tooltip over the description in small text below the title when present in the root table, same as the experiments and segments tables:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/b6a5f332-8762-4f84-82c6-54532b0f9ca0)

**Comment by amurphy-cl** [comment]
Reassigning to Zack and reopening to fix.

**Comment by Yagnik56** [comment]
QA passed
