### ISSUE TITLE
FF Extract Drag-And-Drop File Import as Common Component

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1713]
We have several places where a similar component has been designed, so we should extract the basic component used for the import modal as a reusable common component.

`common-drag-and-drop-file-import-component`:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/e4a3221c-02d6-4358-a0b8-419dedc6f171)

This component should:
1. accept a param to designate the proper file extension (currently, `.json` or `.csv` are the types)
2. accept a param for button label text string
3. files that are not of that type will not be able to be dropped into the large area
4. files that are not of that type will not be able to be selected from the native file-system dropdown on button click.
5. on select or drag end, this component should emit the raw file input to the parent without trying to parse it.

Note: This component is going to need to basically "disappear" after it does it's job, so it should not need to be coupled with any form or any other kind of input.

For instance, when selecting a feature-flag import file, this component will be present in the import modal, and will disappear after a valid file has been emitted.

There is also usage in a modal when selecting a csv of ids. The user will be able to click on a button in their text input, and they will then see this appear. Once the valid csv file has been selected, this component will disappear and the raw data will be parsed and validated by the parent, which will then populate the input field with string chips or do some error-handling itself.

**Comment by bcb37** [comment]
QA: this looks fine
