### ISSUE TITLE
Import / Export button

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1714]
We need the ability to support an icon(s) in the `common-tag-input` that will look like this when the user can upload a file:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/4d747a36-64ca-404a-bf29-5eb006fe7bb4)

And this when the user can download the values in the input:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/27dc9999-440d-4319-a242-a9d9255414b8)

This button should just toggle between `download` and `upload` states and emit its state to the parent which will handle the actual action that is produced by the click.

**Comment by zackcl** [comment]
QA: Passed
