### ISSUE TITLE
FF: Endpoint to Validate Imported JSON files

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1716]
On drag end or select of valid feature-flag JSON file(s) in the import modal, we will need to support a view that gives the user a list of files, their compatibility status (`COMPATIBLE`, `WARNING` and `INCOMPATIBLE`, and a text warning message for the warning and incompatible states that will give more complete information about what the user can expect or need to correct in order to proceed.

@ppratikcr7 @VivekFitkariwala please help me to fill out the details for acceptance criteria of the response and request so that it will look familiar to the way we do it for experiments.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/11251c12-278d-44b1-ade3-81bc07561d67)

**Comment by bcb37** [comment]
The response and request objects should look like they do for /api/flags/:id , with    "featureFlagSegmentInclusion" and "featureFlagSegmentExclusion" arrays that define the inclusion and exclusion lists, which should be created via calls to the /segment endpoints as part of the import action. I'm not sure we do it for experiments, but maybe we should verify that all included/excluded (public) segments already exist?

**Comment by amurphy-cl** [comment]
Reminder that for v1, imports will be one at a time. 

Imported feature flag design IDs should not be processed (a new ID will be assigned). 

Required fields: Name, Key, Description (can be null if empty), App Context, Tags (can be null), Include List, Exclude List

If there are public segments that don't exist during the import, the compatibility status will be `WARNING`
UI will say that "At least one segment listed in this feature flag could not be found".

**Comment by ppratikcr7** [comment]
For backend:

the /validation api will expect the below format:

[{
  fileName: string;
  fileContent: string;
}]
This api will return the below format:

[{
  fileName: string;
  compatibilityType: FF_COMPATIBILITY_TYPE;
}]
enum FF_COMPATIBILITY_TYPE {
  COMPATIBLE = 'compatible',
  WARNING = 'warning',
  INCOMPATIBLE = 'incompatible',
}
Based on the returned filenames and their compatibilityType, we can show the required message in the modal

**Comment by ppratikcr7** [comment]
@danoswaltCL @bcb37 @zackcl @amurphy-cl Just to confirm once, are we going to have the includeList and excludeList in import FF file? In the `Add feature` button next to the hamburger's `import ff` we only take the below details and allow to add or import the includeList and excludeList separately later.

`{ 
  "id": "be3ae74f-370a-4015-93f3-7761d16f8b11",
  "name": "test",
  "key": "FF_1",
  "description": null,
  "context": "sub",
  "tags": [
    "ff",
    "test"
  ]
}`

**Comment by amurphy-cl** [comment]
Yeah, only the constructed lists, not segments that are public.

**Comment by Yagnik56** [comment]
This [issue](https://github.com/CarnegieLearningWeb/UpGrade/issues/1918) is related to this PR.

**Comment by bcb37** [comment]
This works as expected. Moving to done

**Comment by ppratikcr7** [comment]
QA: Found a bug in this. If we try to import a duplicate feature flag which already exists, we show `compatible` label and we get a 500 error while clicking on import due to duplicate key constraint. I feel this was addressed and resolved for add feature flag but is remaining for import feature flag. @RidhamShah Can you please resolve this?
<img width="807" alt="Screenshot 2024-10-03 at 3 04 39 PM" src="https://github.com/user-attachments/assets/acc4f89d-4295-4364-8451-4b18d6f03fe3">
<img width="678" alt="Screenshot 2024-10-03 at 2 45 22 PM" src="https://github.com/user-attachments/assets/1fa95e5d-fc68-4da9-82a6-255401a5d3e1">

**Comment by Yagnik56** [comment]
I am working on this issue.

**Comment by ppratikcr7** [comment]
I will QA this

**Comment by ppratikcr7** [comment]
QA passed
