### ISSUE TITLE
FF: Pending state in Import Flag modal while validating json

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1717]
On successful drag end or on successful user-select (i.e. a json file was able to be parse), a call will go out to `/featureflags/validation`. While that call is pending:

- the large draggable "Import" widget will be hidden
- a spinner will show in the middle of the modal (retain the same height as when showing the widget though so it's not janky and popping up and down in height)
- when the response has been received, the spinner will disappear and the next state will be dispatched.

**Comment by zackcl** [comment]
The load-spinner sounds good to me.

**Comment by bcb37** [comment]
QA: this looks good.
