### ISSUE TITLE
FF: Design needed for Import Modal: Failed to parse file.

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1718]
When drag-dropping or selecting a file that, we will get the benefit of native html validation of the file extension where we won't even be able to select anything but `.json` or `.csv` files, but that doesn't mean the contents of those files are actually parse-able. We will need some kind of message to capture a parsing error (the user should be able to try again)

**Comment by zackcl** [comment]
For validating a CSV file (in the "Add Include/Exclude list" modal), I think we can simply show a red error message saying something like "Invalid CSV file." The message could be shown either below the "Choose CSV" button, or below the import box.

![Image](https://github.com/user-attachments/assets/04bf8869-cddc-4bee-b046-cdbe27076990)

For validating JSON files (in the import modals), we can show the compatibility in the modal like in the current design:

![Image](https://github.com/user-attachments/assets/155724a7-60b0-488a-939b-aca5ec428f90)

**Comment by danoswaltCL** [comment]
Since we are only showing one, we don't have to show the *Incompatible Files error message

**Comment by bcb37** [comment]
QA: This failed with an error when I attempted to import an empty file with a `.json` extension. It showed a blank modal with an enabled Import button which, when pressed, caused another 500 error.

**Comment by ppratikcr7** [comment]
@bcb37 Is this QA passed now? It is shown in done column, but I dont see that `Done` Activity here in this ticket.
