### ISSUE TITLE
FF: Import Modal File Validation Happy Path

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1720]
On successful selection and parsing of a JSON file, the UI will send a request to validate the file to the backend. On successful 200 ok of that validation, the file-uploader component will disappear and be replaced by a table that contains values in the following states:

`COMPATIBLE`: Greyed out carat, name of segment, `COMPATIBLE` status.
`WARNING` or `INCOMPLETE` will have an enabled carat and an expandable row to see detailed information.

TBD: The implementation of https://github.com/CarnegieLearningWeb/UpGrade/issues/1713 will give us the data type of the response.

1. If all of the files are incompatible, the primary "Import" button should be disabled.
2. If at least one file is 'warning' or 'compatible', the Import button should be enable.
3. On click of 'Import', we should see the import button disabled to prevent double-click, and we should see a load spinner.

Latest design (allow uploading only one file):

![Image](https://github.com/user-attachments/assets/3136eb77-ea17-43cc-a073-e542d4d75308)

![Image](https://github.com/user-attachments/assets/13bf8dc5-6b16-4b72-acf7-77daba4ad98b)

![Image](https://github.com/user-attachments/assets/f787ef0a-2875-46b2-b3e2-3851d237c782)

![Image](https://github.com/user-attachments/assets/5a47b687-ac3d-4585-9d7d-a6b5c1c72af3)

**Comment by ppratikcr7** [comment]
@danoswaltCL @bcb37 Is this fine? I can start with the api development.

**Comment by danoswaltCL** [comment]
yes please, can you put those details in the validation endpoint story as well and take needs refined off? It's all yours.

`fileContent` just means a valid feature flag JSON string, right?

https://github.com/orgs/CarnegieLearningWeb/projects/1/views/12?pane=issue&itemId=69574460

**Comment by ppratikcr7** [comment]
Yes right. `fileContent` means a valid feature flag JSON string. Ohh sorry searched for `validation` and could find only this ticket. Will add it there. Thanks for the link to the ticket.

**Comment by danoswaltCL** [comment]
all good, we need those details for this story too anyway

**Comment by bcb37** [comment]
@ppratikcr7  The API is good as it is, with no message needed from the backend
