### ISSUE TITLE
FF: Import Modal File Import success

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1721]
On import success, the modal should close, and the user should remain on the root page.

*If only one feature flag was imported, we could potentially nav to that details page, but since this modal can import more than one file, maybe we just stay put on root after imports?

Latest design (allow uploading only one file):

![Image](https://github.com/user-attachments/assets/79df548a-5c82-444f-ab94-db85d9269122)

![Image](https://github.com/user-attachments/assets/97551396-28e3-4ded-a694-d73fdad8de38)

![Image](https://github.com/user-attachments/assets/02e4eee6-d8ef-48f8-8f42-ccb04998a846)

![Image](https://github.com/user-attachments/assets/b4c47362-40a0-4271-93fb-e0918a49e9c2)

**Comment by zackcl** [comment]
Yes, I think we can just stay put on the root after imports, at least for now.

**Comment by Yagnik56** [comment]
do we want to start work on this issue @danoswaltCL or wait for the backend to get ready?
