### ISSUE TITLE
FF: Import Modal Import Fail state

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1722]
If an import fails, the import button should be reenabled and the user should be allowed to make changes. If we are not planning any specific messages for errors that might happen during import, we will be depending on the generic snackbar error.

Latest design (allow uploading only one file):

![Image](https://github.com/user-attachments/assets/54a42283-5d0f-4c77-8744-aca4ab4e6031)

![Image](https://github.com/user-attachments/assets/b5e83acd-2d8f-439d-83ef-062e3703aa50)

![Image](https://github.com/user-attachments/assets/6373c0ca-11d6-4dbf-8b7d-0941df58dfc3)

![Image](https://github.com/user-attachments/assets/c8bf731a-ba6c-4a12-8b30-77795807fc63)

**Comment by zackcl** [comment]
Here are the designs of the import modals as a reference (the "Import Include List" and "Import Exclude List" modals will look identical to the "Import List" modal):

![Image](https://github.com/user-attachments/assets/ce11d0f9-b049-4782-a5f0-5528273bb860)

![Image](https://github.com/user-attachments/assets/7c97efb8-09cf-4bc1-b768-3250c34840aa)

![Image](https://github.com/user-attachments/assets/4f87228e-78d4-428c-a5d6-f5c32d624ec0)

**Comment by bcb37** [comment]
QA: looks good
