### ISSUE TITLE
FF: Combobox for tag inputs?

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1723]
@zackcl I think we may need to hammer out what the design for this will need to look like. There is a handy component called `common-tag-input` that gives us a good deal of magic for the tag behavior. Do we want to:

- Extend the common-tag-input to be able to accept a list of searchable terms, giving us the 'combobox' behavior:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/4e153e49-9697-4853-b8be-85d8238c87fc)

- Have two inputs, a 'search' input combobox above to select a valid segment, and the common-tag input underneath it. Selecting a valid segment would fill in the tag name. You wouldn't be allowed to type in anything like a 'normal' tag input box, but you would be able to click the little X to remove them.

I can see either way working, but I'd vote for the second

**Comment by zackcl** [comment]
@danoswaltCL I'm not sure if I understand the second option, but I feel like having one input would make it simpler and more intuitive than having two inputs, if all we expect from the user is to complete a list of segments.

**Comment by danoswaltCL** [comment]
The difference really is that dealing with a list of raw strings is much simpler than dealing with objects, so if we want the dropdown combo to act and feel like what we do with strings, I'm trying to think of what's best to do with our common-tag-input component. We could...

- Extend it to be able to support a list of objects and a 'combobox' search-and-select. Drawback is that we add complexity.
- Have two separate tag-input implementations, one for `common-tag-string-input` and `common-tag-object-input` (or something....). Identical function behavior then can be put into a tag-input-helper service.

**Comment by zackcl** [comment]
@danoswaltCL If you export a list of segments to CSV, it will simply be a list of segments in the CSV file. This is basically the same as how we currently export a segment to CSV in UpGrade. For example, if you export the following segment (screenshot) to a CSV file, a file with the content below will be downloaded.

<img width="750" alt="Screenshot 2024-07-04 at 12 09 59 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/d53d90f6-c35f-4f4c-bbf9-0a82c3ea7279">


Seg1.csv:
```
Type,UUID
Segment,fwefwe
Segment,gewgewg2
```


If we export a list from the "Add Include List" modal, we would just need one column of values in a CSV. I think the filename would include the Type, though. When the user imports the file, it will simply fill the "Values" input field, with values separated by commas. I think we should also allow listing any strings, even if they didn't select one from the combo box options (just like listing tags). I think the final validation can happen when the user clicks on the "Create" button (or when each value is entered and converted to a chip).
