### ISSUE TITLE
FF Fix: Details Overview section card collapse all

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1725]
The intent of the "collapsible" carat on the details overview section card is to close and/or toggle all of the section cards on the page. Currently they are all indepedent.

**Comment by Yagnik56** [comment]
@danoswaltCL can you share where we want to put this? or do you want to use the current collapse button on the overview to collapse all at once?

**Comment by danoswaltCL** [comment]
Current collapse on the overview should be global for all cards, see around 3:50 of @zackcl 's video (if this link doesn't work, you can find it in the upgrade-design channel: https://carnegielearning.slack.com/files/U02DS8JDP0Q/F06QF0YKX40/feature_flags_design_v7.mov

**Comment by Yagnik56** [comment]
QA passed
