### ISSUE TITLE
FF Fix: Text of Include / Exclude button labels

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1726]
In last Thursday's mtg we demo'd this to Steve Ritter and he commented that the text for 'Add Include List' and 'Add Exclude List' should be shorted to just `Add` since we already have know the list type from the title of the section card.

Easy to do in the code but @zackcl created an issue since you weren't here in case that's something you'd like to update in Figma also.

**Comment by zackcl** [comment]
Closing this as we decided to keep the button labels for now.
