### ISSUE TITLE
FF: Implement Duplicate Feature Flag

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1727]
Implement the Duplicate Feature Flag modal.
- Selected from the root page menu
- The Name and Key should be appended with `_COPY` (or something?) as the suffix when prefilling the form values with the source flag's details (the user is expected to change this).
- This will otherwise work the same as the EDIT flow for pre-filling the details, and will call the same endpoint as ADD.
- As such, it may behoove us to consolidate these 3 states, add edit and duplicate, as one template modal called something like 'Feature Flag Details Modal'.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/cf8cbca3-8582-4c08-8f9b-03cf4dc9c4e1)

**Comment by danoswaltCL** [comment]
(I assigned myself since I already started this work, but we should properly refine it)

**Comment by Yagnik56** [comment]
@danoswaltCL the name and key aren't appended with _COPY as the suffix instead they are empty when we open the duplicate feature flag modal, did we change it or this is a bug?
