### ISSUE TITLE
Analytics Controller Swagger and Email send bugs and improvements

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1733]
**Version where bug was found:**
e.g "5.2.0"

**Describe the bug**
Need to add various swagger error codes in Analytics Controller and sending proper http codes for email send error. Also, there is an error of "Missing final '@domain'" due to comma in EMAIL_FROM env variable.

**Comment by bcb37** [comment]
QA: this works as expected, and swagger is correct
