### ISSUE TITLE
FF Handling 'All' filter mode in UI

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1738]
The user can toggle the to include all by selecting the all-in toggle on the FF details include table.

If `filterMode` of feature flag is "EXCLUDE_ALL":

The toggle will be set to disabled status, and the user will be able to manage include lists.

![Image](https://github.com/user-attachments/assets/408605f7-56da-4b50-9971-a76091ffb525)

If `filterMode` of feature flag is "INCLUDE_ALL":

The toggle will be set to enabled status, and the include table will be collapsed and the user will not be able to manage, view, or edit their include lists.

![Image](https://github.com/user-attachments/assets/43c3dea2-6540-47ea-ad7b-ce38fad2c03e)

**Comment by amurphy-cl** [comment]
Zack will mock up the option discussed today - All button outside of Include Lists table.

**Comment by zackcl** [comment]
Here's the updated UI design for handling the "Include All" option (notice that the section card collapses when the "Include All" is enabled). 

![Image](https://github.com/user-attachments/assets/d484d32f-d6f0-495b-b1ef-4a80ef05f1eb)

![Image](https://github.com/user-attachments/assets/4af03704-057f-43ca-ad0f-63b551e22cd8)

**Comment by bcb37** [comment]
There should be a confirm modal when toggle is clicked.

**Comment by zackcl** [comment]
QA: Passed
