### ISSUE TITLE
FF Export Single Feature Flag Design

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1744]
In overview menu, the user can export the Feature Flag Design:

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/1bf9bd78-0cf4-4ea8-9e51-a9a064f34458)

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/b4b2cd31-e5ed-4786-b895-0c93eb3a570f)

No functionality for submit yet, just configure and show the modal

**Comment by bcb37** [comment]
QA: looks good
