### ISSUE TITLE
FF: Import List Modal (Include and Exclude Table Menu Function)

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1746]
The user can open the Include or Exclude List Table menu and select to "Import List" (only difference between these two will be the modal text)

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/1121300e-d6dc-45f1-80d5-9742006e3b86)

This will open a standard confirmation modal such as this one, I don't have a pic of this at the moment but the language should be:

title: Import List
message: Are you sure you want to Import a List into the `Include Lists` || `Exclude Lists` table?

@zackcl let me know if that seems right!

- should this need validation like we do with other imports?
- can we give the user some hint about what a valid file might look like, either with an explicit example or a link to something in gitbook?

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/191069c0-87f4-4a3f-8ae7-8c62b5e072e9)

**Comment by zackcl** [comment]
> title: Import List
> message: Are you sure you want to Import a List into the Include Lists || Exclude Lists table?

I don't think we need a confirmation modal for importing lists. We would immediately show the import modal that allows uploading files, which looks like this:

<img width="500" alt="State=Default" src="https://github.com/user-attachments/assets/dcbf947e-6907-4dbb-bdc5-1a192f8a61b9">

<img width="500" alt="State=Imported" src="https://github.com/user-attachments/assets/da898fa1-f637-4f34-9b33-5ecd0aa260e0">
