### ISSUE TITLE
FF: Export All Lists Modal (Include and Exclude)

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1747]
The user can select "Export All Lists" from either of the Exclude or Include tables

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/e1bc8e64-c709-4a8d-bc66-f750989ad22e)

Need Design for Export All Lists confirm modal, but can probably guess it should say:
title: Export All Exclude Lists
message: Are you sure want to export all exclude lists?

**Comment by zackcl** [comment]
OK, I think that makes sense. Here are the updated designs:


![Image](https://github.com/user-attachments/assets/917a0034-9531-4b6f-8e8e-1aea1b08cfb5)



![Image](https://github.com/user-attachments/assets/d1c29a7d-c4e0-4cc5-b114-1de33d4889a1)


![Image](https://github.com/user-attachments/assets/6c2eb2d9-4879-4c4c-8efe-188f53b019e9)





![Image](https://github.com/user-attachments/assets/ff975956-80ab-43f5-a1e4-b820a7578c8a)



![Image](https://github.com/user-attachments/assets/134b6296-7e87-45f3-8ae7-4b45fe45ae1d)
