### ISSUE TITLE
FF: General Add List Modal

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1749]
Implement a modal that can be utilized for adding or editing lists for both Inclusion and Exclusion flows.

We should start with just the initial `type` selector, then other work can follow. Depending on the type selected, form will act differently, so we can start here and then develop the rest.

Screenshot (Updated):

<img width="688" alt="Feature Flag - Add Include List" src="https://github.com/user-attachments/assets/d9ebfce3-42ac-42b1-9ae0-a233369072c1">

Considerations:

- This modal will need to be templated for use in both the Include and Exclude List functionality
- This modal will need to be able to handle both Add and Edit functions

When the user opens this modal, we will only show a type selector at first. They can select:
- Segment
- Individual
- Group (listed by each group type supported in that context)

**Comment by danoswaltCL** [comment]
hola, the design shows (`All` won't be used now, ignore that):

`Individual`
`Segment`
`groupId1 (group)`
`groupId2 (group)`
`groupId3 (group)`

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/b3137d89-57db-49e9-92a2-6290319880c4)

Couple thoughts:

1. Is this the preferred order from user perspective? Segment will probably be the most used thing right, can it be topmost?

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/c536f419-dc14-45a2-a8f9-eedc94a43e2e)


2. While Zack was out I suggested a different format for how we show these groups [here] so they look more like the other options (https://carnegielearning.slack.com/archives/C02QA168MNW/p1718981331228129). That would be an app-wide change that can be implemented outside this later, but that would give us a list that looks like this for `assign-prog`. What do you think about that @zackcl 

That would look like this:
![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/b2a7bbf1-711b-46c1-8f91-9c61b39ce15a)

@amurphy-cl @bcb37

**Comment by zackcl** [comment]
Yeah, I like that! I can update the options to the following in Figma if @amurphy-cl confirms:

```
Segment
Individual
Group: schoolId
Group: classId
Group: instructorId
```

What I'm not totally sure about is how the group types are ordered. It looks like it's not alphabetical. Do you know how the order is determined?
<img width="500" alt="Screenshot 2024-07-12 at 5 58 51 PM" src="https://github.com/user-attachments/assets/f4c7a521-62c5-48e5-b09e-9780c920ef0f">

**Comment by amurphy-cl** [comment]
makes sense to be alphabetical, not sure why it wasn't previously

**Comment by zackcl** [comment]
Here's the updated design:

<img width="688" alt="Feature Flag - Add Include List" src="https://github.com/user-attachments/assets/2e815bcf-7438-4d53-8f2e-6f78b4f6bf75">

**Comment by zackcl** [comment]
I've updated the screenshot in the original post, where the "Group" is in alphabetical order:

```
Segment
Individual
Group: classId
Group: instructorId
Group: schoolId
```

**Comment by ppratikcr7** [comment]
@zackcl @amurphy-cl QA done for this. I dont see a decision made for the quotes around group names. But, I see that implemented in the code. Hope that's correct. Just one thing, I noticed that the segment names are not alphabetical, hope that's fine again, as we considered alphabetical order for the type dropdown.


![Image](https://github.com/user-attachments/assets/86d5f0a6-fc02-4923-abdb-8fcf0c947d6d)
![Image](https://github.com/user-attachments/assets/af89ac8f-45e5-4004-a21c-a1f6afea58db)

**Comment by zackcl** [comment]
Yes, I believe both the segment and group names should appear in alphabetical order (ascending order). Also, the group type should be in this format: `Group: groupId` as we discussed without the quotes. 

```
Segment
Individual
Group: classId
Group: instructorId
Group: schoolId
```
