### ISSUE TITLE
FF: Add List Modal: Individuals

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1750]
In Add List modal, the user can choose `Individual` as a type.

- The user will then see fields for:
`values: string[]` required
`name: string` required
`description: string`

- The values field will be a tag input that should incorporate csv import-export action button. This should be a one-column csv format of ids. Verify if header is needed. Can be done in separate task if this takes more effort than it looks!

- On change of `type`, all fields should be cleared.

- On submit, this list of Individual `userIds` will be sent:

Request example:

```
{
  "flagId": "ee53d1b5-8bcc-4d6b-a2ba-fada78a82879"
  "enabled": true,
  "listType": "individual",
  "list": {
    "name": "User List",
    "description": "This is a user list",
    "context": "assign-prog",
    "userIds": ["user1", "user2", "user3"],
    "groups": [],
    "subSegmentIds": []
  }
}
```

Latest design:

<img width="688" alt="Feature Flag - Add Exclude List 1" src="https://github.com/user-attachments/assets/c31ca841-71c9-4564-b303-6d2786752c11">

<img width="688" alt="Feature Flag - Add Exclude List (2)" src="https://github.com/user-attachments/assets/aee1d446-6bf6-4760-b6f0-064a992a7e96">

<img width="688" alt="Feature Flag - Add Exclude List" src="https://github.com/user-attachments/assets/762b27af-f968-4a22-88cc-e8901dce8228">

<img width="688" alt="Feature Flag - Add Exclude List (1)" src="https://github.com/user-attachments/assets/adc269fe-6ce2-4adb-b8a6-8f5552bd2158">

<img width="688" alt="Feature Flag - Add Exclude List 2" src="https://github.com/user-attachments/assets/03ad18ab-e0f2-45f4-bc6d-3fae68e3d8a8">

**Comment by zackcl** [comment]
What you described sounds correct, except that the order should be "Type", "Values", "Name", and "Description".

![Image](https://github.com/user-attachments/assets/5d8dd8e1-7f3c-4876-9899-e88d66e4be23)

![Image](https://github.com/user-attachments/assets/8f4dd4d8-889c-4259-a2ff-4729ac65309f)

**Comment by danoswaltCL** [comment]
@bcb37 add example of request to add-individual-userids

**Comment by zackcl** [comment]
@bcb37 Are you also working on the UI part of this issue? (updating the `UpsertFeatureFlagListModalComponent`)

**Comment by Yagnik56** [comment]
QA passed
