### ISSUE TITLE
FF: Add List Modal: Groups

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1751]
In Add List modal, the user can choose <groupType> as a type.

The user will then see fields for:
values: string[] required
name: string required
description: string

The values field will be a tag input that should incorporate csv import-export action button. This should be a one-column csv format of ids. Verify if header is needed. Can be done in separate task if this takes more effort than it looks!

On change of type, all fields should be cleared.

On submit, this list of Group ids will be sent.

Request example:

```
{
  "flagId": "ee53d1b5-8bcc-4d6b-a2ba-fada78a82879"
  "enabled": true,
  "listType": "Group(type)"
  "list": {
    "name": "User List",
    "description": "This is a user list",
    "context": "assign-prog",
    "userIds": [],
    "groups": [
       {
          "groupId": "school1",
          "type": "schoolId"
       },
          "groupId": "school2",
          "type": "schoolId"
       {
       }
     ],
    "subSegmentIds": []
  }
}
```

Latest design:

<img width="688" alt="Feature Flag - Add Include List" src="https://github.com/user-attachments/assets/efd5940c-6f31-48bb-adf6-c72458362a98">

<img width="688" alt="Feature Flag - Add Include List (2)" src="https://github.com/user-attachments/assets/c8ce92d4-0073-45d9-8116-cc9557396e08">

**Comment by zackcl** [comment]
![Image](https://github.com/user-attachments/assets/4a8667da-86b8-402f-a91a-f80dd30a318f)

**Comment by Yagnik56** [comment]
QA passed
