### ISSUE TITLE
FF: Add List Modal: Segment (Implement for Include)

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1753]
In Add List modal, the user can choose Segment as a type.

They will see a searchable input "combobox" where they can select from eligible segments for that flag's context, searchable by name.

Eligible Segments:
- every public segment available to that context
- no "global" exclude segment
- it is ok if the segment is already selected (maybe will do validation in a v2 later)

*NOTE: this will require making sure to fetch segments data if not exist

On change of type, all fields should be cleared.

*NOTE: The user should be warned on cancel button click or changing type that their info is going to be cleared if they click that button? It would suck to enter a bunch of values and then lose it.
- Decision: won't handle this for now.

On submit, this Segment Id or segment definition will be sent:

```
{
  "flagId": string(UUID),  // the id of the feature flag
  "enabled": boolean,
  "listType": string // 'segment', 'individual', etc.
  "list": { // 
    "name": string, // If type is 'segment', the segment name
    "description": string, //optional if type is 'segment' the segment description
    "context": string,
    "userIds": [ // Optional - populated if type is 'individual'
      string
    ],
    "groups": [ // Optional - populated if type is 'group'
      {
        "groupId": string,
        "type": string
      }
    ],
    "subSegmentIds": [] // Optional - populated with a single segmentId if type is 'segment'
  }
}
```

Latest design:

<img width="688" alt="Feature Flag - Add Include List" src="https://github.com/user-attachments/assets/744c785a-f78a-4754-9372-d66f562813e3">

<img width="688" alt="Feature Flag - Add Include List (2)" src="https://github.com/user-attachments/assets/3414bd3c-33df-46b9-8dea-7ecf1e107f81">

<img width="688" alt="Feature Flag - Add Include List (3)" src="https://github.com/user-attachments/assets/ddd22353-313a-411d-a22a-aecf62578383">

**Comment by zackcl** [comment]
> They will see a searchable input "combobox" where they can select from eligible segments for that flag's context, searchable by name.

I believe the UI for selecting a segment will be a dropdown instead of the combobox? At least this is how I designed it in the new design.

> *NOTE and question: Will all segments for that context always be eligible for selection? I assume we'll need to define some kind of filter here for things that are IN USE for example.

I'm not sure if I understand this. I think all segments for the context should always be eligible for selection, whether they are being used or not.

> *NOTE: The user should be warned on cancel button click or changing type that their info is going to be cleared if they click that button? It would suck to enter a bunch of values and then lose it.

I think it should be fine to lose the previously entered values on type change since the user can still click "Cancel" to close the modal. The values will remain if they reopen the modal.

**Comment by danoswaltCL** [comment]
@zackcl please add some design pics with segment combobox

**Comment by danoswaltCL** [comment]
@bcb37 please add example of request for add-segment

**Comment by Yagnik56** [comment]
QA passed
