### ISSUE TITLE
FF: Add Include-All toggle to the Include Table all header

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1758]
This story is to position that switch in the include table header and wire up the basic functionality.

The user will be able to toggle the FILTER_MODE property of the flag itself by toggling an 'Include All' switch in the include table header. By default, a newly created flag will have FILTER_MODE.EXCLUDE_ALL, so it will be in the off position.

When Include-All toggle is enabled, we will pop a confirmation modal that should give a pretty clear message about what the effect will be to the include lists.

@zackcl @amurphy-cl will need a design and some word-smithing for the confirmation modal for include-all confirmation modal and the exclude-all confirmation modal

When the toggle is confirmed and we will send a PUT request to `/featureflags/:id` with the value `FILTER_MODE.INCLUDE_ALL` for on, and `FILTER_MODE.EXCLUDE_ALL`.

Latest design:

![Image](https://github.com/user-attachments/assets/ac30d0c7-3243-431a-891b-beab4127c077)

![Image](https://github.com/user-attachments/assets/b75de25a-0fad-4cc1-a5dc-b28d2e481e5d)

![Image](https://github.com/user-attachments/assets/6943b8b5-1a22-41bc-a9b4-1193e119ca6d)

![Image](https://github.com/user-attachments/assets/7e553562-d5f0-42e7-8cfd-a532a6b26f95)

![Image](https://github.com/user-attachments/assets/27ca0176-4dcf-4a6a-9c71-dc9867fc5ec5)

**Comment by danoswaltCL** [comment]
I like the message that it sends when collapsing that we are clearly switching to "Include All" mode. But this design makes it look like we are still 'freezing' their ability to manage their lists when include all is selected, I couldn't tell from the video if there was any way for the user to still view and edit things.

@amurphy-cl for refinement tomorrow, can we answer some true or false for the user scenarios we want to support

When `Include All` is selected:

- The user cannot add a list: TRUE/FALSE
- The user cannot view their lists: TRUE/FALSE
- The user cannot edit a list's name and description: TRUE/FALSE
- The user cannot edit a list's enabled state: TRUE/FALSE
- The user cannot delete a list: TRUE/FALSE
- The count by "Include Lists" should go to zero: TRUE/FALSE

**Comment by Yagnik56** [comment]
QA: passed as per images provides in this issue
