### ISSUE TITLE
FF Fix: Duplicate key feature flag 500 error

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1762]
When submitting a feature flag, either from POST or PUT, the `key` that is submitted should be unique per the requested `context`. If it is not, the user should see an error and be given the chance to correct it.

For implementation, 409 HTTP status error should be sent back with a `type` of `SERVER_ERROR` enum designated for duplicate key error.

NOTE: We are not going to show this in the snackbar now, we have gone back to showing it in the form.

If the UI receives the error type, it should intercept it and trigger a specific validation message under the "key" form control:
"A flag with this key already exists for this app-context, please enter a unique key."

A snackbar notification will not be used for this error.

**Comment by amurphy-cl** [comment]
Error code should be 409 - CONFLICT to show duplicate key on submit.  Error should be below the submit button.

**Comment by zackcl** [comment]
The 409 error code seems appropriate based on ChatGPT and Google search results. I think the response could be something like this:

```
{
  "status": 409,
  "message": "A flag with this name already exists",
  "details": {
    "conflicting_field": "name"
  }
}
```

**Comment by RidhamShah** [comment]
I can take on this task.

**Comment by RidhamShah** [comment]
@danoswaltCL @zackcl A few questions regarding this issue
1. Do we want to check for both name and key to be unique?
2. The error msg of duplicate should be shown below the respective text box?
3. For the backend, create a validated end-point that returns 200 if all unique data is and throws 409 error with msg if a duplicate is found. Do you want to change anything in this approach?

**Comment by danoswaltCL** [comment]
1. Key definitely, I think we said name might be good to make unique also, but I don't remember. @amurphy-cl @bcb37

2. That would be ideal, but for this story I would vote to just put it into the snackbar message to limit the scope of this and get it done? I don't think it's a great idea to invent something on fly for each endpoint where we might want the UI to do more than just show the snackbar message. A simple unique error-code enum system would be my vote to keep the UI dumb and to keep the backend out of the UI's business of deciding how to handle user-facing content. It's not hard to do but that's gonna get a little in the weeds and deserves to be argued over in a separate ticket 😬 .

3. I think that sounds right.

**Comment by zackcl** [comment]
1. I think we decided to only make the `key` unique for v1, and later we might make the `name` unique also for experiments.

2. I think the error message is good enough for now, but we can definitely consider what Dan suggested later.

3. I think that sounds good as long as all the required fields exist.

**Comment by danoswaltCL** [comment]
https://github.com/CarnegieLearningWeb/UpGrade/issues/1794 is a dependency of this story now. @RidhamShah @zackcl please take a look at the re-written requirements for this, since we've gone back and forth, I want to make sure this story is solid and what others remember discussing.

**Comment by danoswaltCL** [comment]
QA: Passed
