### ISSUE TITLE
UserId error code regression

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1767]
When an /assign call is made with a 'userId' that doesn't yet correspond to an existing user, it now throws a 500 - Cannot read properties of null (reading 'requestedUserId'), rather than the expected 404.

**Comment by ppratikcr7** [comment]
I checked this, it seems to be fixed after the [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/1803) from zack was merged which has optional chaining operator for experimentUserDoc: `experimentUserDoc?.requestedUserId`.

I do get 404 error as below:
<img width="805" alt="Screenshot 2024-08-29 at 2 26 51 PM" src="https://github.com/user-attachments/assets/7e1ca6ca-f86f-4964-ab65-9414afc77284">

@bcb37 We can close this now.
