### ISSUE TITLE
FF: Simple Confirmation Modal

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1770]
@zackcl has basically designed 2 kinds of modals, form modals and simple modals. we dove into the complex form modals first and skipped right past the simple ones. the UX and implementation of the current form modals is way more than is needed for the simple info message ones. These are from the figma and are simple modals that should be able to be wired up and launched with a few pieces of data in `common-dialog-service` instead of new components.

![Image](https://github.com/user-attachments/assets/e428ec30-74a4-4dcb-ad6b-59a7b420e3ec)

Form modals have user input that can be validated and corrected if need be if an error is returned from the backend, and for that reason, the UX model for these is to wait until the response is either successful or the user abandons the form. They also are containers for complex logic that require more them to handle their own business. We dispatch the request from the primary click and handle listening in those modals, so it makes sense to have specific component implementations of those forms.

Simple confirmation modals need none of that, we have neglected to make a simpler template for the many modals that have one or two informational messages and have no need to have a brain of their own. Thus we should have a common reusable configuration and a common modal template that will allow us to create these modals. All buttons on simple confirmation button should trigger an immediate close, emitting a 'true' for primary-button click only so the parent can handle the rest.

For example, config inputs can be message strings with options for class.

```
export interface SimpleConfirmationModalParams {
  message: string;
  subMessage?: string;
  subMessageClass?: string;
}
```

For acceptance criteria, this should be true:

As a developer, I can launch a new simple common modal directly via passing in simple confirmation details, without needing to design any new modal component.

**Comment by zackcl** [comment]
QA: Passed
