### ISSUE TITLE
FF: Implement the Edit Button for the "Include/Exclude Lists" Table Rows

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1775]
Clicking the "Edit" button on the "Include/Exclude Lists" table rows should open the "Edit Include/Exclude List" modal, pre-filled with the row's field values. The "Save" button should remain disabled until the form is modified. Upon clicking the "Save" button after making edits, the modal should close, and the updated values should be reflected in the corresponding table row.

<img width="1536" alt="Feature Flag Details" src="https://github.com/user-attachments/assets/b918d4ba-29e3-4faa-ae84-5e45d7700ee5">

<img width="688" alt="Feature Flag - Edit Include List" src="https://github.com/user-attachments/assets/83351b82-4dbb-4da5-92bc-1f08eb77f750">

**Comment by Yagnik56** [comment]
@zackcl @bcb37 In the update list modal for individual lists, I cannot remove the value tags. There are no errors, but the value is not removed from the list. This issue occurs with both the include and exclude lists for individual lists, while the group list functions correctly.

https://github.com/user-attachments/assets/925694a0-7808-4f04-986f-2b2db0ac05ae

**Comment by Yagnik56** [comment]
QA passed
