### ISSUE TITLE
FF: Implement the Delete Button for the "Include/Exclude Lists" Table Rows

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1776]
Clicking the "Delete" button on the "Include/Exclude Lists" table rows should open the "Delete Include/Exclude List" modal to confirm the deletion. The message in the modal should include the corresponding list's name. Upon clicking the "Delete" button in the modal, the modal should close, and the corresponding row should be deleted from the table.

<img width="1536" alt="Feature Flag Details" src="https://github.com/user-attachments/assets/3939fad1-3156-47e9-b15e-7049ec18c127">

<img width="512" alt="Delete Include List" src="https://github.com/user-attachments/assets/cfcfb97b-9374-40f3-a094-6d66211d0a6e">

**Comment by Yagnik56** [comment]
QA passed
