### ISSUE TITLE
FF: Fetch Data for the "Include/Exclude Lists" Table Rows from Backend

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1778]
The data for the "Include/Exclude Lists" table rows should be fetched from the backend to render them on the table upon page load. 

<img width="1536" alt="Feature Flag Details (2)" src="https://github.com/user-attachments/assets/1ab78da9-b64f-48d6-81fa-5dc9ff0d3c1e">

The table data would need to look like the following to be assigned to the `@Input() dataSource$` in the `feature-flag-inclusions-table.component.ts` file:
```
const mockTableData = [
  {
    type: 'Individual',
    values: ['user1', 'user2', 'user3'],
    name: 'Test Students',
    enable: false,
  },
];
```

**Comment by danoswaltCL** [comment]
I think this is covered by other stories, the data doesn't need fetched separately from the feature flag call that already happens on page load.
