### ISSUE TITLE
FF: Disable or Hide the Menu Options for v2

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1780]
The menu options that we decided to implement for v2 on the Feature Flags Root and Details pages should be either disabled or hidden in the UI.

<img width="1536" alt="Feature Flags Root menu options for v1" src="https://github.com/user-attachments/assets/671e8630-238e-49d3-a8b6-2ec8cd1ada1e">

<img width="1536" alt="Feature Flags Details page menu options for v1" src="https://github.com/user-attachments/assets/7e3fcce5-f006-4158-8957-a8ff7a0e67e5">

**Comment by danoswaltCL** [comment]
@zackcl can you list out exactly what all should be disabled / hidden for MVP1? cc: @bcb37

**Comment by Yagnik56** [comment]
@zackcl we are going to hide the disabled options right? from menu

**Comment by zackcl** [comment]
@Yagnik56 Yes, that's correct! We should hide them.

**Comment by zackcl** [comment]
QA: Passed
