### ISSUE TITLE
Rendering of nested profile metrics runs out of memory

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1796]
Discovered while researching [this issue](https://github.com/CarnegieLearningWeb/UpGrade/issues/1703):

On the profile page, the rendering of the nested tree of metrics data runs out of memory when there is a top-level metric with thousands of children. This happens in all three deployed environments in the case of the 'masteryWorkspace' and 'conceptBuilderWorkspace' metrics.

This affects all deployed versions:

To reproduce on dev (v5.2): log into UpGrade > navigate to the profile page.
To reproduce on other environments (v5.1): log into UpGrade > navigate to the Metrics tab of the profile page > click on the '>' to expand the row for the 'masteryWorkspace' and 'conceptBuilderWorkspace' metrics.

Deliverable: 
Implement a fix that handles the volume of metrics data somehow without running out of memory (possibly by truncating the metric children data at some cutoff, or disabling the recursive tree display in some or all cases).

If there's no solution the allows the current design to handle the volume of data, we should limit the data being rendered for the current release (6.0), and then re-think the design. In that case, spawn an issue.

**Comment by RidhamShah** [comment]
@danoswaltCL @zackcl We discussed this issue and came up with a potential solution. We propose adding a search bar at the top of the metrics tree. This search bar would allow users to search for a metric name, including within the nested structure. Only the resulting metrics would be displayed as expandable, potentially alleviating the memory issue.

**Comment by zackcl** [comment]
Hey, I worked on this a little bit last week and I think it's still possible to display the tree without it freezing. I will try to share something today, but I'm also open to other suggestions, such as a search bar.

**Comment by danoswaltCL** [comment]
Qa'd and passed!
