### ISSUE TITLE
FF: Disabled Include List Participants are Included in the /featureflag Response

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1800]
**Version where bug was found:**
5.2.0

**Describe the bug**
While a feature flag is in "Enabled" status, it works as expected when:
- The "Include All" is enabled (All users are included)
- An Include List is enabled (All users in the enabled list are included)

However, when an Include List is disabled, it still works as if it is enabled.

**To Reproduce**
1. Define a feature flag in UpGrade
2. Define an Include List with user or group IDs.
3. While the Include List is disabled, request `api/v5/init` and then `api/v5/featureflag` with an included user/group ID.
4. You will see that the defined feature flag's key is included in the `/featureflag` response.

**Expected behavior**
The participants in the disabled Include Lists should not be included in the `/featureflag` response.

**Comment by bcb37** [comment]
Check for whether this is an issue for exclude lists as well.
