### ISSUE TITLE
Requesting /featureflag without /init should return a proper 404 response

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1802]
**Version where bug was found:**
5.2.0

**Describe the bug**
When `/featureflag` is requested without `/init` first, it throws `TypeError: Cannot read properties of null (reading 'id')` in the backend console. However, the proper response should be "Experiment user not defined (404)" to be consistent with how `/assign` works ([clientlib documentation](https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/clientlibs/js/README.md)).

**To Reproduce**
1. Make a request to `api/v5/featureflag` without `api/v5/init` first.
2. Check the backend console.
3. You will see the `TypeError: Cannot read properties of null (reading 'id')` in the console.

**Expected behavior**
Requesting `/featureflag` without `/init` should return a proper 404 response.

**Comment by ppratikcr7** [comment]
QA Done. Working as expected.

![Image](https://github.com/user-attachments/assets/8c4d7189-6a9e-4326-988e-ed7aaa2555cb)
