### ISSUE TITLE
Export Feature Flag endpoint

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1810]
`GET`

/flags/export/{id}

For exporting feature flag, we will be using the below headers:

'Content-Disposition', `attachment; filename="${filename}"`

As discussed we should be triggering the export JSON file without emulating a download click in HTML DOM object from the frontend

**Comment by ppratikcr7** [comment]
@danoswaltCL As discussed with Vivek we need to have a separate export api for this as well.

**Comment by bcb37** [comment]
Question from QA: should we send a 404 (or something other than a 500) when the feature flag is not found (i.e. the id is a UUID, but doesn't correspond to an existing feature flag)?

**Comment by bcb37** [comment]
This works as expected now.
