### ISSUE TITLE
FF fix: Enable the upload / download button functionality in Upsert-List values

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1812]
Enable the upload / download button functionality in Upsert-List values. The Upsert-List modal utilizes the common-tag-input component and we should need to turn it on and test that it's operating correctly.

**Comment by danoswaltCL** [comment]
I guess this should be MVP1 release, putting that tag on.

**Comment by Yagnik56** [comment]
QA: passed
