### ISSUE TITLE
FF Fix: Remove the second sentence in info message in include-all enable modal

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1815]
Per Ritter: Remove the second sentence in info message in include-all enable modal.

"Enabling this will include all participants."

Q: do exclude lists need mentioned?

![Image](https://github.com/user-attachments/assets/e35632bc-a28e-4917-b923-e81fa48a50ba)

**Comment by amurphy-cl** [comment]
QA passed
