### ISSUE TITLE
FF fix: Warning message when flag is enabled but no participants involved

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1817]
Per discussion in meeting after demo with @sritter, a new item to design and include in MVP1 would a preference for a special message and/or warning to the user if a flag is in an "enabled" state but no users are included.

We discussed ideas like a warning symbol on root page for that flag, and a more explicit message on the details page by the status chip.

Also discussed was a new status-chip / status called "Enabled - No Participants" but I think we decided against that in favor of just a UI warning.

Zack also mentioned possibility of making it impossible for enable to occur in a no-participant state, which potentially would be explained by a modal saying that a feature flag cannot be turned on without participants, but Steve said this should be allowed.

**Comment by ppratikcr7** [comment]
@zackcl It says this in your PR:

Implemented a tooltip saying "No include lists defined" when hovering over the "Enabled" status with the warning icon next to it.

But I see  "No include lists enabled". Hope this is intended text change later?

![Image](https://github.com/user-attachments/assets/4dcc6993-ac5d-4f5e-86d5-e0dda25f76eb)

**Comment by zackcl** [comment]
That's intended. Initially, we showed the warning when "No include lists defined", but later we changed it so that it shows the icon when "No include lists enabled".

> Ritter: Yeah, I’d display the warning icon if none of the include lists are enabled (with a tooltip saying “no include lists enabled”). I think it just emphasizes that the flag is technically on but isn’t really doing anything.
