### ISSUE TITLE
Incorrect FeatureFlag Validator components

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#1831]
**Describe the bug**
While working on this task, I identified an issue within the `FeatureFlagValidator` component. The validator treats `featureFlagSegmentInclusion` and `featureFlagSegmentExclusion` as objects containing segments as an array. However, in all other instances, we have defined `featureFlagSegmentInclusion` and `featureFlagSegmentExclusion` as arrays of objects, each containing segment, enabled, and listType.

Additionally, this validator is utilized in the create and update calls of the FeatureFlag, which do not include `featureFlagSegmentInclusion` or `featureFlagSegmentExclusion` (only name, key, context, and tags are present). This discrepancy is likely why the error has not surfaced, but it is crucial that we address this issue before it causes any disruptions.

**Expected behavior**
`FeatureFlagInclusion` and `FeatureFlagExclusion` should be an array of object containing Segment, enabled and listType

**Comment by bcb37** [comment]
QA: passed. FF Inclusions and Exclusions are validated with the correct types.
