### ISSUE TITLE
Include featureFlagSegmentInclusion in the api/flags/paginated response

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1838]
**Is your feature request related to a problem? Please describe.**
Currently, `featureFlagSegmentInclusion` is not included in the response from the `api/flags/paginated` endpoint, which we call on the Feature Flags root page. Because of this, displaying a warning icon when a feature flag is enabled with no enabled participants is not working as expected on the root page, as `featureFlagSegmentInclusion` is initially missing.

**Describe the solution you'd like**
~~The response from the `api/flags/paginated` endpoint should include `featureFlagSegmentInclusion` so that we can properly detect when to display a warning icon. We might also consider including `featureFlagSegmentExclusion` for consistency, although it is not currently needed.~~

The response from the `api/flags/paginated` endpoint should include `hasEnabledIncludeList`, which should be set to `true` if there is at least one enabled include list (`featureFlagSegmentInclusion`).

**Describe alternatives you've considered**
~~The response from the `api/flags/paginated` endpoint could include a field like `doesIncludeListExist` or `includeListLength` that would still allow us to implement the logic.~~

**Additional context**
- Related Issue: #1817
- PR (merged): #1830
- Relevant selector code: [Link](https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/frontend/projects/upgrade/src/app/core/feature-flags/store/feature-flags.selectors.ts#L169-L189)

- The current example response from `api/flags/paginated` where `featureFlagSegmentInclusion` is missing:

```
{
    "total": 1,
    "nodes": [
        {
            "createdAt": "2024-08-15T16:01:42.955Z",
            "updatedAt": "2024-08-16T15:16:59.508Z",
            "versionNumber": 44,
            "id": "aa25775d-4e20-4df7-8577-1726f51b08ab",
            "name": "My Feature",
            "key": "MY_FEATURE",
            "description": "",
            "context": [
                "assign-prog"
            ],
            "tags": [],
            "status": "enabled",
            "filterMode": "excludeAll",
            // "hasEnabledIncludeList": false <-- this should be added
        }
    ],
    "skip": 0,
    "take": 20
}
```

- A screenshot showing the flag with a warning icon even though it contains include lists:
![Screenshot 2024-08-19 at 11 54 56 PM](https://github.com/user-attachments/assets/f10fdee8-b973-4df1-b4a4-d7b37b7d6397)

**Comment by danoswaltCL** [comment]
This isn't a bug, this is expected behavior as Ben said, potentially was discussed when you were out. I argued the same thing but this was the decision that was made.

**Comment by zackcl** [comment]
I know it's technically not a bug, so I used the `Feature request` form for this ticket. I just wanted to clarify that it's something that should be fixed, but I can remove the "bug" tag if necessary.

**Comment by zackcl** [comment]
This ticket needs to be updated due to new design requirement mentioned in #1841.

**Comment by zackcl** [comment]
@bcb37 @RidhamShah @ppratikcr7  I've updated the original requirement for this ticket as confirmed by @amurphy-cl (https://github.com/CarnegieLearningWeb/UpGrade/issues/1841#issuecomment-2302220147). Please feel free to assign this to yourselves. 

> **Describe the solution you'd like**
The response from the `api/flags/paginated` endpoint should include `hasEnabledIncludeList`, which should be set to `true` if there is at least one enabled include list (`featureFlagSegmentInclusion`).
