### ISSUE TITLE
BadRequestError when updating a feature flag with one or more include lists defined

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1840]
**Version where bug was found:**
v6.0.0

**Describe the bug**
When I update a feature flag with one or more include lists defined, I get a `BadRequestError` saying the `PUT /api/flags/{flag_id}` request has an invalid body. Here's an example response:

```
{
    "httpCode": 400,
    "name": "BadRequestError",
    "message": "Invalid body, check 'errors' property for more info.",
    "errors": [
        {
            "property": "featureFlagSegmentInclusion",
            "children": [
                {
                    "property": "0",
                    "children": [
                        {
                            "property": "segments",
                            "children": [],
                            "constraints": {
                                "isArray": "segments must be an array",
                                "isNotEmpty": "segments should not be empty"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

**To Reproduce**
1. Create a Feature Flag with an include list of any type.
2. Click "Edit Feature Flag" menu option at the top overview section card.
3. Update something (Name, Key, Description, etc) from the form and click "Save."
4. You will see the "400 (Bad Request)" error in the console.

**Expected behavior**
The error should not happen when updating a feature flag with one or more include lists defined.

**Comment by RidhamShah** [comment]
This issue will be resolved by merging [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/1798). It is because the Validators in dev are not perfect and get updated in this PR. So once we merge this you can recheck this after it.

**Comment by zackcl** [comment]
QA: Passed
