### ISSUE TITLE
FF: Remove v2 UI elements

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1843]
- Remove 'Archive Feature Flag' from the actions dropdown on the Feature Flag detail page
- Remove the 'hamburger' buttons from the exclusion/inclusion list menus

![Image](https://github.com/user-attachments/assets/a5dcc035-aeb1-4adb-8558-becc3097e5c6)
![Image](https://github.com/user-attachments/assets/72d15d47-01d4-4023-96f1-8f74ce8a2940)

**Comment by zackcl** [comment]
QA: Passed
