### ISSUE TITLE
Add action for the 'View Logs' link and should store audit logs for feature flag updates

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1844]
The "View Logs" link on the feature flag details page currently does nothing. It should take you to some logs.

![Image](https://github.com/user-attachments/assets/7491a1cd-048e-42b1-9446-a8897826db63)

**Comment by Yagnik56** [comment]
@danoswaltCL @bcb37 should we redirect it to the logs tab?

**Comment by ppratikcr7** [comment]
Also we are not storing any audit logs for feature flag updates. We should store them and yes redirect this `View Logs` to Audit logs page.

**Comment by zackcl** [comment]
By the way, the original design in Figma was to display the "View Logs" modal for viewing only the logs of the current feature flag (similar to the "Enrollment Time Logs" modal on the experiment details page). I'm not sure if we decided to change this or if it's not possible to implement at the moment, though. @amurphy-cl @danoswaltCL  Any thoughts or suggestions?

<img width="1000" alt="Screenshot 2024-08-21 at 7 17 45 PM" src="https://github.com/user-attachments/assets/b58a6fbd-a920-4872-9b53-635ea141e88d">

**Comment by ppratikcr7** [comment]
@amurphy-cl Do we want to store these feature flag logs in audit logs and redirect the `View Logs` to Audit logs page or have a separate modal on the feature flag details page. If we plan to do the later one, we need to either store logs in a separate table or else add a column in audit logs table to differentiate it from other audit logs.

**Comment by Yagnik56** [comment]
Here is a list of changes we might like to add in audit logs for feature flag
- Creating FF
- Editing FF
- Delete FF
- Enable/ Disable FF
- Exporting FF
- Select all toggle in the include/ exclude list
- creating members in the include/ exclude list
- deleting members in the include/ exclude list
- editing members in the include/ exclude list
- importing/exporting multiple members in the include/ exclude list

Feel free to add comments or suggestions on this

**Comment by zackcl** [comment]
Closing due to a decision to remove the "View Logs" link for now. Related Issue: #1853
