### ISSUE TITLE
login/user api fails on login screen probably during routine token refresh

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1846]
**Version where bug was found:**
e.g "6.0.0"

**Describe the bug**
The login/user api gives 401 Unauthorised error when we are auto logged out from Upgrade or during routine token refresh.

**To Reproduce**
1. Go to upgrade login page or maybe after restarting the backend after a long time would trigger auto log out for logged in user in Upgrade.
2. See the snackbar error as below.

**Expected behavior**
We should not get that error before clicking the login button and we have some messed up login params.

**Screenshots**
![image](https://github.com/user-attachments/assets/1ae319ad-af8d-4bbc-b9d7-1962c6f70002)

**Comment by amurphy-cl** [comment]
Remove error snackbar for 401 errors since it will already redirect.
