### ISSUE TITLE
Deprecate/remove old client versions

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1852]
- Put a "deprecation" tag on the v4 client controller.
- Remove the older controller versions entirely (v1 and unversioned).
- Deprecate published client libraries? (npm?)

**Comment by amurphy-cl** [comment]
Add documentation (README in js client lib directory and gitbook) to clarify that these versions are deprecated. 

Deprecation tags should be in the swagger.

For release 6.0, we will say that we'll deprecate v4 (and add appropriate tags+documentation), and will remove it completely for the next major release. 

Need an additional story about the java client lib - maybe @kawcl can take care of this one.

**Comment by amurphy-cl** [comment]
We should do at least the first two bullet points for 6.0 release. If we can't do the third one, let's create a new issue for it.

**Comment by ppratikcr7** [comment]
QA:

I dont see deprecated tag in swagger for v4 as we already removed them in code.

Also, are the gitbook updates made for this? If yes, can we add the link to the updates gitbook PR here, so that we can verify that.

@bcb37

**Comment by amurphy-cl** [comment]
The gitbook changes will be addressed in a different task once 6.0 is finalized.
