### ISSUE TITLE
FF: Support Audit Log Types for Feature Flags

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1855]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have specific audit log types (enum) for feature flags, so we need to support them to enable proper filtering.

**Describe the solution you'd like**
The list of audit log types for feature flags:
- Feature Flag Created
- Feature Flag Updated (below lists belong to this type and are only included in the log message)
  - Feature Flag Include List Created
  - Feature Flag Include List Updated
  - Feature Flag Include List Deleted
  - Feature Flag Include List State Changed (enabled/disabled a specific include list or the "Include All" slide toggle) 
  - Feature Flag Exclude List Created
  - Feature Flag Exclude List Updated
  - Feature Flag Exclude List Deleted
- Feature Flag Deleted
- Feature Flag State Changed (enabled/disabled)
- Feature Flag Design Exported

Some examples ('My Feature Flag' links to the details page like how experiment logs work):
- "Successfully created 'My Feature Flag'."
- "Successfully updated 'My Feature Flag' - The include list 'My Schools' has been added."
- "Successfully updated 'My Feature Flag' - The include list 'My Schools' has been updated."
- "Successfully updated 'My Feature Flag' - The include list 'My Schools' has been enabled."
- "Successfully updated 'My Feature Flag' - The include list 'My Schools' has been deleted."
- "Successfully enabled 'My Feature Flag'."
- "Successfully deleted 'My Feature Flag'."

**Additional context**
I tried to make the log types consistent with the existing ones for experiments:
<img width="1000" alt="Screenshot 2024-08-23 at 12 00 20 AM" src="https://github.com/user-attachments/assets/d545e9b5-c99f-4c95-847e-2fcd83017e14">

For your reference, the log messages can be more concise if we implement the local logging in the future:
<img width="1000" alt="359855483-b58a6fbd-a920-4872-9b53-635ea141e88d" src="https://github.com/user-attachments/assets/72d4d692-d972-4b91-a2bf-3c4ee726b76e">

Related issue: https://github.com/CarnegieLearningWeb/UpGrade/issues/1844

**Comment by zackcl** [comment]
@amurphy-cl @danoswaltCL @bcb37 @VivekFitkariwala @ppratikcr7 @Yagnik56 Please let me know what you think about the Audit Log Types I listed above.

**Comment by amurphy-cl** [comment]
@Yagnik56 will create a new issue and PR for front end work

**Comment by RidhamShah** [comment]
I am doing QA for this isssue
