### ISSUE TITLE
Restore `upsert()` call to v5.2 release

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1864]
Add to release 5.2: Use the tpyeorm `upsert()` method for user creation, rather than `save()` (relates to: https://github.com/CarnegieLearningWeb/UpGrade/issues/1044)
 
The same change was merged to dev https://github.com/CarnegieLearningWeb/UpGrade/pull/1304 but was omitted in subsequent releases.

**Comment by ppratikcr7** [comment]
@bcb37 Can we closer this ticket, it is completed.
