### ISSUE TITLE
Getting swagger syntax error in FeatureFlag Controller

### ISSUE THREAD

**Issue by Yagnik56** [CarnegieLearningWeb/UpGrade#1882]
While running the backend in dev, I came across this swagger syntax error in backend.
![image](https://github.com/user-attachments/assets/5d3f6d77-cceb-4be6-bb18-6395ee77f0b7)

**Comment by amurphy-cl** [comment]
Ben will fold this into other changes he's making in the swagger for automated testing.

**Comment by Yagnik56** [comment]
QA: passed
