### ISSUE TITLE
Metrics not handled correctly by initMetrics.ts

### ISSUE THREAD

**Issue by Innoviox** [CarnegieLearningWeb/UpGrade#1884]
**Version where bug was found:**
dev latest (54de016)

**Describe the bug**
The current `.env.docker.local.example` has a different idea of what should be in `METRICS` than `backend/packages/Upgrade/src/init/seed/initMetrics.ts`. In the env, it is just a metrics array, but `initMetrics` expects an object containing a `metrics` and a `contexts` attribute. This causes `MetricService.saveAllMetrics` to be called with `metrics=undefined`, which instantly crashes the app.

**To Reproduce**
Install the app:
1. git clone https://github.com/CarnegieLearningWeb/UpGrade.git
2. cd Upgrade
3. cd frontend && npm install
4. cd ../backend/packages/Upgrade && npm install
5. cd ../../../ && mv ./backend/packages/Upgrade/.env.docker.local.example ./backend/packages/Upgrade/.env.docker.local
6. docker-compose -f singleContainerApp-docker-compose.yml up -d

**Expected behavior**
The backend starts up correctly.

**Screenshots**
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/8ce594a3-8bfb-4f7c-95cf-fc9f96cbdf3b">
<img width="707" alt="image" src="https://github.com/user-attachments/assets/b1ef067b-19bc-48f2-820d-68cd5f24abb3">

**Desktop (please complete the following information):**
 - OS: macOS 14.1.1
 - Docker version 25.0.3, build 4debf41

**Additional context**
To fix this, I believe the `.env.docker.local.example` should have an updated `METRICS` that reflects its actual usage in the application. Additionally, in backend/packages/Upgrade/src/api/services/MetricService.ts, line 168, this line could be added:
```
private parseMetrics(metrics: Array<IGroupMetric | ISingleMetric>): IMetricUnit[] {
    // add this line since this function gets called with undefined
    if (!metrics) return [];
    // ... rest of file
```
to prevent issues like this from completely crashing the backend.

**Comment by ppratikcr7** [comment]
@Innoviox Thanks a lot for pointing this out. We will update this and create a PR soon.
