### ISSUE TITLE
Enrollment and metric data is inconsistent

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#19]
Sometimes when I look at an experiment, I see no enrollees (see first screenshot). Then I go out and back into the experiment and see some enrollees (see second screenshot). These screenshots were taken 2 minutes apart. I suspect there's some kind of timeout error (sometimes) happening on the server.

Also, in the second screenshot, you can see no data under "average time to complete workspace". I had previously seen data for this metric, so that could also be a timeout issue (note, though, that the server recognizes that there is some data - if there's no data, the metric clearly shows the message "No Data"). So this might be a separate bug.

<img width="1743" alt="Screen Shot 2021-02-08 at 12 48 53 PM" src="https://user-images.githubusercontent.com/16547537/107260823-8ba61000-6a0c-11eb-83ec-227ab9a8429b.png">

<img width="1294" alt="Screen Shot 2021-02-08 at 12 50 35 PM" src="https://user-images.githubusercontent.com/16547537/107260909-a5dfee00-6a0c-11eb-9501-fc65aa3638b8.png">

**Comment by nirmalpatel** [comment]
@SritterCL @amurphy-cl the first part of this issue (no data in graph for the first time, visible data on refresh) might be:

- Related to #118 (infinite spinner for enrollment by condition section)
- OR solved when we solved the query performance issue
- OR a separate issue

The second part of the issue (missing metric data) is being tracked in #121
