### ISSUE TITLE
Email is not being sent on experiment export

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#190]
I tried to export an experiment in UpGrade both locally and through our [production website](https://upgrade.carnegielearning.com/) but I have never gotten an email from UpGrade even though it says an email will be sent.

I talked about this in our team meeting and Kyle confirmed that he couldn't get an email either.

EDIT: Wring this issue, I just received an email from UpGrade with the exported data, but I think the last time I exported an experiment was like 2 hours ago, so I'm not sure if it simply takes a long time to receive an email. Still, I think it should be faster to receive the email.

Can we clarify if this feature works properly? Also, I personally think it would be better to make the experiment data directly downloadable in UpGrade without going through email. Is there a reason to not make them directly downloadable? Thank you!

**Comment by amurphy-cl** [comment]
@nirmalpatel This is fixed, right? If so I think we can close it. BUT I will add a separate issue requesting that a log item be added to confirm that the email has been sent.

**Comment by nirmalpatel** [comment]
@amurphy-cl @ppratikcr7 started working on this issue today. We will fix this first and then go to the replica issue.

**Comment by amurphy-cl** [comment]
@nirmalpatel Are you waiting for us to review this and #208 and merge?

**Comment by ppratikcr7** [comment]
@amurphy-cl I have already verified this, it works in the same latest CL's main branch code that is deployed to our development environment. I also checked this in the demo application that Zack made with the same experiment. There it doesn't work. The only reason is the environment variables set for `HOST_URL`, `EMAIL_BUCKET` and `AWS_REGION`. If corresponding bucket or host_url is not present then the mail wont be triggered. I have informed all this to Zack and he has raised a JIRA ticket for the same to redeploy the backend with proper environment variables. Once that's done, it should work. Also, you can go ahead and merge [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/210)  for #208.

**Comment by amurphy-cl** [comment]
@zackcl do you know what the status is of the internal Jira ticket meant to address the email issue in the CL environment?

**Comment by zackcl** [comment]
Here's the link to the Jira task: https://carnegielearning.atlassian.net/browse/DEVOPS-752

I believe @mfugate1 is working on this. I hope he will help us soon.

**Comment by amurphy-cl** [comment]
I'm going to close this for now since the issue appears to be on the CL side with elastic beanstalk deployment, otherwise the email works.
