### ISSUE TITLE
Refresh (or URL) goes to Experiment list from FF details page

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1904]
Steps to reproduce:
- Navigate to the details page for a Feature Flag (or Experiment)
- Refresh the page in the browser (or copy the URL and load it in a new tab)

Expected behavior: it should display the details page.

Actual behavior: The Experiment list page is displayed.

**Comment by zackcl** [comment]
@danoswaltCL I've assigned you to this issue. Please feel free to look into it.

**Comment by ppratikcr7** [comment]
QA Done: Working as expected
