### ISSUE TITLE
Editing a FF with lists fails with an error

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#1905]
Steps to reproduce:

- Navigate to the details page of a FF with at least one Exclusion or Inclusion list defined
- Select 'Edit Feature Flag' from the top menu
- Make a change to the Feature Flag and attempt to save it from the modal

Expected behavior: The FF is updated and the modal closes

Actual behavior: Modal remains and a 400 error is thrown.

**Comment by zackcl** [comment]
Is this fixed? I can no longer reproduce it.

**Comment by bcb37** [comment]
This seems to be fixed.
