### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createdAt') when navigating to some FF details page

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1910]
**Version where bug was found:**
6.0.0

**Describe the bug**
When navigating to some FF details page (e.g., Test13 from QA env), the page doesn't properly load the Include/Exclude Lists due to the `TypeError: Cannot read properties of undefined (reading 'createdAt')` error.

**To Reproduce**
1. Go to https://upgrade.qa-cli.net/
2. Sign-in and go to FF root page
3. Click the feature flag named "Test13"
4. See error on the browser console.

**Expected behavior**
The error should not happen.

**Screenshots**
<img width="1440" alt="Screenshot 2024-09-10 at 1 18 52 AM" src="https://github.com/user-attachments/assets/c17741cd-bc81-4f84-926a-16cdd0777a75">

**Comment by bcb37** [comment]
QA: can't reproduce the bug anymore.
