### ISSUE TITLE
segment list created for feature flag which doesn't exist

### ISSUE THREAD

**Issue by Yagnik56** [CarnegieLearningWeb/UpGrade#1918]
Issue: 
In the add list, we can only select a segment if it exists with the same context as the feature flag, but while importing, we haven't applied any validation to make sure the segment list that is getting created already exists. This might apply to groups as well.

(For this case warning should be shown on import while creating but was not showing)

**Comment by RidhamShah** [comment]
A validation was also added to check multiple imports of duplicate files as the second file will try to create on key already used and throw an error.

**Comment by Yagnik56** [comment]
segment list should be ignored if it doesn't exist but here that's not happening and it is getting created.
Also, the segment list validation is just checking the id and attaching a list to a segment with a different context which shouldn't be allowed.

**Comment by ppratikcr7** [comment]
I will QA this

**Comment by ppratikcr7** [comment]
QA passed
