### ISSUE TITLE
FF: Support capital letters for user-entered values/tags

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1925]
**Is your feature request related to a problem? Please describe.**
Currently, the user-entered values and tags are automatically converted to lowercase. This makes it not possible to create a tag such as "MATHia" or values/IDs that contain capital letters. Also, we support including capital letters for experiment participants, but not feature flag participants. We should make it consistent.

**Describe the solution you'd like**
We should support capital letters for user-entered values/tags for better usability and flexibility.

**Additional context**
Tags shouldn’t be case-sensitive in matching. If it’s “mathia” in one feature flag but “MATHia” in another, we should be able to click (or search) one and see both.

**Comment by Yagnik56** [comment]
QA passed
