### ISSUE TITLE
Investigate replicating UpGrade DB (read-only replica)

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#195]
Queries like data export could go against a read-only DB that is a replication of the main DB. We should investigate creating a read-only replication and offloading read only requests to that DB.

**Comment by amurphy-cl** [comment]
@nirmalpatel based on last week's meeting, this task is on-track for this week, right? To be clear, we think it's only data exports that will go to the replica DB. We may change this in the future. LMK if there are any blockers.

**Comment by amurphy-cl** [comment]
@nirmalpatel can you give a status update on this at tomorrow's meeting?

**Comment by nirmalpatel** [comment]
@amurphy-cl no update as there are many issues going on in parallel and only Pratik is there to address them this week. See here: https://github.com/CarnegieLearningWeb/UpGrade/projects/1

**Comment by danoswaltCL** [comment]
ok, bringing this back from the dead, dev environment now has a read-replica spun up. I see some sql statements (they get cut off in AWS): 

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/fe476ed7-1abd-44c8-9992-4af34f8103ce)

`SELECT "experiment"."id" as "experimentId", "experiment"."name" as "experimentName", "experiment"."context" as "context", "experiment"."assignmentUnit" as "assignmentUnit", "experiment"."group" as "group", "monitored"."site" as "site", "monitored"."target" as "target", "individualEnrollment"."userId" as "userId", "individualEnrollment"."partitionId" as "decisionPointId", "individualEnrollment"."groupId" as "groupId", condition."conditionCode" as "conditionName", MIN("monitoredPointLogs"."created`

`SELECT "logs"."data" as data, "queries"."id" as id, "queries"."name" as name, queries."repeatedMeasure" as "repeatedMeasure", logs."userId" as "userId", logs."updatedAt" as "updatedAt", "metric"."key" as key, "metric"."type" as type FROM "experiment" "experiment" INNER JOIN "query" "queries" ON "queries"."experimentId"="experiment"."id"  INNER JOIN "metric" "metric" ON "metric"."key"="queries"."metricKey"  INNER JOIN "metric_log" "metric_logs" ON "metric_logs"."metricKey"="metric"."key" INNER JO`

`DECLARE "query-cursor_1" SCROLL CURSOR FOR select queryid, left(query, 100000), calls, (total_plan_time + total_exec_time) as total_time from pg_stat_statements order by calls desc limit 5000 FOR READ ONLY`

**Comment by bcb37** [comment]
Verified that the export query is hitting the replica on dev. Spawning https://github.com/CarnegieLearningWeb/UpGrade/issues/1389 and closing this.
