### ISSUE TITLE
Add metrics fails in UI

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1984]
**Version where bug was found:**
6

**Describe the bug**
Add metrics in UI fails due to "context" needing to be an array instead of string.

```
{"metricUnit":[{"metric":"completionStatus","datatype":"categorical"}],"context":"mathstream"}
```

**To Reproduce**
![Image](https://github.com/user-attachments/assets/e715dd37-3ac7-4d6f-9238-6e3ad5e59c2d)

**Comment by ppratikcr7** [comment]
QA passed.
