### ISSUE TITLE
init api for v6 version should not allow userid in body

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1994]
**Version where bug was found:**
e.g "6.0"

**Describe the bug**
init api for v6 version should not allow userid in body. Currently this happens as we dont throw user not defined error from CheckUserMiddleware for init api.

**Comment by ppratikcr7** [comment]
@zackcl Can you please QA this?

**Comment by zackcl** [comment]
QA: Passed.

I can confirm that I get the error when I include `id` in the body:
```
{
    "httpCode": 400,
    "name": "BadRequestError",
    "message": "Invalid body, check 'errors' property for more info.",
    "errors": [
        {
            "property": "id",
            "constraints": {
                "whitelistValidation": "property id should not exist"
            }
        }
    ]
}
```
I also get the error when I don't include "User-Id" in the header:

```
{
    "type": "Missing `User-Id` header",
    "httpCode": 400
}
```
