### ISSUE TITLE
Adding, Importing, Editing, and Deleting a Feature Flag Should Not Be Allowed for Users with the 'Reader' Role

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1998]
**Version where bug was found:**
6.0.0

**Describe the bug**
Currently, adding, importing, editing, or deleting a feature flag is allowed for users with the 'Reader' role. We should not allow this.

**To Reproduce**
1. Go to the Profile page and update your role to 'Reader' (note: not sure how to revert to 'Admin' later though).
2. Go to the Experiments/Segments root and details pages, and observe that the options for adding, importing, editing, and deleting an experiment or segment are hidden or disabled.
3. Go to the Feature Flags root and details pages.
4. Observe that the options for adding, importing, editing, and deleting a feature flag are available.

**Expected behavior**
Adding, importing, editing, and deleting a feature flag should not be allowed for users with the 'Reader' role, just like how the Experiments and Segments pages work.

Root page:
- The "Add Feature Flag" button should be hidden or disabled.
- The "Menu" icon button should be hidden (since we currently have only the "Import Feature Flag" menu option).

Details page:
- "Edit Feature Flag", "Duplicate Feature Flag", and "Delete Feature Flag" menu options should be hidden.
- "Add Include List" and "Add Exclude List" buttons should be hidden or disabled.
- All slide toggles should not respond to mouse events, and the cursor should be `not-allowed` on hover.
- All "Edit" and "Remove" icons from the Include/Exclude Lists tables should be greyed out and not respond to mouse events.

**Comment by ppratikcr7** [comment]
@zackcl Just observed that we allow importing stratification factors in reader mode:
<img width="1039" alt="Screenshot 2024-10-03 at 2 26 39 PM" src="https://github.com/user-attachments/assets/86bf612d-f49a-4abb-89c8-5b05c578e737">

Can you please create a separate ticket for that and handle it so that we are all clear for reader role.

**Comment by ppratikcr7** [comment]
QA passed
