### ISSUE TITLE
Day of week in enrollment UI doesn't match real enrollment date

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#20]
Day of week that shows participant enrollment isn't lining up with the actual day of experiment running.
Also ideally we should show month/day, possibly even month/day year instead of simply day of week since most experiments will cross multiple weeks.

**Comment by msandbothe** [comment]
Any hypotheses from investigating this yet?

**Comment by RidhamShah** [comment]
The issue is nearly solved - now we can get client Timezone through API and the server will make changes according to it and display properly. Also if the client changes the timezone the graph will be adjusted according to the new timezone.

**Comment by RidhamShah** [comment]
@amurphy-cl This issue is solved when I created the PR.
