### ISSUE TITLE
Disallow Importing Stratification Factors for Users with the 'Reader' Role

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#2009]
**Version where bug was found:**
6.0.0

**Describe the bug**
We should not allow importing stratification factors for users with the 'Reader' role.

**To Reproduce**
1. Go to the Profile page and update your role to 'Reader' (note: not sure how to revert to 'Admin' later though).
2. Go to the Participants page and click the "Stratifications" tab.
3. Observe that the "Import CSV" button is visible and clickable.

**Expected behavior**
The "Import CSV" button above the Stratifications table should be invisible for users with the 'Reader' role.

**Screenshots**
<img width="1039" alt="Screenshot 2024-10-03 at 2 26 39 PM" src="https://github.com/user-attachments/assets/86bf612d-f49a-4abb-89c8-5b05c578e737">

**Additional context**
Related Issue: https://github.com/CarnegieLearningWeb/UpGrade/issues/1998

**Comment by danoswaltCL** [comment]
I will QA

**Comment by danoswaltCL** [comment]
passed
