### ISSUE TITLE
Make the Feature Flags Root Section Card Scrollable

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#2011]
**Is your feature request related to a problem? Please describe.**
Currently, the feature flags root section card expands infinitely as the list grows, making the top UI elements (heading, search field, buttons) invisible when scrolled to the bottom.

**Describe the solution you'd like**
The feature flags root section card should have a maximum height so that its content section can be scrollable. This makes the top UI elements always visible, which is better for the user experience.

**Additional context**
We might consider also applying this to other section cards on the details page later if needed.

**Comment by ppratikcr7** [comment]
I will QA this

**Comment by ppratikcr7** [comment]
QA passed
