### ISSUE TITLE
/experiments endpoint bugs from testing

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#2013]
Change the following endpoints to return the indicated responses:

- GET /experiments/single/[id] => return 404 when no experiment is found; return 400 when [id] is not a valid UUID
- GET /experiments/conditions/[id] => return 404 when no experiment is found; return 400 when [id] is not a valid UUID
- GET /experiments/getGroupAssignmentStatus/[id] => return 404 when no experiment is found; return 400 when [id] is not a valid UUID
- DELETE /experiments/[id] => return 404 when no experiment is found; return 400 when [id] is not a valid UUID

**Comment by bcb37** [comment]
These changes resulted in the /init call returning a 404 called with a new user.

**Comment by Yagnik56** [comment]
@bcb37 This issue is related to changes in experiment endpoints; the error you are getting is related to experimentUserService. This PR didn't make that change.
![Image](https://github.com/user-attachments/assets/eaba01ac-383a-403f-9013-99f6335ead4c)

**Comment by ppratikcr7** [comment]
@bcb37 @Yagnik56 I will push a fix for this. It is due to a PR for this [ticket](https://github.com/CarnegieLearningWeb/UpGrade/issues/2045). I will open this [ticket](https://github.com/CarnegieLearningWeb/UpGrade/issues/2045) and close this one.
