### ISSUE TITLE
Duplicate Feature Flag Import gives 500

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#2019]
**Version where bug was found:**
6

**Describe the bug**
Duplicate Feature Flag Import gives 500

**To Reproduce**
![Image](https://github.com/user-attachments/assets/c9133755-dbc1-46ef-b559-90558a4957a5)

It doesn't appear to remove the id from the import, and it throws "Query Failed" 500.

**Comment by ppratikcr7** [comment]
@danoswaltCL I had already [reported](https://github.com/CarnegieLearningWeb/UpGrade/issues/1716#issuecomment-2390957864) this bug yesterday and re-opened the relevant validation api ticket and assigned yagnik to it. I had mentioned the same in yesterday's Technical meeting. Can we close this? Or assign yagnik to this ticket and close the previous one?

**Comment by ppratikcr7** [comment]
I will QA this

**Comment by ppratikcr7** [comment]
QA passed
