### ISSUE TITLE
We are using redundant class validators for various validation checks.

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#2042]
**Version where bug was found:**
e.g "6.0.0"

**Describe the bug**
We are using a redundant `@IsString` and `@IsDefined` class validators throughout the codebase for validation checks at various places. The `@IsString` validation already takes place with the subsequent `@IsUUID()` validator internally. Same goes for `@IsDefined` which checks for `!=null or !=undefined` which is already being checked under `@IsNotEmpty()` which checks for `!= '' or !=null or !=undefined`. We should remove these redundant class validators.

**Comment by danoswaltCL** [comment]
oops didn't mean to close
