### ISSUE TITLE
Disallow Duplicating a Segment Using an Existing Name

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#2069]
**Version where bug was found:**
6.1.0

**Describe the bug**
The segment name should be unique within each app context. We currently disallow creating a segment with an existing name when using the "Add Segment" button. However, we allow duplicating a segment using an existing name when using the "Duplicate" button on the details page. We should not allow creating a segment using a name that already exists.

**To Reproduce**
1. Go to the Segments root page.
2. Click on any defined segment.
3. Click the "Duplicate" button.
4. Change the name of the segment to match an existing one.
5. Observe that the segment is created with the same name, resulting in two segments with the same name and app context.

**Expected behavior**
We should not allow duplicating a segment using an existing name. A validation error message should be displayed below the "Name of the duplicate segment" field.

**Comment by amurphy-cl** [comment]
We shouldn't consider private segments for testing duplicates. This issue only pertains to "public" segments.
