### ISSUE TITLE
Disallow Editing (Name, Key, App Context) or Deleting an Enabled Feature Flag

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#2070]
**Is your feature request related to a problem? Please describe the solution you'd like.**
When a flag is “Enabled”, we should not allow editing the “Name”, “Key”, and “App Context” fields on the “Edit Feature Flag” modal (these fields should be disabled and greyed out) for safety reasons, but we should allow editing the “Description” and “Tags”. Additionally, the “Delete Feature Flag” menu option should be disabled and greyed out.

**Describe alternatives you've considered**
We could also consider simply disabling both the "Edit Feature Flag" and "Delete Feature Flag" menu options. However, I think always allowing editing of the "Description" and "Tags" could be convenient.

**Comment by amurphy-cl** [comment]
For this issue, we won't worry about whether the flag has _ever_ been enabled, only when it is "currently" enabled.
