### ISSUE TITLE
Import experiment results in validation error

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#2073]
Verion 6.0 QA testing of Import Experiment

I imported a recent experiment (attached) and received a confusing and hard to read validation error. Was not able to import experiment (import button was disabled). 

<img width="207" alt="image" src="https://github.com/user-attachments/assets/0f33d0ae-918f-4972-b09e-88d519c7ba5b">

[Vanderbilt Metacognition Experiment 3 Course 2.json](https://github.com/user-attachments/files/17480792/Vanderbilt.Metacognition.Experiment.3.Course.2.json)

**Comment by amurphy-cl** [comment]
Use `"backendVersion"` to check for validation (which for this experiment is :"5.2.1") 
We can still show a warning validation message -- the existing validation message -- but not block import, at least for v5.x 

backendVersion should be dynamically created or updated upon export rather than created when the experiment is created.

**Comment by bcb37** [comment]
QA: The attached experiment can be imported on dev (6.1) with a reasonable warning message. Pass.
