### ISSUE TITLE
api/v5/assign - no longer returning experiment

### ISSUE THREAD

**Issue by kawcl** [CarnegieLearningWeb/UpGrade#2078]
**Describe the bug**
`api/v5/assign` stopped returning the attached experiment while `api/v5/mark` still correctly returns the experiment id and condition.  It had been working for approximately the past 2 months prior to Wed, Oct 23rd.

**Note**
I created two separate experiments with different weights to the conditions and both are currently returning with the assign call.  One with 50/50 weighting between control/feature and another that put 100/0 weighting feature/control (specifically putting the feature condition first).

[LiveLab Test.json](https://github.com/user-attachments/files/17526087/LiveLab.Test.json)

**Comment by ppratikcr7** [comment]
@kawcl Can you please elaborate the issue you found. I tried and I am getting the assigned experiment data in `v5/assign` api for your experiment in dev branch.
<img width="631" alt="Screenshot 2024-10-28 at 3 29 58 PM" src="https://github.com/user-attachments/assets/6ea6c522-476a-47fd-8329-993ead24f50c">

**Comment by kawcl** [comment]
The second experiment with `target: at-risk` has also stopped returning as of this afternoon.

**Comment by kawcl** [comment]
Was able to reproduce the issue again with the 3rd experiment.  None of them are returning through `assign` anymore.

I'm working in an ngrx application and with how data flows in the app the `mark` call might be getting called before any of the data is returned from `assign`.  Not sure what issue is happening to cause it to stop the experiment from returning from `assign` though.

This is the request body of the offending mark call.
```
{"userId":"454b65b7-7140-4d02-9c84-da13992205b1","status":"condition not applied","data":{"target":"risk-icon","site":"notifications","experimentType":"Simple","assignedCondition":{"id":"d4da2eb5-fba7-4abd-911a-7a4ac2926aab","conditionCode":null,"payload":{"type":"string","value":"control"},"experimentId":"302a5756-6818-4574-bac6-ac6d2695de45"}},"uniquifier":"Error: No experiment found for site: notifications - target: risk-icon"}
```

**Comment by kawcl** [comment]
@ppratikcr7 maybe the issue is correlated to the specific userId?  Can you try with the userId that's in the request body I posted above?

**Comment by kawcl** [comment]
I was able to confirm that the mark call requestBody posted above will exclude the user from the experiment.  So probably not a bug but an issue with how the async behavior of my implementation is calling mark with the wrong or insufficient data.

**Comment by ppratikcr7** [comment]
@kawcl Yeah that might be the case.
