### ISSUE TITLE
Produce audit log of of experiment design export

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#208]
When an UpGrade user requests an email link to the data or to the experiment design, we should add this to the log. This way we can track that the emails were actually sent in case they aren't received.

**Comment by ppratikcr7** [comment]
@amurphy-cl Are you talking about the Audit logs as seen below? If yes, then we already do show email related log. We still need to add `Exporting Design` log in this.
<img width="967" alt="Screenshot 2021-12-07 at 9 46 01 PM" src="https://user-images.githubusercontent.com/33730817/145066137-d1de90d5-246e-4ab2-8e2b-1ea28453b34a.png">

**Comment by amurphy-cl** [comment]
@ppratikcr7 yeah, now that we separated the design download from the data download, we'll need to add `exporting design`. I'll change the issue title to be more clear!

**Comment by ppratikcr7** [comment]
@amurphy-cl Okay. Yeah that would be great.

**Comment by SritterCL** [comment]
It's a small thing, but I think we should include the email for the data export (just in case that's somehow misconfigured).

**Comment by ppratikcr7** [comment]
@SritterCL I didn't get you. Do you mean to look for the email not sent bug? If yes, then its already being tracked in #190. I have already verified the latest code works fine for our AWS environment variables and mail is received instantly. I am in discussion with @zackcl to confirm the AWS environment variables being used in the QA by CL's AWS backend deployment. Will get this sorted soon.

**Comment by ppratikcr7** [comment]
We are also planning to add a log for `email for data export requested`.

**Comment by SritterCL** [comment]
No, I just meant to include the email address that the data was sent to in the log message.
