### ISSUE TITLE
Removing an UpGrade user

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#21]
I noticed in the UI that while there is an option to Add User (with associated roles), we don't have a way to Remove User. A couple of the users in the CL instance of UpGrade are no longer with the company, so we'll want to have the ability to remove them from the list.

**Comment by msandbothe** [comment]
@YashilDepani What needs CL review on this? Do we need to better spec out the requested enhancement?

**Comment by YashilDepani** [comment]
@msandbothe, I have made a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/91) regarding this issue. In this, I have added the delete option for removing an UpGrade user. On clicking the delete-icon it prompts the dialogue box asking for confirmation. Type "delete" to confirm the delete.
![image](https://user-images.githubusercontent.com/51193749/124454293-f3873980-dda5-11eb-88ce-69528f5b63e5.png)
![image](https://user-images.githubusercontent.com/51193749/124454311-faae4780-dda5-11eb-8e77-bee286f340bd.png)

**Comment by nirmalpatel** [comment]
Closing this and and more discussion will be in the #93
