### ISSUE TITLE
create experiment: logging boolean bad request

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#2101]
**Version where bug was found:**
6

Creating a new experiment in staging gives this after the bugfix that removed the logging checkbox:

{
    "httpCode": 400,
    "name": "BadRequestError",
    "message": "Invalid body, check 'errors' property for more info.",
    "errors": [
        {
            "property": "logging",
            "children": [],
            "constraints": {
                "isBoolean": "logging must be a boolean value",
                "isNotEmpty": "logging should not be empty"
            }
        }
    ]
}

**Comment by zackcl** [comment]
@ppratikcr7 Please check my direct message on Slack.
