### ISSUE TITLE
Mathia: Exception 

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#2106]
**Version where bug was found:**
5.2

**Describe the bug**
Since Oct 16, this error has been popping up routinely.

```
2024-11-11T18:54:44.989Z lvl=ERROR thr=jersey-client-async-executor-0 sid=zep1phmv_qxtxk-b4wwkxhshslg:1731351281255 log=c.s.c.s.b.SectionVariantExperimentServiceImpl exception processing experiment response for ctcontextid=mx-43ffa566-7f5b-4213-8f00-cbb31f2a71a7-7ef8fa1f-b3e9-4d06-be8c-4c1a366ebc20 in sectionid=understanding_the_slopes_of_lines
```

https://carnegielearning.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22ctp_tomcat%22%20SectionVariantExperimentServiceImpl%20exception&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-1mon%40mon&latest=now&sid=1731351368.208255

This corresponds to logs in upgrade that look like:

```
{
    "client_session_id": "g9dx3qot_rgvav9uqs92hn8tga4:1731348996688",
    "endpoint": "/v5/mark",
    "level": "error",
    "message": {
        "type": "Error reported from client"
    },
    "request_id": "2a6d909a-8869-4680-bd21-ec29b9e70908",
    "request_method_type": "POST",
    "userDoc": {
        "createdAt": "2024-10-07T16:30:44.389Z",
        "group": {
            "classId": [
                "cl_4a114502-a85a-4d4f-8da7-d42f5596a062"
            ],
            "instructorId": [
                "6fb61a31-6345-4160-ae21-c8e4d99f5a20"
            ],
            "schoolId": [
                "10112779xfx6o"
            ]
        },
        "id": "5b801e3c-a6ed-4b97-8073-7a9fc491d472",
        "requestedUserId": "mx-5b801e3c-a6ed-4b97-8073-7a9fc491d472-reasoning_algebraically_fl_g7_23",
        "updatedAt": "2024-11-11T18:17:02.151Z",
        "versionNumber": 3,
        "workingGroup": {
            "classId": "cl_4a114502-a85a-4d4f-8da7-d42f5596a062",
            "instructorId": "6fb61a31-6345-4160-ae21-c8e4d99f5a20",
            "schoolId": "10112779xfx6o"
        }
    }
}
```

New Relic does not show any of this for some reason. 

I don't know steps to reproduce, this needs triaged.

**Comment by danoswaltCL** [comment]
[index="ctp_tomcat" SectionVariantExperimentServiceImpl sid=1r7dclc5me-upaev0twfzwir6l4:1731351550362](https://carnegielearning.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22ctp_tomcat%22%20SectionVariantExperimentServiceImpl%20sid%3D1r7dclc5me-upaev0twfzwir6l4%3A1731351550362&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-1mon%40mon&latest=now&sid=1731352093.208377)

I guess these are just timeouts, @jerith666 ?

**Comment by jerith666** [comment]
Yes, that's what it looks like to me.  The failure is logged before the timeout because the Mathia wrapper around the UpGrade client lib has its own timeout, independent of the one in the client lib.

**Comment by danoswaltCL** [comment]
ok, that checks out, closing
