### ISSUE TITLE
Remove the Enrollment Type Dropdown in the Experiment Data Tab

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#2115]
The "Type" dropdown in the "Enrollment" section under the "Data" tab on the Experiment details page is somewhat ambiguous regarding what it means when a group type (e.g., `classId`) is selected.

We should either make it clearer in the UI (e.g., rename the "Group Enrollments Across Sites" label) or remove the dropdown to avoid confusion.

This should be applied to the redesigned UI (it might not be needed for the old experiment design).

@VivekFitkariwala @ppratikcr7 If anyone from Playpower Labs recalls the meaning or usage of this dropdown, please leave a comment.

<img width="1000" alt="Screenshot 2024-11-16 at 1 35 03 AM" src="https://github.com/user-attachments/assets/1e59fc5f-8165-4634-97e4-330cc93a2645">

<img width="1000" alt="Screenshot 2024-11-16 at 1 36 23 AM" src="https://github.com/user-attachments/assets/fae3e0c0-9356-4d2f-b60d-e0697e18e09a">

**Comment by ppratikcr7** [comment]
So, when you select individual type, it will show you the complete enrollment count (i.e. I enrolled 3 students) as shown below:

<img width="1015" alt="Screenshot 2024-11-20 at 3 25 38 PM" src="https://github.com/user-attachments/assets/4dbe406c-731d-4cab-bb28-0b0f896515ff">


And when you select Group Type, it will show the graph for the number of groups that have enrolled students for group type: "add-group1" as below: (so I enrolled 2 students in `teacher1` group and 1 student in `teacher2`, so we see 2 enrolled groups in graph) 

<img width="1015" alt="Screenshot 2024-11-20 at 3 25 46 PM" src="https://github.com/user-attachments/assets/44d256b8-752e-44d4-863c-10e2348ad70d">


We should keep the dropdown and maybe rename it to "`Groups Enrolled"` for the dropdown and rename to `"Grouped Enrolled Across Sites"` for the label.

**Comment by zackcl** [comment]
Rename the label to "Groups Enrolled" or "Unique Groups Enrolled"

**Comment by zackcl** [comment]
What do you mean by "it will help us see different graphs as well"? Does the "Type" dropdown display different graphs? I think the dropdown just shows or hides the "Group Enrollments Across Sites"? (which we can always show if we remove the "Type" dropdown)

**Comment by ppratikcr7** [comment]
Yes, it shows different graphs as shown in my first comment.

**Comment by zackcl** [comment]
OK, we discussed that we still need the "Type" dropdown and for viewing the 2 different graphs. We might want to update the enrollment counts label but I think it can be created as a separate issue. I will close this one.
