### ISSUE TITLE
Suggestion on adding another way to post metrics using the Client Library

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#212]
Currently, this is an example of how we post metrics to UpGrade.

```
const upClient = new UpgradeClient(studentId, hostUrl);
const metrics = [{
    timestamp: new Date().toISOString(),
    metrics: {
        attributes: {
            durationSeconds: session.durationSeconds,
            percentCorrect: session.numCorrect / session.numAnswered * 100
        }
    }
}];

await upClient.log(metrics);
```

I think problems with this approach are that 1) it's difficult for developers to remember this data structure 2) and they might use incorrect property names by mistake and don't get any errors, 3) If we change any properties/data structure in the future, it will be difficult for them to update the code.

While we can still leave the `log()` function as it is, I would like to suggest another way to post metrics which is like the following:
```
const upClient = new UpgradeClient(studentId, hostUrl);
const attributes = {
    durationSeconds: session.durationSeconds,
    percentCorrect: session.numCorrect / session.numAnswered * 100
};
upClient.addMetrics(attributes);
await upClient.postMetrics(); // timestamp will be added internally in the postMetrics() function.
```
And if we also use the grouped metrics, it can be done like the following:

```
const upClient = new UpgradeClient(studentId, hostUrl);
const attributes = {
    durationSeconds: session.durationSeconds,
    percentCorrect: session.numCorrect / session.numAnswered * 100
};
upClient.addMetrics(attributes);
const groupClass = "masteryWorkspace";
const groupKey = "calculating_area_various_figures";
const groupAttributes = {
    timeSeconds: 246,
    hintCount: 25,
    errorCount: 48,
    problemsCompleted: 12
};
upClient.addGroupedMetrics(groupClass, groupKey, groupAttributes);
await upClient.postMetrics(); // timestamp and groupUniquifier will be added internally in the postMetrics() function.
```

We can implement this by adding something like `attributes = {}` and `groupedMetrics = []` member variables in the `UpgradeClient` class and add/push values to them whenever the `addMetrics()` or `addGroupedMetrics()` functions are called. And `postMetrics()` will internally structure the data using these variables and call the `log()` function, and then empty the variables.

Please let me know if my suggestion makes sense, and/or if you have a better one.

You can check out [this document](https://docs.google.com/document/d/1U6Mw0KB82EDpd9W99Kl5Rud1PMMatu0XJcmIBiguAL0/edit?usp=sharing) to learn about the metrics data structure we use.

**Comment by jerith666** [comment]
Doesn't TypeScript give you compile-time errors that help with all three of the issues you mentioned?

**Comment by zackcl** [comment]
@jerith666 I'm using the UpGrade client library in JavaScript, and it seems the `log()` function only checks `metrics` and `attributes` properties. For example, the following code worked without an error although `timestamp` and `groupMetrics` were incorrectly used. 

```
const metrics = [{
    timestamp2: new Date().toISOString(),
    metrics: {
        attributes: {
            durationSeconds: session.durationSeconds,
            percentCorrect: session.numCorrect / session.numAnswered * 100
        },
        groupedMetrics2: {
            groupClass: "masteryWorkspace",
            groupKey: "calculating_area_various_figures"
        }
    }
}];
await upClient.log(metrics); 
```
But changing `metrics` or `attributes` to something else produced a `500 (Internal Server Error)` when the `log()` function is called.

Anyways, even if TypeScript is able to detect mistakes in compile-time, some of our users might not use TypeScript and I don't think it solves the first issue that is "difficult for developers to remember/write the data structure".

When I first tried to post metrics, it took me a while to find out what the `metrics` argument should be like, but even after writing the above code, I had some questions like "why do we need to pass the `timestamp`?" and "why does it expect an array?" I later learned why they're needed so it makes sense to leave the API as it is, but I think the point of providing such a library is to hide the complexity and allow the user to write more simple and understandable code.

**Comment by jerith666** [comment]
You shouldn't be able to produce a 500 error by sending bad data to the server (even independent of the official client lib) -- the server should be robust to that and produce a `400 Bad Request` instead.  So I'd open a separate issue for that.

If `timestamp` and `groupMetrics` are indeed optional, it's okay if the server doesn't complain when they're missing.  But it probably should also throw a `400` when extra properties are present, to prevent these kinds of mistakes.

I think UpGrade's docs should strongly recommend that users use TypeScript, but you're right that we can't *force* that on our users.

Anyway, I don't object to making the API simpler in general!  Just want to make sure that we're taking as much advantage of type-checking as we possibly can.  :)

**Comment by mswartzCL** [comment]
@zackcl Do you think this is something we still need to do or shall we close it?

**Comment by zackcl** [comment]
Yes, I think we can close this for now but I might reopen this or suggest something similar in the future.
