### ISSUE TITLE
Metrics and repeated measures 

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#22]
Currently, when using the monitored metrics tool, you are forced to pick a repeated measures treatment when you select a metric to be monitored. If your desired metric is Average on the metric timeSeconds, and your repeated measures treatment is Mean, we should still see the requested Average of timeSeconds data from students when we run the monitor even if there are no repeat measures from any students.

Additional UI issue that will also be filed separately: we need to use the term Mean for both of these measures, not a mix of Average and Mean

**Comment by ppratikcr7** [comment]
@amurphy-cl We tried to test this on current latest main branch code.  We are getting Average/Mean time properly for a single user as well as shown below:

<img width="1393" alt="Screenshot 2022-01-04 at 1 38 35 PM" src="https://user-images.githubusercontent.com/33730817/148028827-5ea86cb3-d5c9-460a-852e-a33cc5e4e71a.png">
<img width="969" alt="Screenshot 2022-01-04 at 1 38 48 PM" src="https://user-images.githubusercontent.com/33730817/148028843-b6437c7c-5725-4510-bc58-1049eda2f67d.png">

**Comment by amurphy-cl** [comment]
Playpower could not reproduce, so closing this.
