### ISSUE TITLE
Deleting conditions in dashboard

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#24]
When going back to edit an experiment, the list of Conditions automatically rearranges the order of Conditions and also only allows removal of the last two Conditions. We should be able to remove any Condition

**Comment by amurphy-cl** [comment]
This is not quite fixed. We can delete the first and second conditions only when there are 3+ conditions. We still want to be able to delete conditions even when there's only 1 or 2 so there remains 1 or 0 conditions (but add the requirement that you need at least one condition).

I'll put the sorting bug in a new issue.

**Comment by ppratikcr7** [comment]
@amurphy-cl Yes. I have made the changes accordingly and it will show a validation message in case of less than one condition is present.
