### ISSUE TITLE
Throwing informative error when experiment the enrollment start fails

### ISSUE THREAD

**Issue by YashilDepani** [CarnegieLearningWeb/UpGrade#240]
Whenever we try to change the state of DDI experiment, we get 500 error for this API network . ```/api/experiments/state```

The issue is because of null users and without id. So this line in the code is throwing the error.
```
TypeError: Cannot read property 'id' of null
    at map (..../UpGrade/backend/packages/Upgrade/src/api/services/ExperimentService.ts:395:103)
```

**Comment by RidhamShah** [comment]
The main problem of the error is that there are about 72 users with UserID as null in `monitored_experiment_point`. We are working on filtering these users so they don't create any errors.
![image](https://user-images.githubusercontent.com/49234788/152128458-0221182f-0eaa-4b64-b6f0-fefc6bbd68d2.png)

**Comment by jerith666** [comment]
From slack, those rows are found with this SQL:

```
select * from monitored_experiment_point where "userId" is null
```

Is it expected that there will be such rows in that table, or is #241 a work-around for some other as-yet-unknown bug that permitted those rows to be added to the table in the first place?

**Comment by RidhamShah** [comment]
@jerith666 Ideally this error should not occur as we already have a ['code'](https://github.com/CarnegieLearningWeb/UpGrade/blob/be14ad142ea7d23d5a6d3657307d028a42ab6e9c/backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L102) snippet to check for the null users. 

We think the best solution is NOT TO MERGE this PR as this is a work-around and rather check for the corrupt data (data with null UserId) in the database and remove those data.

So what do think?

**Comment by jerith666** [comment]
Hm ... that check was added in 4b9e49c5e358f3f03109cbf62f1854bb82a3b40d, which is dated Mar. 2020.  Could the bad data have been in our DB for such a long time?

**Comment by amurphy-cl** [comment]
@RidhamShah if this is fixed (I think it might be), can we close this issue?

**Comment by VivekFitkariwala** [comment]
@amurphy-cl we are unable to recreate this issue as the code has proper checks to filter these users. So let's close this issue and we can reopen if we face it again.
