### ISSUE TITLE
Terminology change in the code

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#250]
Description TBD

**Comment by zackcl** [comment]
Terminology changes to be made so far:

1. `EXPERIMENT POINT` will be changed to `SITE`, `ID` to `TARGET`, and `Add Experiment Site` to `Add Decision Point`.
<img width="815" alt="Screen Shot 2022-02-04 at 4 32 11 PM" src="https://user-images.githubusercontent.com/90279765/152605944-2955b2e9-ac97-4656-a4f3-5aae5d98d502.png">

2. `ID` for the Grouped Metric will be changed to `Key`.
<img width="941" alt="Screen Shot 2022-02-04 at 4 37 09 PM" src="https://user-images.githubusercontent.com/90279765/152606489-2c73a916-49a8-4d9e-92e7-1099ba9c4bd9.png">

**Comment by ppratikcr7** [comment]
Handling this change in the above mentioned [ticket](https://github.com/CarnegieLearningWeb/UpGrade/issues/10) and closing this ticket.
