### ISSUE TITLE
Upgrade Docker base image to latest 12 version

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#260]
Current image in Dockerfile (`node:12.7.0-alpine`) is outdated https://hub.docker.com/_/node, and is likely cause of bugs seen in `api/query/analyse`, which fail because of outdated version of node on server (`Promise.allSettled` not available on 12.7, needs 12.9 and up).

Can we create an issue to update the docker image to `12-alpine3.14` or `12-alpine` in dev and get it into QA asap if all looks good there? (these will pull node 12.22^).

In near future upgrading to 14+ will be necessary also, as 12 will be no longer officially in next couple months. https://nodejs.org/en/about/releases/

**Comment by nirmalpatel** [comment]
Should we just try upgrading to 14+ now instead of later? @ppratikcr7 not sure how much work will be required to move to v14 or v16.

**Comment by ppratikcr7** [comment]
@nirmalpatel Not sure, will have to look into it. Let's discuss about this in our internal scrum meet.

**Comment by danoswaltCL** [comment]
closing this as 12.22.10 is being used now, separate issue should be created to move dev branch to node 16 image
