### ISSUE TITLE
Dev branch does not work without TYPEORM_HOST

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#270]
Linked to this issue, the new env for the dev branch https://upgrade.qa-cli.net/ is not able to connect to postgres when RDS_HOSTNAME is used instead of TYPEORM_HOST. https://carnegielearning.atlassian.net/browse/DEVOPS-975.

Triaging the issue, I found that reverting `typeormLoader.ts` to previous commit worked better to at least start up and reflect RDS_HOSTNAME as expected, so it seems that the logic for multiple read replicas is not working as expected to pass connection parameters.

This bug does block ability to test dev branch and promoting to staging.

@ppratikcr7 @nirmalpatel @VivekFitkariwala @amurphy-cl

**Comment by ppratikcr7** [comment]
@danoswaltCL I am looking into this.
