### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#28]
For each experiment, UpGrade should allow the user to enable verbose logging.

Under verbose logging, UpGrade logs any API calls (as "info" log messages). For example, when getAllExperimentConditions is called, each experiment that is in verbose mode should log something like:
INFO: getAllExperimentConditions: experiment: "experimentName", user: "userID", condition: "conditionCode", enrollmentCode: "code"

We should always use verbose logging in preview mode but also allow it to be turned on in other statuses.

**Comment by amurphy-cl** [comment]
@nirmalpatel can you explain what the new "logging" checkbox provides and whether all UpGrade user roles can use/see it?

**Comment by nirmalpatel** [comment]
@amurphy-cl when you turn on "logging" for an experiment, it will start logging /assign and /mark calls for that experiment into the backend's running terminal. This is to help with QA/debugging.
