### ISSUE TITLE
Bring backend coverage up to > 80%

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#281]

**Comment by jreddig** [comment]
Folders with low coverage

- [x] api/controllers 
in branch increase-code-coverage
- [x] api/errors
in branch increase-code-coverage
- [ ] api/middlewares
currently working on
- [ ] api/repositories
- [ ] api/repositories/utils
- [ ] api/services
- [ ] auth
- [ ] database/migrations
- [ ] lib/env
- [ ] lib/logger
- [x] add text files to coverage exclude list
in branch increase-code-coverage

**Comment by ppratikcr7** [comment]
@jreddig Are you working on further checklist for more test cases? Or should anyone from Playpower should be completing the rest checklists?

**Comment by jreddig** [comment]
@ppratikcr7 I haven't had the time to work on additional test cases since 3/1, so feel free to claim a group and write some unit tests. Hopefully will get back to this when production issues are resolved

**Comment by ppratikcr7** [comment]
Okay. Will let you know.

**Comment by ppratikcr7** [comment]
Okay, fine. I will take that up.
