### ISSUE TITLE
Log errors, warnings and info

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#29]
We should distinguish three different types of logging.

An Error means that UpGrade is unable to continue normally. For example, if an experiment requires assignment by group and no group has been set for the user, that's an error. The user gets the "default" condition.

A Warning means that UpGrade has detected a strange situation but can continue. If a user's working group is specified but the general group membership isn't, that reflects some kind of misconfiguration, but it's clear what UpGrade should do - assign the user according to the specified working group.

An Info message is used for debugging. It allows a user to trace what's going on UpGrade. For example, in verbose mode, we should log any API calls.

**Comment by amurphy-cl** [comment]
This is done.
