### ISSUE TITLE
Backend using Alias IDs instead of Root User IDs

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#301]
During regression testing we found a bug in the user doc in which instead of pointing the root user id, we are taking the alias user id. This change was introduced in logger format [commit](https://github.com/CarnegieLearningWeb/UpGrade/commit/12b23ded25d9ac8166765e0d40bd9290eec866f9) where we tried to have a single level fetching of userDoc and pass it though the logger instance.

This was not caught in test cases as its a controller level change and we currently don't have controller level integration test cases. We are planning to soon have test cases for controllers as well.

Note: We will have to clear the db.

**Comment by danoswaltCL** [comment]
Can we add a catch block to this function if it will still be used? There's a question of lambda calls timing out when `api/log` is being called and no logging to show any errors from Upgrade. I am wondering if as a symptom of the id issue is that this call is happening but the Promise either never resolves and breaks or the rejection is swallowed without any logging.

@jreddig @msandbothe do you think this could be a place where a failure would result in the behavior noticed in the lambda failures to `api/log`?

```
public async getUserDoc(experimentUserId, logger) {
    const experimentUserDoc = await this.experimentUserService.getOriginalUserDoc(experimentUserId, logger);
    if ( experimentUserDoc ) {
      var aliasUserId = experimentUserId;
        if (!experimentUserDoc.aliases) {
          aliasUserId = experimentUserId;
        }
        const userDoc = {
            id: aliasUserId,
            originalUserId: experimentUserDoc.id,
            group: experimentUserDoc.group,
            workingGroup: experimentUserDoc.workingGroup
        };
        return userDoc;
    } else {
      return null; 
    }
  }
```

**Comment by ppratikcr7** [comment]
@danoswaltCL I have added error handling and more error logs and also logs inside api/log call to give you more idea on this issue.
