### ISSUE TITLE
AWS latency / instance failures, always 'Severe' or 'Degraded' state with any decent volume

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#304]
Since deploying 10.0.88 on March 2 our EC2 instances on AWS have not been able to handle prod-level volume. Latest code is 10.0.94 with recent bugfixes in there and the issues remain.

With low volume, we are not seeing issues, but as the volume goes up:

1. Latency and errors track up
2. Healthy responses track down
3. Eventually, we appear to run out of disk space.

This happens despite scaling up of number of instances. In production we had 6 running at one point, and mostly were failing.

We are still trying to track down the root cause. We reverted staging back to 10.0.86, which was before recent production deployments, and while load tests up to 1000 concurrent users showed pretty high latency, the number of errors was low and it the health of the environment didn't go past 'warning' stage.

One spot that seems to be a potential clue is the size of the `/stouterr.log` directory (64.5GB currently), which has some pretty bizarre-looking logs that are too large to attach here. One example is a failed query that logs out a thousands of rows of data, and others that just look like thousands of rows of data that just looks like SQL prepared statement parameter references?: `$130521, $130522, $130523, $130524, $130525, $130526, $130527, $130528, $130529, $130530, $130531, $130532, $130533, $130534, $130535, $130536, $130537, $130538, $130539`.

In other places, such as the docker logs, we see it reporting that it cannot parse JSON due to unexpected EOF repeatedly until there is no more disk space to write to.

We are not seeing logs like this when reverting back to 10.0.86, so whether this is a symptom or a cause, there may be something strange going on with logging outputs.

**Comment by jreddig** [comment]
Elaborating on the query error, it's flooding splunk. The production splunk logs are full of pages of `[Truncated...]`. I'm assuming that they are shortened versions of a dump of what looks like aliases `"simplify_exponents_2_power_SelectSection_mx-4503e46b-4b3b-48f5-aa5b-c8cfddc64d02-696f34b1-9087-431f-aa8e-25d919fec238","simplify_exponents_2_power_SelectSection_mx-c38b5d8d-1016-483b-ae04-f70ad0d0e6bc-exploring_constant_change"`. 

Eventually these logs give a `"simplQueryFailedError: bind message supplies 29354 parameters, but prepared statement "" requires 160426`

**Comment by danoswaltCL** [comment]
Example of ^

[index="cl_upgrade" QueryFailedError](https://splunk.carnegielearning.com/en-US/app/search/search?q=search%20index%3D%22cl_upgrade%22%20QueryFailedError&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-30d%40d&latest=now&display.events.timelineEarliestTime=&display.events.timelineLatestTime=&sid=1646959812.136477)

**Comment by danoswaltCL** [comment]
Whatever is producing this query is consistently producing logs that are 

`query: SELECT "MonitoredExperimentPoint"."createdAt" AS "MonitoredExperimentPoint_createdAt", "MonitoredExperimentPoint"."updatedAt" AS "MonitoredExperimentPoint_updatedAt", "MonitoredExperimentPoint"."versionNumber" AS "MonitoredExperimentPoint_versionNumber", "MonitoredExperimentPoint"."id" AS "MonitoredExperimentPoint_id", "MonitoredExperimentPoint"."experimentId" AS "MonitoredExperimentPoint_experimentId", "MonitoredExperimentPoint"."enrollmentCode" AS "MonitoredExperimentPoint_enrollmentCode", "MonitoredExperimentPoint"."condition" AS "MonitoredExperimentPoint_condition", "MonitoredExperimentPoint"."userId" AS "MonitoredExperimentPoint_userId", "MonitoredExperimentPoint__user"."createdAt" AS "MonitoredExperimentPoint__user_createdAt", "MonitoredExperimentPoint__user"."updatedAt" AS "MonitoredExperimentPoint__user_updatedAt", "MonitoredExperimentPoint__user"."versionNumber" AS "MonitoredExperimentPoint__user_versionNumber", "MonitoredExperimentPoint__user"."id" AS "MonitoredExperimentPoint__user_id", "MonitoredExperimentPoint__user"."group" AS "MonitoredExperimentPoint__user_group", "MonitoredExperimentPoint__user"."workingGroup" AS "MonitoredExperimentPoint__user_workingGroup", "MonitoredExperimentPoint__user"."originalUserId" AS "MonitoredExperimentPoint__user_originalUserId" FROM "monitored_experiment_point" "MonitoredExperimentPoint" LEFT JOIN "experiment_user" "MonitoredExperimentPoint__user" ON "MonitoredExperimentPoint__user"."id"="MonitoredExperimentPoint"."userId" WHERE "MonitoredExperimentPoint"."id" IN ($1` ....followed by many (sometime 100k+) placeholder tags ($2, $3...), followed by potentially 100k parameters that looks like this, there are so many in this example I can't tell if the query is a success or an error, as it gets truncated... `) -- PARAMETERS: ["simplify_exponents_2_power_SelectSection_7c1290ef-4ea5-402e-96bf-8abdc500113a","simplify_exponents_2_power_SelectSection_1ef1ec03-7036-4281-abf0-e1400edd280d","simplify_exponents_2_power_SelectSection_b6bb856b-a074-4e43-8e98-a70452c7186e","simplify_exponents_2_power_SelectSection_a95cd64a-77ef-4741-851f-0ae4b257fdbf","simplify_exponents_2_power_SelectSection_d2bd04f7-b425-4278-b063-3826feea5e60","simplify_exponents_2_power_SelectSection_6593c0cd-f493-4e35-9010-d911c56461e9","simplify_exponents_2_power_SelectSection_9ff07f13-f3a5-43b0-9a48-ce97ac0829e4","simplify_exponents_2_power_SelectSection_e0aad272-6df7-4d5e-859d-d27dbd8f2446","simplify_exponents_2_power_SelectSection_598f7a6f-3f7f-4cae-8766-9972f451ad38","simplify_exponents_2_power_SelectSection_d3f881f6-3ed3-4252-8373-76cdd76943c8","simplify_exponents_2_power_SelectSection_b1d9c91a-e7eb-4192-bd85-70827fd4b457","simplify_exponents_2_power_SelectSection_1cfdb689-9be6-4497-b523-54660e04358e","simplify_exponents_2_power_SelectSection_e1bd79dd-b5dc-4cbb-a68b-cb28b00c12c8","simplify_exponents_2_power_SelectSection_750ccf0b-fd65-4bfb-80cd-ff16708520e2","simplify_exponents_2_power_SelectSection_63a61ad8-7424-4b79-80e1-a51dd7cddf85","simplify_exponents_2_power_SelectSection_8294793d-124d-4f5f-accf-80391567d1fe","simplify_exponents_2_power_SelectSection_fa31ea09-2ebb-4955-99a0-b0884dceb313","simplify_exponents_2_power_SelectSection_ae57c4a7-b6a4-46f1-8620-731e41409a03","simplify_exponents_2_power_SelectSection_51dab52b-f689-40b8-b93e-a2af5c7e9048","simplify_exponents_2_power_SelectSection_470bdf26-1035-415c-881b-67ba41705403","simplify_exponents_2_power_SelectSection_5a0b8e3b-9ac5-47f4-94f9-7a9bd332f6da","simplify_exponents_2_power_SelectSection_2b9512f6-0884-43f0-9ee7-0c108cdee3d7","simplify_exponents_2_power_SelectSection_f0f5eb36-54d2-4208-b660-aa61470c2708","simplify_exponents_2_power_SelectSection_a6d97e1c-5123-4b9e-b6fe-936d0392fd96","simplify_exponents_2_power_SelectSection_9a2a8ac7-da87-48d5-8cb6-38e1199d0321","simplify_exponents_2_power_SelectSection_c05953cd-627a-4f56-827b-acf73a08ec43",` ... imagine this goes on for a long time

**Comment by danoswaltCL** [comment]
If one pulls a recent prod database snapshot where this state already exists, one can run local docker and observe the following when hitting `api/mark` with an initialized user.

The issues noted look like they are occurring in `checkEnrollmentEndingCriteriaForCount()` of `ExperimentAssignmentService`.

At a certain point when enrolling students for a while, this query begins to get overwhelmingly large and slow:

```
const individualAssignments = await this.individualAssignmentRepository.find({
        where: { experiment: experimentDoc },
        relations: ['user'],
});
```

in fact the slowness is reported by in the logs:

```
query is slow: SELECT "IndividualAssignment"."createdAt" AS "IndividualAssignment_createdAt", "IndividualAssignment"."updatedAt" AS "IndividualAssignment_updatedAt", "IndividualAssignment"."versionNumber" AS "IndividualAssignment_versionNumber", "IndividualAssignment"."id" AS "IndividualAssignment_id", "IndividualAssignment"."assignmentType" AS "IndividualAssignment_assignmentType", "IndividualAssignment"."experimentId" AS "IndividualAssignment_experimentId", "IndividualAssignment"."userId" AS "IndividualAssignment_userId", "IndividualAssignment"."conditionId" AS "IndividualAssignment_conditionId", "IndividualAssignment__user"."createdAt" AS "IndividualAssignment__user_createdAt", "IndividualAssignment__user"."updatedAt" AS "IndividualAssignment__user_updatedAt", "IndividualAssignment__user"."versionNumber" AS "IndividualAssignment__user_versionNumber", "IndividualAssignment__user"."id" AS "IndividualAssignment__user_id", "IndividualAssignment__user"."group" AS "IndividualAssignment__user_group", "IndividualAssignment__user"."workingGroup" AS "IndividualAssignment__user_workingGroup", "IndividualAssignment__user"."originalUserId" AS "IndividualAssignment__user_originalUserId" FROM "individual_assignment" "IndividualAssignment" LEFT JOIN "experiment_user" "IndividualAssignment__user" ON "IndividualAssignment__user"."id"="IndividualAssignment"."userId" WHERE "IndividualAssignment"."experimentId" = $1 -- PARAMETERS: ["28206923-f221-4892-a039-5bec55e70741"]

execution time: 5315
```

This is because the apparently `individualAssignments` array gets gigantic under some conditions, which correlates eventually to an exception being thrown here:

```
const monitoredDocuments = await this.monitoredExperimentPointRepository.findByIds(monitoredDocumentIds, {
        relations: ['user'],
});
```

```
message: 'bind message supplies 12959 parameters, but prepared statement "" requires 144031',
```

In the error here, there were 144031 items in both the `individualAssignments` as well as `monitoredDocumentIds`, but I don't know what the 12959 number comes from.

```
{

  http_request_id: '95b4bd0a-f26b-414d-83c4-e7fd4291decd',

  endpoint: '/api/mark',

  request_method_type: 'POST',

  client_session_id: null,

  userDoc: {

    createdAt: 2022-03-10T01:56:55.016Z,

    id: 'abc123',

    requestedUserId: 'abc123alias',

    group: {},

    workingGroup: {}

  },

  level: 'error',

  message: ExperimentError {

    name: 'QueryFailedError',

    message: 'bind message supplies 12959 parameters, but prepared statement "" requires 144031',

    endPoint: '/api/mark',

    errorCode: undefined,

    type: undefined

  },

  timestamp: '2022-03-13T19:30:16.350Z'

}

{

  http_request_id: '95b4bd0a-f26b-414d-83c4-e7fd4291decd',

  endpoint: '/api/mark',

  request_method_type: 'POST',

  client_session_id: null,

  userDoc: {

    createdAt: 2022-03-10T01:56:55.016Z,

    id: 'abc123',

    requestedUserId: 'abc123alias',

    group: {},

    workingGroup: {}

  },

  level: 'info',

  message: {

    remote_address: '::ffff:172.22.0.1',

    time: '2022-03-13T19:30:16.524Z',

    method: 'POST',

    url: '/api/mark',

    http_version: '1.1',

    status_code: '500',

    user_agent: 'vscode-restclient'

  },

  timestamp: '2022-03-13T19:30:16.524Z'

}

QueryFailedError: bind message supplies 12959 parameters, but prepared statement "" requires 144031

    at QueryFailedError.TypeORMError [as constructor] (/usr/src/app/backend/packages/Upgrade/src/error/TypeORMError.ts:7:9)

    at new QueryFailedError (/usr/src/app/backend/packages/Upgrade/src/error/QueryFailedError.ts:9:9)

    at PostgresQueryRunner.<anonymous> (/usr/src/app/backend/packages/Upgrade/src/driver/postgres/PostgresQueryRunner.ts:258:19)

    at step (/usr/src/app/backend/packages/Upgrade/node_modules/tslib/tslib.js:143:27)

    at Object.throw (/usr/src/app/backend/packages/Upgrade/node_modules/tslib/tslib.js:124:57)

    at rejected (/usr/src/app/backend/packages/Upgrade/node_modules/tslib/tslib.js:115:69)

    at processTicksAndRejections (internal/process/task_queues.js:85:5)
 
```

This query + error + the verbose logging of the large array are the reason for the instances slowing and filling up disk space, and it looks like it has something to do with some unexpected behavior in enrollments / monitored experiment data when enrollments are happening, but I'm not personally familiar enough with all that is going on in these services to say what is making this happen.
