### ISSUE TITLE
Send 404 instead of 500 for 'user not found' error types

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#309]
Send 404 instead of 500 for 'experiment user not found' error situations in ExperimentClientController (experiment user id not in the table), as it's not likely an indication of a server issue.

~~If this affects EC2 health status checks in a meaningful way, this could be higher priority fix, as these common errors shouldn't cause problems in environment.~~

EDIT: It appears that a 4xx will affect EC2 health checks in same way as 5xx with current configuration (default). While this can be changed to ignore 4xx, I'm not sure we're consistent enough in our error codes to do that. Still, 404 is preferred to 500.

**Comment by YashilDepani** [comment]
Not much progress on this task, as I am currently working on '**segments**' feature.
