### ISSUE TITLE
Metric data is slightly off in the UI

### ISSUE THREAD

**Issue by jreddig** [CarnegieLearningWeb/UpGrade#312]
The metric data in the UI for each experiment does not match the computation from Mathia database or the computed data from the exported csv. I confirmed the enrollment numbers between Mathia and Upgrade and they both have the same students enrolled in each experiment. The student level data also matches between the exported csv and Mathia DB, but the aggregated values displayed on the UI are slightly incorrect.

I think some extra data is getting pulled into the metric calculations because as soon as an experiment is created, metric data is available when no students are enrolled. I tried this with a new workspace that hasn't been tracked before and set the experiment to enrollment complete. The experiment has no students enrolled, yet there are metrics for control and variant groups.

**Comment by ppratikcr7** [comment]
@jreddig We tried to recreate the above issue with various cases but couldn't see this. Can you let us know if there are any enrolled user for this experiment in the db, using the below query:

`SELECT * FROM individual_assignment WHERE "experimentId" = '<your_Experiment_id_for_which_you_see_excess_metric_data>'`

**Comment by ppratikcr7** [comment]
@jreddig Should we close this issue?

**Comment by jreddig** [comment]
Yes, I believe this is good to close!
