### ISSUE TITLE
Managing import of duplicate experiments

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#314]
Right now if you try to import two experiments that are identical, the UI doesn't handle this well -- just spins and does nothing. Instead we should either return an error upon import, e.g. 

"ERROR: this experiment design has already been imported" 

or prepend COPY OF... in the experiment name of the duplicate.

**Comment by ppratikcr7** [comment]
Okay. Do we require duplicate experiments? I would say let's go with first option, to show the error.

**Comment by amurphy-cl** [comment]
Good question. Let's go with the first option.

**Comment by ppratikcr7** [comment]
Handled this by verifying existing partitions in existing [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/349)
<img width="780" alt="Screenshot 2022-05-16 at 1 26 17 PM" src="https://user-images.githubusercontent.com/33730817/168550130-92e171ba-7006-4081-9572-c15ce46e74f4.png">
