### ISSUE TITLE
Copyright and BSD license

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#32]
Do we want to include copyright and BSD 3-clause license info here and in the client libraries repo?

**Comment by nirmalpatel** [comment]
@amurphy-cl GitHub has a template library of licenses. If you go to the repo home page, then click Create New File like this:

![image](https://user-images.githubusercontent.com/830400/116802199-b3e66c00-ab2e-11eb-84ba-f5f8a9c80628.png)

Then name your file "LICENSE" and a new template button will appear on the top right of the editing pane:

![image](https://user-images.githubusercontent.com/830400/116802211-cb255980-ab2e-11eb-87ff-df842f9cc907.png)

You can then go there and navigate quickly through all types of license templates and pick the one that you want:

![image](https://user-images.githubusercontent.com/830400/116802220-db3d3900-ab2e-11eb-9d5c-155333a6b1c5.png)

**Comment by amurphy-cl** [comment]
PR #89
