### ISSUE TITLE
Manage Roles: Can't add First Name/Last Name

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#333]
In role management, admins can add a new user by email address and assign a role, but can't add or edit the First Name or Last Name of the user. We should be able to edit this.

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/65311369/160920745-87fc15b9-f18e-4167-90d1-a9e63b97759f.png">

**Comment by jreddig** [comment]
Verified this change in dev branch. Admins can edit the first and last name of a user
