### ISSUE TITLE
Creating Segments

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#335]
Creating Segments that contain userIds, GroupIds, and other Segments.
Needed a UI with all functionalities and working backend for the same. (UI for Include/exclude lists (participants stepper) (O))

**Comment by amurphy-cl** [comment]
@zackcl has UI for this.

**Comment by zackcl** [comment]
Here are the status details of the global exclusion and segment:

* Global Exclusion
  * Unused: When there is no defined experiment (editable, not delectable)
  * Used: When there is any experiment, even an inactive one (editable, not deletable)
* Segment
  * Unused: When the segment is used in any experiment (editable, delectable)
  * Used: When the segment is used in inactive (inactive/preview/scheduled) experiments (editable, not delectable)
  * Used (Locked): When the segment is used in one or more active (enrolling) experiments (not editable, not delectable)
  * Globally Excluded: When the segment is added as a Global Exclusion member  (not editable, not deletable)
