### ISSUE TITLE
Data export links from email are inconsistent

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#34]
When exporting json experiments from qa-cli. I noticed that an inactive experiment with no monitored data, the 2 entries (data json and metadata) link to reversed (metadata and data json respectively).

**Comment by JD2455** [comment]
@msandbothe 
I've created a PR #56  to fix sign urls for Experiment Json Data and Experiment Metadata in exporting experiment from dashboard.
