### ISSUE TITLE
Cannot update the conditions after creating an experiment

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#340]
I tried updating an experiment by clicking the "EDIT" button and adding or removing a condition. However, the experiment never gets updated with the changed conditions. And when I delete the experiment after this, UpGrade shows a bunch of errors related to the `api/experiments/single/id` API call.

**Comment by zackcl** [comment]
It happened when running UpGrade locally on macOS. I just tried it in the QA UpGrade and had the same issue. The error did not show up in the UI this time (popup error messages appeared when running locally) but still exists in the console. You can try creating an experiment and updating the conditions if you'd like to confirm it.

**Comment by ppratikcr7** [comment]
I am able to EDIT and update/add/delete conditions successfully on running dev branch locally on MacOS. This doesn't seems to be an issue. Can someone else verify as well if they are facing this issue?

**Comment by zackcl** [comment]
@ppratikcr7 Did you check the conditions are updated on the experiment details page?

**Comment by ppratikcr7** [comment]
Yes, they are getting updated, expect the Section `Enrollments by Conditions`, that needs a refresh or route change for once. I will look into this in next PR.

**Comment by zackcl** [comment]
I found out I needed to click the "Save" button in each step to update the change. I was only clicking the "Update" button in the last step. I think we can discuss this in the design meeting. I will close this issue since this is not a bug.
