### ISSUE TITLE
Simplify backend by storing enrollments instead of assignments.

### ISSUE THREAD

**Issue by VivekFitkariwala** [CarnegieLearningWeb/UpGrade#342]
### Problem:
At present we are storing the assignments for the experiment user and to get the enrollments we need to join the table of assignments and monitored experiment point. From the application perspective if we store enrollments instead of assignments we can simplify many queries. Another problem which we are facing is after the enrollment complete state if the user reaches the experiment site they are counted as enrolled because we already have an entry in assignment table.

### Changes in table
IndividualAssignmnet -> IndividualEnrollment
GroupAssignment -> GroupEnrollment
Instead of storing the enrollment per experiment we will be storing it per experiment site so that the new design can be used for factorial experiment also.

### Changes in service
1. Now getAllExperimentCondition will not add any entry in the database (IndividualEnrollment or GroupEnrollment). It will return the assignments using the case code as we have now but for new assignment it will use random seed.
**Individual Experiment** -> RandomSeed will be experimentId_userId
**Group Experiment** -> RandomSeed will be experimentId_workingGroupId (based on type group experiment is defined on).
2. monitorExperimentPoint will add the entry inside the Individual Enrollment table and Group Enrollment table in addition to what it is doing at present. Also if the experiment is not in enrolling state it will not add any entry in the enrollment tables.
3. Update queries in the codebase accordingly.

**Comment by danoswaltCL** [comment]
This feels like a pretty major tech debt initiative, but I would hope to see it prioritized above new features, it would make a huge difference.
