### ISSUE TITLE
Enrollment Code not being marked correctly in some cases

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#345]
This may be a result of the new include / exclude functionality, but not sure:

1. It is often coming as `null`, I'm not sure of how to reproduce but it's happening quite a bit.

2. While working with `excludeAll` experiment filtermode and explicit group include, `/assign` calls for individuals who are in excluded groups are working correctly, but the `/mark` call is setting `enrollmentCode` in monitored_experiment_point to "Student was included".

The logic in https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L124-L206 seems to be missing references to explicit include / exclude tables, and to my quick reading of the nested if/else statements, several places that there is no `else` condition to catch unmatched conditions, which could easily be producing `null` values.

**Comment by amurphy-cl** [comment]
@VivekFitkariwala will this be addressed by the enrollment table? If so can you please close?

**Comment by VivekFitkariwala** [comment]
Yes this will be addressed by #27
