### ISSUE TITLE
Importing experiment design relies on the same experimentID 

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#347]
When you import an experiment design, the imported experiment uses the same `experimentId` as the original. This can create conflicts for QA testing as well as if we import multiple times and make small modifications to each imported design. The import design function should create a new `experimentId` at each import.

**Comment by ppratikcr7** [comment]
@amurphy-cl Okay, so when we import multiple times we are checking for duplicate experiment in terms of experiment id, if a same experimentId exists then we can create a new experiment with new experimentId. But for this to work the imported design should also have unique conditionId's and partition Id's. If this is fine then I would make changes to create the experiment with new expId when duplicate experiment (in terms if experiment id) is imported.

**Comment by ppratikcr7** [comment]
<img width="925" alt="Screenshot 2022-04-13 at 1 45 06 PM" src="https://user-images.githubusercontent.com/33730817/163131988-954ec742-a486-4d1b-bdc7-6bff16bcc782.png">

**Comment by ppratikcr7** [comment]
Okay, so everytime we import an experiment, all the UUID's should be changed, right?

**Comment by amurphy-cl** [comment]
Yes, that's right.
