### ISSUE TITLE
Condition auto-resorting

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#35]
When creating multiple conditions, the system auto-resorts them in an order that 1) is not the original order they were entered, and 2) cannot be changed. Conditions should be shown in the order they were added. In this example, I added in order A, B, C, D but when checking the dashboard or going to edit the experiment, it shows this. 

![image](https://user-images.githubusercontent.com/65311369/116593318-f4f03d80-a8ee-11eb-8a09-7e176512b8ae.png)

**Comment by msandbothe** [comment]
Unclear what is left to be done here. Should the PR have closed this?

**Comment by RidhamShah** [comment]
Yes, this issue is completed.
