### ISSUE TITLE
Frontend Enhancements for summer release

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#357]
We are covering the below changes in this ticket:

Equally weighted checkbox (O)
Remove number column from tables (O)
Place decision points above conditions (O)
Required checkbox UI for decision points (O)
Show weights with % rounded to 1 decimal place (e.g. 33.3%) (O)
Export experiment popup (one export button instead of two) (O)
Experiment stepper "update" (instead of "save") button when editing (O)
Within-stepper metrics definition (O)
Disable required checkbox for decision points
Remove old Monitor Metrics from Experiment Page
Stepper Dialog box uniform size
Stepper Overall Enhancement with Decision Point term changes
Upgrade Logo Centric with single version
Stepper Error Message Enhancements

**Comment by ppratikcr7** [comment]
**Done:**
Equally weighted checkbox (O)
Remove number column from tables (O)
Place decision points above conditions (O)
Required checkbox UI for decision points (O)
Show weights with % rounded to 1 decimal place (e.g. 33.3%) (O)
Export experiment popup (one export button instead of two) (O)
Experiment stepper "update" (instead of "save") button when editing (O)

**In Progress:**
Within-stepper metrics definition (O)

**Comment by amurphy-cl** [comment]
Are you guys using the kanban board for this ticket? Will you be creating a single PR for all of these?

**Comment by ppratikcr7** [comment]
No, we haven't separated this ticket, so not tracking in kanban. This is all under a single PR.
