### ISSUE TITLE
Create test scripts that define/clear experiments for automated testing

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#36]
Expand them to define a set of experiments. Ideally write these in python so they can be called from the Locust scripts.

In the short term, we're concerned with creating a standard environment for reproducing bugs, but this will lead into a maintainable unit testing process.

**Comment by nirmalpatel** [comment]
@ppratikcr7 Let us do the work in the new repo now. I transferred the issue.

**Comment by ppratikcr7** [comment]
@nirmalpatel Okay. Awaiting response from CL team for the above proposed changes.

**Comment by msandbothe** [comment]
Yes, raise the PR.
