### ISSUE TITLE
Patch code for XPRIZE and Demonstration phase

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#360]
We need to decide what to do with the current xprize patch code and how it should be maintained if we're advanced to the demonstration phase (probably starting in Sept 22). Do we need to create a more permanent solution to the issue of experiment point/id conflicts?

**Comment by danoswaltCL** [comment]
maybe i missed something on this in the meeting, what is the intent of this issue? If it's to merge in the patch code, that was already done by jenn. If it's to put in a more permanent solution, I was thinking that was not part of summer scope actually.

@amurphy-cl @SritterCL @jreddig

**Comment by amurphy-cl** [comment]
@danoswaltCL I think the decision to merge the patch code was made while I was out, so this issue can be closed. For tracking a more permanent solution to this problem, we can create a new issue.
