### ISSUE TITLE
Permanent solution to the issue of experiment point/id conflicts

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#370]
Create a Permanent solution to the issue of experiment point/id conflicts that is temporarily fixed by "X-Prize" patch Issue #360

**Comment by nirmalpatel** [comment]
@amurphy-cl @mswartzCL do we need to keep issue #360 (patch code) open? It is part of the Release 1 milestone.

**Comment by mswartzCL** [comment]
@nirmalpatel I will close. I thought #360 was only for merging the patch, but now I see it is for the permanent solution.

cc @amurphy-cl
