### ISSUE TITLE
Excluded users included in UI data

### ISSUE THREAD

**Issue by jreddig** [CarnegieLearningWeb/UpGrade#388]
**Describe the bug**
When enrolling and excluding students, excluded student data still counts toward enrollment counts and metric summaries.

**To Reproduce**
1. Initialize a student and assign conditions
2. Mark the experiment
3. Student appears in enrolled users
4. Send log data for the workspace
5. Student's metric data is now present in UI
6. Exclude student from the experiment
7. Enrollment numbers still include student
8. Student's metric data still present in UI

**Expected behavior**
Excluded student enrollments and metrics should not be counted.

**Screenshots**
Three students were enrolled, marked, and logged: Two with all metric data as 50 (control and variant), one with metric data as 10 (control). The student with metric data as 10 was explicitly excluded from the experiment and confirmed that the student does not receive conditions for this experiment anymore. If the student was excluded, the 10 metric data should not be present and both control and variant should have 50. The enrollment numbers still count 3 students with none excluded.

<img width="1017" alt="Screen Shot 2022-06-10 at 9 33 46 AM" src="https://user-images.githubusercontent.com/97543136/173077485-683e1f9b-af60-4d6f-999a-86f8ad0844bd.png">

**Additional context**
Excluded student with both experiment exclusion and global exclusion.

**Comment by amurphy-cl** [comment]
This will be part of a larger redesign of enrollment counts in the dashboard.
