### ISSUE TITLE
/assign provides wrong conditions

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#39]
@ppratikcr7 and I were debugging #7 and found discrepancies between what /assign provides and /mark expects.

result from /api/assign
[
   {
      "expId": "absolute_value_plot_equality",
      "expPoint": "SelectSection",
      "twoCharacterId": "N7",
      "assignedCondition": {
         "createdAt": "2021-04-07T18:12:25.844Z",
         "updatedAt": "2021-04-07T18:12:25.844Z",
         "versionNumber": 1,
         "id": "db2482dc-f7e9-43d1-9a81-3260df0659de",
         "twoCharacterId": "KQ",
         "name": "",
         "description": "Second Condition",
         "conditionCode": "variant",
         "assignmentWeight": 50
      }
   },
   {
      "expId": "simplify_exponents_2_power",
      "expPoint": "SelectSection",
      "twoCharacterId": "QX",
      "assignedCondition": {
         "conditionCode": "default"
      }
   },
   {
      "expId": "volume_surface_area_sphere_vol",
      "expPoint": "SelectSection",
      "twoCharacterId": "S2",
      "assignedCondition": {
         "conditionCode": "default"
      }
   },
   {
      "expId": "volume_surface_area_cone_vol",
      "expPoint": "SelectSection",
      "twoCharacterId": "RU",
      "assignedCondition": {
         "conditionCode": "default"
      }
   }
]

Plugging results into /mark

`curl -X 'POST' \
  '/api/mark' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $(< token.txt)" \
  -d '{"userId": "thisisnotarealuser", "experimentPoint": "SelectSection", "partitionId": "volume_surface_area_cone_vol", "condition": "default"}'`

Yields
{
   "name": "Error",
   "message": "Condition not found: default",
   "endPoint": "/api/mark",
   "errorCode": null,
   "type": "Condition not found",
   "createdAt": "2021-05-04T19:08:48.699Z",
   "updatedAt": "2021-05-04T19:08:48.699Z",
   "versionNumber": 1,
   "id": 252590
}

If I instead query with 'variant' condition

`curl -X 'POST' \
  '/api/mark' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $(< token.txt)" \
  -d '{"userId": "thisisnotarealuser", "experimentPoint": "SelectSection", "partitionId": "volume_surface_area_cone_vol", "condition": "variant"}'`

Instead yields 
{
   "createdAt": "2021-05-04T14:23:51.508Z",
   "updatedAt": "2021-05-04T14:23:51.508Z",
   "versionNumber": 1,
   "id": "volume_surface_area_cone_vol_SelectSection_thisisnotarealuser",
   "experimentId": "volume_surface_area_cone_vol_SelectSection",
   "enrollmentCode": "Student included in experiment",
   "userId": "thisisnotarealuser",
   "condition": null
}

The experiment this corresponds to, still has 0 students enrolled.

**Comment by msandbothe** [comment]
![Screen Shot 2021-05-04 at 12 00 45 PM](https://user-images.githubusercontent.com/6402566/117059293-a4615180-aced-11eb-9b9b-f591a62af37f.png)
![Screen Shot 2021-05-04 at 12 01 06 PM](https://user-images.githubusercontent.com/6402566/117059295-a4f9e800-aced-11eb-8ef4-49c017b94317.png)
![Screen Shot 2021-05-04 at 12 01 13 PM](https://user-images.githubusercontent.com/6402566/117059298-a4f9e800-aced-11eb-9471-164bb1be5b86.png)
![Screen Shot 2021-05-04 at 12 01 25 PM](https://user-images.githubusercontent.com/6402566/117059299-a4f9e800-aced-11eb-9fc7-64b9459de519.png)

**Comment by ppratikcr7** [comment]
Hi @msandbothe,

I figured out the issue, you are using wrong keys for the group and workingGroup, the experiment AA1-AA3 on which you are trying to call the api calls have group type as "class" or "school" and "teacher" and you are using "classId", "schoolId" and "instructorId" in place. This was giving conditionCode as "default" in the /assign call. Do try with the above change and you would get the desired enrolments without any error on /mark call as well.

**Comment by amurphy-cl** [comment]
Guys - are you not using the same script? It's not clear why Michael's keys would be different from Pratik's keys if you're using the same file to run these tests.

**Comment by ppratikcr7** [comment]
Mike is testing using curl commands to test. I guess the scripts should be same and run fine.

**Comment by msandbothe** [comment]
Verified that using the appropriate strings for group/working group corrects this.
