### ISSUE TITLE
The Need for Usability Testing

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#390]
@danoswaltCL and I discussed today that it would be nice to conduct usability testing to get feedback from our potential users and make necessary improvements sooner than later. We've been adding many new features to UpGrade lately and it would be helpful to test/learn how some of our potential users interact with UpGrade and what the overall experience would be like. 

It would also be helpful to get advice/feedback from some of our UX experts at Carnegie Learning regarding our design and testing methodologies.

Some questions to consider:
* When would be a good time to do this? (e.g. before/after the Summer release 1 or 2 or after having XYZ features)
* How can we find/invite our potential users? (e.g. random people or researchers)
* Do we want to use a Figma mockup or an actual UpGrade app for testing?
* How should we conduct the usability testing? (e.g. have the user follow written instructions while recording video)

**Comment by amurphy-cl** [comment]
This is something I've mentioned at meetings (involving Emily's team at CL or John/other members of CogSci to do some user testing of basic functions, like "set up an experiment").  We don't want random people involved. Previously we leaned on the Advisory Board for these types of questions, and while it doesn't exist anymore, we could possibly reach out to former members. Let's discuss in a design meeting what should be user-tested and why, and then reach out to Emily's team to see if they can help.

**Comment by amurphy-cl** [comment]
Closing this, to be revisited as specific tasks when needed.
