### ISSUE TITLE
Support for factorial/partial factorial experimental designs

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#393]
As part of the DLP deliverables, we need to implement factorial and partial factorial experimental designs. @zackcl has created design prototypes for the UI, tracked in #392

Related documents:
* [Factorial experiment documentation](https://docs.google.com/document/d/14MMMK3aTPI5T4MKCNaIxwOUzxtBP4cPK4I9O7-o7HCM/edit?usp=sharing)
* [Factorial experiment examples document](https://docs.google.com/document/d/1yeK-8mH39RIc7AV5ioY6dcwdGA8RbSWt5e0zLqwavXA/edit?usp=sharing)

Related Issues:
* [#392](https://github.com/CarnegieLearningWeb/UpGrade/issues/392#issuecomment-1466608087): UI design for factorial/partial factorial experiment support
* [#745](https://github.com/CarnegieLearningWeb/UpGrade/issues/745): Response to the api/assign request should be updated
* [#746](https://github.com/CarnegieLearningWeb/UpGrade/issues/746): Client library methods should be updated/added

**Comment by jreddig** [comment]
Ardent Angle is in production now!
