### ISSUE TITLE
Researcher needs to validate experiment design when editing an experiment so that they can ensure data is valid for the given client application.

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#403]
**User Story**
 - **Researcher needs to validate decision points, IDs, and conditions when _editing_ an experiment so that they can ensure data is valid for the given client application.**

**Acceptance Criteria**
 - Scenario: **Context Metadata does not exist for AppContext**
     - Given **AppContext is selected for experiment and context metadata does not exist for that AppContext and experiment in inactive state**, when **decision points, IDs, and conditions are _edited_**, then **any text can be entered and it will not be validated**.

 - Scenario: **Context Metadata validation is disabled globally**
     - Given **Context Metadata validation is disabled and experiment in inactive state**, when **decision points, IDs, and conditions are _edited_**, then **any text can be entered and it will not be validated**.

 - Scenario: **Context Metadata exists for AppContext**
     - Given **AppContext is selected for experiment and context metadata exists for that AppContext and experiment in inactive state**, when **decision points, IDs, and conditions are _edited_**, then **_valid options from context metadata can be selected_**.
     - Given **AppContext is selected for experiment and context metadata exists for that AppContext and experiment in inactive state**, when **decision points, IDs, and conditions are _edited_**, then **_any text can be entered and it will fail validation_**.

**Design**
[ - Link to design](https://www.figma.com/file/uYxnCT2dXTftSZKFQ00Q0y/UpGrade-UI-Prototype-(latest))
 
 **Context Metadata Model**
[Context Metadata Gist]( https://gist.github.com/danoswaltCL/2db2b62e09550a39f7cb02d725cf0290)

**Comment by mswartzCL** [comment]
@zackcl Can you please link your design work? Thanks!

**Comment by zackcl** [comment]
Here's a link to the latest Figma design: https://www.figma.com/file/uYxnCT2dXTftSZKFQ00Q0y/UpGrade-UI-Prototype-(latest)

**Comment by zackcl** [comment]
I don't think we need to validate the context metadata and provide feedback (e.g. showing error icons) when editing an experiment for the same reason I commented on https://github.com/CarnegieLearningWeb/UpGrade/issues/402#issuecomment-1189190080.
