### ISSUE TITLE
Enabling Edit button for Enrolling and Enrollment Complete State

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#405]
**Description:**
We need to keep the edit button enabled even when the experiment state is changed to Enrolling or Enrollment Complete State. We need to accordingly allow user to edit the participants, metrics, schedule and post-rule stepper tab details.

**Solution:**
We should allow users to edit the participants, metrics, schedule and post-rule stepper tab details. And disable the overview and design tabs. Also, while in schedule tab we should not allow the user to again set the enrolling schedule. They can still update the Ending criteria.

**Additional context**
We need to decide what details should be kept as editable while user changes experiment state to enrollment complete.

**Comment by jreddig** [comment]
When editing an experiment that has enrollment complete:
1. Click Next
2. Design step is skipped and you are directed to the Participants step
3. Click Back
4. Design step is accessed and empty

The design step should be disabled on "Back"

**Comment by ppratikcr7** [comment]
@jreddig When I tried recreating this, for me only the weights column was editable on design step as well as coming back to design step. This is due to the PR for enabling equal weights. I am working on it
