### ISSUE TITLE
Default Rows in Participants Step

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#411]
**Describe the bug**
No default placeholder rows displayed when user arrives at Participants step

**To Reproduce**
1. Create new experiment, or edit existing
2. Fill out first 2 steps

**Screenshots**
Expected:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/97542869/176284229-3eb1d75c-3f96-4cfe-a052-a8b7636c18d4.png">

Actual:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/97542869/176284123-09b2585e-1a28-4681-903a-fd8ddaa5688b.png">

**Comment by RidhamShah** [comment]
![image](https://user-images.githubusercontent.com/49234788/177086911-1d59472a-8979-4ed6-aad5-b2cde884dec9.png)

Default rows are now showing.

**Comment by jreddig** [comment]
There should also be a default row on the Except table per the design
<img width="958" alt="screen_shot_2022-07-06_at_2 59 43_pm" src="https://user-images.githubusercontent.com/97543136/177629959-a9b23f91-a5af-4441-960b-9d7946178cbc.png">

**Comment by ppratikcr7** [comment]
> I think it matters to the design that at least one row on the top is required, but it's fine to have no exceptions (so no rows on the bottom)

@jreddig As per steve's response, we have not kept a default row for "except" table. Should we still keep default row for "except" table

**Comment by zackcl** [comment]
@jreddig I think it's more natural to have the default row even if it's not required, and It's better for consistency. I think we can discuss this in the meeting.

**Comment by danoswaltCL** [comment]
@zackcl this design is ready to go right? I can pick this up and start in on it if so.

**Comment by danoswaltCL** [comment]
It has evolved enough I think we can close this and make a new issue, too much conversation to sift through to know what the finalized design state is.

**Comment by zackcl** [comment]
@danoswaltCL Sounds good!

**Comment by danoswaltCL** [comment]
oops, i realized @RidhamShah was assigned. Is this something that is currently be worked on Ridham? The design changed from the original request. I'm happy to take if you're not working on this one.

**Comment by RidhamShah** [comment]
Sorry for the late reply, somehow I miss this
@danoswaltCL you can take on this one. 
Also if it is completed, we can close this pr too
