### ISSUE TITLE
Update Experiment Overview Design to match Stepper Design

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#414]
**Describe the bug**
Stepper Design updated terminology and order of Decision Point/ Conditions, but same was not done for Experiment Overview page

**To Reproduce**
1. Create an experiment!
2. Click on it and view the overview!

**Expected behavior**

**Screenshots**
This:
![image](https://user-images.githubusercontent.com/97542869/176288516-45527e6b-7c82-40ee-9a12-9788f3fbc8b7.png)

...should look more like this:
![image](https://user-images.githubusercontent.com/97542869/176288464-d77b78e3-4e24-4e1d-8091-9027768b1ab7.png)

**Comment by jreddig** [comment]
Small update, the design has text in tables left aligned, except the weight column

**Comment by ppratikcr7** [comment]
@jreddig Did you mean the Design stepper page? There was some change in upcoming PR's. Will again set the weights to center.

**Comment by jreddig** [comment]
@ppratikcr7 oh, it looks like we're referencing different designs. In Zack's most recent designs, the weights are centered while the rest of the text is left aligned. 
<img width="747" alt="Screen Shot 2022-07-08 at 9 39 45 AM" src="https://user-images.githubusercontent.com/97543136/178003381-38d4e403-b185-4257-90ae-0504b40758a2.png">

**Comment by zackcl** [comment]
This is the latest  (tab-based) overview design. Yes, all should be left-aligned just like the stepper. I think the weight could also be left-aligned. (We'll need to discuss this in the design slack channel)

<img width="700" alt="Experiment Detail - Design (Inactive) 1" src="https://user-images.githubusercontent.com/90279765/178007789-3a523521-c3fc-4870-98f4-968181276d5b.png">

**Comment by danoswaltCL** [comment]
what I mean by left-aligned is that there isn't a gap on the left-hand side. in the stepper we have this:

**Comment by danoswaltCL** [comment]
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/97542869/178010591-d1cc22c5-8722-42cf-84f7-b5c8f0fa4e87.png">

<img width="989" alt="image" src="https://user-images.githubusercontent.com/97542869/178010846-222416eb-5252-4c4e-b7aa-e4d57c5d4f3a.png">

**Comment by zackcl** [comment]
@danoswaltCL Do you think the leftmost column should move further to the left side in the latest Figma design too?
<img width="750" alt="Experiment Detail - Design (Inactive) 4" src="https://user-images.githubusercontent.com/90279765/178049950-21c0f442-a593-4dd3-9ce3-85087aebfd17.png">

I think one reason I left some space there was to show an error icon and a message on its leftside.
<img width="750" alt="Experiment Detail - Design (mismatch Inactive) 7" src="https://user-images.githubusercontent.com/90279765/178050193-387e6684-5176-48ab-9946-1063d673df09.png">

**Comment by zackcl** [comment]
Here are the latest stepper and overview page design:
  * The weight column header should be `WEIGHT (%)`
  * The weight column values should be right-aligned 
  * There should be less gap on the left and right side of the table in the overview page
  * The target and weight columns should be aligned

<img width="500" alt="Experiments - Add Experiment-02-06" src="https://user-images.githubusercontent.com/90279765/178337954-08919556-19f5-46b0-b63f-396ede943005.png">

<img width="750" alt="Experiment Detail - Design (Inactive) 4" src="https://user-images.githubusercontent.com/90279765/178337269-062af4d1-0243-451d-bc9f-c8f41c8681c7.png">

**Comment by danoswaltCL** [comment]
@zackcl i think this issue is finished, can we close?

**Comment by zackcl** [comment]
Not really, because the texts aren't aligned properly and the column widths should be changed too. I will work on the details page UI enhancement soon after I finish working on the stepper UI so I will open up a new issue anyway, but I'd say let's leave it open for now because I might reference this issue.

**Comment by ppratikcr7** [comment]
@zackcl He has completed the tab view format for details page. 2-3 tabs are almost finished and working on the other tabs and populating data in "View Data" button.

**Comment by Yagnik56** [comment]
I have completed first 3 tabs Overview, Design and Participants. Working on loading a metrics data, I have created data view button but experiment data isn't loading in dialog box so for now I have created 5th tab as Enrolment to show it's graph and other data as temporary solution.  
![image](https://user-images.githubusercontent.com/50392803/192081199-591cc71b-31e6-4964-be83-19ae54524976.png)
![image](https://user-images.githubusercontent.com/50392803/192081210-417bfd2e-ec73-4a75-be11-81cfe77bf4f4.png)
![image](https://user-images.githubusercontent.com/50392803/192081214-f6c0516a-0155-4331-a89c-7eb22bb8c2ad.png)
![image](https://user-images.githubusercontent.com/50392803/192081231-b3781440-53fd-41e1-9ec2-4d1d1204740a.png)
Dialog box 
![image](https://user-images.githubusercontent.com/50392803/192081261-fdced7d7-39b7-4a01-b328-282ccd5597c3.png)

**Comment by amurphy-cl** [comment]
@zackcl can you please QA?
