### ISSUE TITLE
Stepper goes blank while trying to create an experiment

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#423]
**Describe the bug**
While trying to create an experiment using the stepper, it goes blank on the Metrics step. I can't proceed or even ESC out of the stepper, and my work is not saved. 

**To Reproduce**
1. Go to Add Experiment
2. Click through the stepper
3. Reach Metrics (Step 4)

**Expected behavior**
Stepper should not break while creating an experiment 🙂

**Screenshots**
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/65311369/176912125-970027be-ae41-4e36-aabc-90ecc0c4fe53.png">
This is what the broken stepper looks like

**Desktop (please complete the following information):**
MacOS Monterey with Chrome

**Comment by danoswaltCL** [comment]
@amurphy-cl  Can you provide any details of what was entered so far on the first 3 steps when it happened? Particularly the Design and Participant steps? I don't get it 100% of the time, for example, was just able to create https://upgrade.qa-cli.com/home/detail/4d75429a-cd48-4afa-a136-0997a94cb80e without that issue, so I suspect it may have to deal with the values entered.

**Comment by amurphy-cl** [comment]
@danoswaltCL sure
 Step 1: Unit of Assignment and Consistency are set to Individual
 Step 2: Target used was `introduction_to_a_quadratic_function`, conditions are `introduction_to_a_quadratic_function_meme_control` and `introduction_to_a_quadratic_function_meme_intervention`, weighted equally, descriptions "control" and "variant"
 Step 3: No participant data added

But I just tried this again and Metrics is there. Unclear why that step is unreliably disappearing

**Comment by danoswaltCL** [comment]
welp I was able to create experiment with exactly those details. https://upgrade.qa-cli.com/home/detail/f6dff4b6-e98e-4806-ac42-43b040f01108. it has definitely happened to me recently, there's a reason somewhere...
