### ISSUE TITLE
The metric field should be editable after a value is selected

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#424]
**Describe the bug**
The Metric field in the Defined Metrics table is currently not editable (and greyed out) once a value is selected from the dropdown. The field should always be editable just like how other fields (e.g. Site, Target) work.

**To Reproduce**
1. Go to the Experiment Stepper's Metrics step, click on the Metric field and select any value (e.g. totalTimeSeconds).
2. Try to change the value by clicking on the field again. You won't be able to edit it.

**Expected behavior**
The Metric field should always be editable just like how other fields (e.g. Site, Target) work. And it should not be greyed out and there shouldn't be a dotted underline below the value.

**Screenshots**
  * Current design:
<img width="500" alt="Screen Shot 2022-07-01 at 10 32 00 AM" src="https://user-images.githubusercontent.com/90279765/176914608-6df37d58-97bf-4244-bb9f-9a760e5d37e2.png">
  
  * Expected design:
<img width="500" alt="Experiments - Add Experiment-04-03 (1)" src="https://user-images.githubusercontent.com/90279765/176920477-955415e0-4378-4af0-aa19-8b25d3fea0b7.png">

**Comment by ppratikcr7** [comment]
@zackcl  It was similarly implemented earlier in separate monitored metrics page. The reason for this is that the next set of auto complete values depend upon the previously selected value. In case we keep all 3 visible together at once, it might create an issue when a user might click in the last dropdown, which would not load and also if they change the previous dropdown the next dropdown values might become invalid. This is the reason why we do lock or disable any selected Metric or Key and  the user has to delete the metric row in case they want to update the metrics.

**Comment by zackcl** [comment]
A video showing how metrics can be editable. The placeholder "Metric" showing in red color indicates that the user has deleted the previously typed metric name:
https://user-images.githubusercontent.com/90279765/179601533-85b28518-c4e2-456d-98a3-00cd538f940b.mov
