### ISSUE TITLE
When a masteryWorkspace metric value is selected, the Key, Metric, and Repeat Measure fields should appear at once

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#425]
**Describe the bug**
When a masteryWorkspace metric value is selected, the Key, Metric, and Repeat Measure fields should appear at once. Currently, only a Key field shows up and the placeholder is not correct (It should be Key instead of Metric).

**To Reproduce**
1. Go to the Experiment Stepper's Metrics step, click on the Metric field and select "masteryWorkspace". A Key field (with a Metric placeholder) will appear below.

**Expected behavior**
When a masteryWorkspace metric value is selected, the Key, Metric, and Repeat Measure fields should appear immediately at once just like the original design in Figma.

**Screenshots**
  * Current design (When a masteryWorkspace metric value is selected):
<img width="500" alt="Screen Shot 2022-07-01 at 11 23 52 AM" src="https://user-images.githubusercontent.com/90279765/176923653-a693dbd7-3d15-45c5-ae7b-b22f05d14d85.png">
  
  * Expected design (When a masteryWorkspace metric value is selected):
<img width="500" alt="Experiments - Add Experiment-04-08" src="https://user-images.githubusercontent.com/90279765/176923912-b22bc4cb-cd52-46d8-945e-87a50761fd68.png">

**Comment by ppratikcr7** [comment]
@zackcl Hey Zack, I will make the placeholder change in PR related to other release 1 bugs. We discussed about the main bug you have mentioned and we would say that it is meant to be visible one after the other as it was similarly implemented earlier in separate monitored metrics page. The reason for this is that the next set id auto complete values depend upon the previously selected value. In case we keep all 3 visible together at once, it might create an issue when a user might click in the last dropdown, which would not load and also if they change the previous dropdown the next dropdown values might become invalid. This is the same reason why we do lock or disable any selected Metric or Key and  the user has to delete the metric row in case they want to update the metrics. We would say, let's close this issue for now.

**Comment by jreddig** [comment]
Per the discussion on 7/7, we should display all the options and if a user reselects an option, the future selections should be cleared.
