### ISSUE TITLE
The defined metrics table's "Description" should be renamed to "Display Name"

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#426]
**Describe the feature**
We've discussed this in the meeting and we think the defined metrics table's "Description" should be renamed to "Display Name" because this field is required unlike other description fields and it will be used as a display name on the overview page (Data tab in the latest design).

**To Reproduce**
1. Go to the Experiment Stepper's Metrics step and find the "Description" label and the placeholder.

**Expected behavior**
The defined metrics table's "Description" label and the placeholder should be renamed to "Display Name".

**Screenshots**
  * Current design:
<img width="500" alt="Screen Shot 2022-07-01 at 11 39 34 AM" src="https://user-images.githubusercontent.com/90279765/176926493-e3f00fc2-2c46-46fc-911b-a9abac16c6f9.png">
  
  * Expected design:
<img width="500" alt="Experiments - Add Experiment-04-01" src="https://user-images.githubusercontent.com/90279765/176926667-453b5c57-2828-4b31-9cd0-a7804ae35827.png">

**Comment by zackcl** [comment]
I agree, should I close this for now then?

**Comment by danoswaltCL** [comment]
no it's just a feature request instead of a bug, can just relabel
