### ISSUE TITLE
The dropdown list for selecting a member type should be updated

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#429]
**Describe the feature**
This was mentioned earlier by @danoswaltCL here: https://github.com/CarnegieLearningWeb/UpGrade/pull/401#issuecomment-1163420527 and discussed in the meeting. We think the dropdown list for selecting a member type (used in both the segment and experiment stepper) should be updated. Currently, the grey label `group` is shown above the group types (e.g. Class, School) which should be removed, and the group types will be followed by parentheses containing "group" (e.g. Class (group)).

**Expected behavior**
The dropdown list for selecting a member type used in both the segment and experiment stepper should be updated.

**Screenshots**
  * Current Design:
<img width="500" alt="Screen Shot 2022-07-01 at 4 17 24 PM" src="https://user-images.githubusercontent.com/90279765/176963004-9b0c1035-bf43-4626-9dae-18d66c326f9d.png">
<img width="500" alt="Screen Shot 2022-07-01 at 4 13 14 PM" src="https://user-images.githubusercontent.com/90279765/176962608-601c661c-5b57-439c-89fa-2057d53ebde0.png">

  * Expected Design:
<img width="500" alt="Segments Pop-Up-07" src="https://user-images.githubusercontent.com/90279765/176962850-6dc76fce-92de-452d-97b2-ddc21ccff0d0.png">
 <img width="500" alt="Experiments - Add Experiment-03-04" src="https://user-images.githubusercontent.com/90279765/176962844-3adefe0f-c76d-49e9-beb0-0981de1ada74.png">

**Comment by jreddig** [comment]
This has been fixed.

![Image](https://user-images.githubusercontent.com/97543136/179530936-bd9d9369-dcd2-4c4f-9675-3592d98eeb70.png)
