### ISSUE TITLE
The number column for the tables in the Participants step should be removed

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#430]
**Describe the bug**
The number column for the tables in the Participants step should be removed for consistency in design. Also, there should be a default row in each table (separate issue: https://github.com/CarnegieLearningWeb/UpGrade/issues/411).

**Screenshots**
  * Current design:
<img width="500" alt="Screen Shot 2022-07-01 at 4 41 31 PM" src="https://user-images.githubusercontent.com/90279765/176965341-8f8e0edd-44d6-47f5-bb8b-353ea1e44fb6.png">
  
  * Expected design:
<img width="500" alt="Experiments - Add Experiment-03-01 (1)" src="https://user-images.githubusercontent.com/90279765/176965491-1292fb06-505e-4342-8068-b22e7c66f727.png">

**Comment by ppratikcr7** [comment]
This is already handled earlier in the merged [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/415).
Closing this.
