### ISSUE TITLE
New format of Simple Export

### ISSUE THREAD

**Issue by VivekFitkariwala** [CarnegieLearningWeb/UpGrade#449]
CSV export within the experiment should mail the csv with new format.

https://docs.google.com/spreadsheets/d/1dWwx53iuGrcQK9v6EWeVyCqQ9A5FMlTtmAe_j24vBIg/edit#gid=205486997

**Comment by mswartzCL** [comment]
Per discussion on 2022-08-04: 
- add human-readable and Excel/Google Sheets friendly timestamp

**Comment by VivekFitkariwala** [comment]
Added GMT time and local time

<img width="908" alt="Screenshot 2022-08-11 at 5 34 45 PM" src="https://user-images.githubusercontent.com/3822890/184129563-9bc4c72f-65b3-4880-925b-d47d5704968d.png">

User need to sign out and sign in to update database with their local time zone.

**Comment by mswartzCL** [comment]
This or similar. Reference standards. YYYY-MM-DD hh:mm:ss:

**Comment by VivekFitkariwala** [comment]
Update to ISO format
<img width="680" alt="Screenshot 2022-08-14 at 6 49 22 PM" src="https://user-images.githubusercontent.com/3822890/184538957-bec0136c-d639-4dd6-a348-bacf8e6d0bf1.png">
