### ISSUE TITLE
Backend >= 1.0.31 has high error rate and transaction times in CL prod environment

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#45]
I attempted to deploy 1.0.33 to prod over the weekend while traffic was minimal, but as soon as it finished deploying, new relic reported incidents because of long transaction times and high error rates. I also tried deploying 1.0.35 and 1.0.31, same issue, so it looks like whatever is causing this was introduced in 1.0.31. 

The transaction that was causing the issue is a POST to /api/mark. This operation typically executes in under 20ms, but during the incident it was at 52 seconds.

The error rate averaged about 30%, but I did not see any errors that aren't already occurring on 1.0.30, so I suspect that the issue lies with the POST I mentioned above.

But in case it happens to be relevant, the error during the incident was:
`Unknown Error: QueryFailedError: null value in column "type" violates not-null constraint`

Here is the breakdown from new relic for the /api/mark call. Looks like an issue in the code and not a database call

![image](https://user-images.githubusercontent.com/28930731/117667523-f33a3b80-b172-11eb-8369-dbdcf9ebd637.png)

Here's what the new relic graphs looked like. Transaction time and error rate both spiked immediately when I deployed the new backend version
![image](https://user-images.githubusercontent.com/28930731/117667815-50ce8800-b173-11eb-823b-753ea1cc5ba5.png)

**Comment by jerith666** [comment]
Here's what changed between 1.0.30 and 1.0.31:
https://github.com/CarnegieLearningWeb/UpGrade/compare/upgrade-backend-v1.0.30...upgrade-backend-v1.0.31

**Comment by SritterCL** [comment]
So where do we stand on this? @VivekFitkariwala - do you think the refactoring fixed this bug? Are you waiting for someone else to test this?

**Comment by mfugate1** [comment]
It is unlikely that Vivek's commit will fix this issue, but I will try deploying it to prod this weekend anyways just to make sure.

**Comment by SritterCL** [comment]
Can we reproduce this on QA first?

**Comment by mfugate1** [comment]
Until the locust script is updated, I'd have to set AUTH_CHECK=false for QA so it doesn't have to authenticate when calling experiment endpoints. If we're ok with having the API wide open I can make that change

**Comment by msandbothe** [comment]
I'm going to work on the locust script now to add an option that goes against existing experiments. It should be simple, so leave the AUTH_CHECK on in QA and we can hopefully test in QA tomorrow.

**Comment by VivekFitkariwala** [comment]
Added a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/54) for filtering experiments which are not assigned any condition.

**Comment by mfugate1** [comment]
Mentioned this on slack but realized I should add it here as well.

I merged that PR into main and deployed 1.0.39 into prod but still observed errors for `api/mark` calls

```
TypeError: Cannot destructure property 'experiment' of 'undefined' or 'null'.
    at ExperimentAssignmentService.<anonymous> (/usr/src/app/packages/Upgrade/dist/src/api/services/ExperimentAssignmentService.js:80:19)
    at Generator.next (<anonymous>)
    at fulfilled(/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)```

**Comment by nirmalpatel** [comment]
@mfugate1 can you see if this PR https://github.com/CarnegieLearningWeb/UpGrade/pull/57 fixes that issue?

**Comment by mfugate1** [comment]
Thanks @nirmalpatel, I will try this tonight when traffic on prod is low

**Comment by ppratikcr7** [comment]
Hi @mfugate1 @msandbothe, I tried recreating the issue in `api/log` call, but I am unable to get any error. I would need more details like on which scenario does that occur in the PROD environment. I am attaching my log.info for the parameters that would cause the issue you are getting. Please find the below logs for `api/log` call:

`info: [api:services/ExperimentAssignmentService] Add data log userId u22 and value [
  {
    "userId": "u22",
    "timestamp": "1970-01-01T00:00:00Z",
    "metrics": {
      "groupedMetrics": [
        {
          "groupClass": "masteryWorkspace",
          "groupKey": "calculating_area_of_square",
          "groupUniquifier": "1990-10-10T00:00:00Z",
          "attributes": {
            "hintCount": 31
          }
        }
      ]
    }
  }
]
info: [api:services/ExperimentUserService] Find original user for userId u22
info: [api:services/ExperimentAssignmentService] createLog: groupedMetrics: [
  {
    "groupClass": "masteryWorkspace",
    "groupKey": "calculating_area_of_square",
    "groupUniquifier": "1990-10-10T00:00:00Z",
    "attributes": {
      "hintCount": 31
    }
  }
], for User: u22
info: [api:services/ExperimentAssignmentService] createLog: metricKeys: masteryWorkspace@__@calculating_area_of_square@__@hintCount
info: [api:services/ExperimentAssignmentService] createLog: metricDocs: [
  {
    "createdAt": "2021-05-24T12:42:52.908Z",
    "updatedAt": "2021-05-24T12:42:52.908Z",
    "versionNumber": 1,
    "key": "masteryWorkspace@__@calculating_area_of_square@__@hintCount",
    "type": "continuous",
    "allowedData": null
  }
]
info: [api:services/ExperimentAssignmentService] createLog: metricDocs.length: 1
info: [api:services/ExperimentAssignmentService] createLog: filteredKeyUniqueArray: [
  {
    "key": "masteryWorkspace@__@calculating_area_of_square@__@hintCount",
    "uniquifier": "1990-10-10T00:00:00Z"
  }
]
info: [api:services/ExperimentAssignmentService] createLog: filtered metricKeys: masteryWorkspace@__@calculating_area_of_square@__@hintCount
info: [api:services/ExperimentAssignmentService] createLog: uniquifierKeys: 1990-10-10T00:00:00Z
info: [api:services/ExperimentAssignmentService] createLog: logGroup: [
  {
    "data": {
      "masteryWorkspace": {
        "calculating_area_of_square": {
          "hintCount": 31
        }
      }
    },
    "uniquifier": "1990-10-10T00:00:00Z",
    "timestamp": "1970-01-01T00:00:00.000Z",
    "id": 17,
    "key": "masteryWorkspace@__@calculating_area_of_square@__@hintCount"
  }
]
info: [api:services/ExperimentAssignmentService] createLog: logData: {
  "data": {
    "masteryWorkspace": {
      "calculating_area_of_square": {
        "hintCount": 31
      }
    }
  },
  "uniquifier": "1990-10-10T00:00:00Z",
  "timestamp": "1970-01-01T00:00:00.000Z",
  "id": 17,
  "key": "masteryWorkspace@__@calculating_area_of_square@__@hintCount"
}
info: [api:services/ExperimentAssignmentService] createLog: current logGroup index: 0
info: [api:services/ExperimentAssignmentService] createLog: logGroup.length: 1
info: [api:middlewares] POST /api/log 200 158.246 ms - 275`

**Comment by mfugate1** [comment]
No longer observing the issue with 1.0.41 in production, so I'm closing it.

I'm also not seeing that error with api/log. If it pops up again I will open a new issue.
