### ISSUE TITLE
DB access for QA testing of Enrollment and Segments for Summer Release 1

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#460]
Obtain DB access for QA testing of Enrollment and Segments for Summer Release 1

DB Testing is needed for:
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/335
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/27
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/342

**Comment by danoswaltCL** [comment]
https://carnegielearning.atlassian.net/browse/DEVOPS-1474
