### ISSUE TITLE
Excluded participants throwing error and unable to select 

### ISSUE THREAD

**Issue by jreddig** [CarnegieLearningWeb/UpGrade#463]
**Describe the bug**
When editing the participants of an experiment (on experiment creation or editing an existing experiment), the user cannot exclude participants. Clicking the drop down does not provide any options and the console has a `Error: NG0901`. The delete icon is not an icon but the text "delete icon".
<img width="966" alt="Screen Shot 2022-07-22 at 10 42 41 AM" src="https://user-images.githubusercontent.com/97543136/180465172-e89bfdb8-34fb-4eec-af68-7d3106783474.png">

Locally, the console error is `ERROR Error: Cannot find a differ supporting object 'Individual' of type 'string'. NgFor only supports binding to Iterables such as Arrays.`

**To Reproduce**
1. Go to the participants step
2. Select "Include Specific"
3. Add a member to the Excluded list

You can also click on the row to return the delete icon to a trashcan, but the dropdown is still unusable.
<img width="912" alt="Screen Shot 2022-07-22 at 10 51 05 AM" src="https://user-images.githubusercontent.com/97543136/180467224-efff5022-172a-4059-a7ad-c8b4b3076d51.png">

**Expected behavior**
The excluded participants section behaves like the included participants section

**Comment by danoswaltCL** [comment]
i think i see issue that caused this and will assign to myself

**Comment by jreddig** [comment]
Looks good in dev! This change is ready for staging.
