### ISSUE TITLE
Reselecting "Mastery" or "ConceptBuilder" in metric stepper causes broken behavior

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#474]
**Describe the bug**
Reselecting "Mastery" or "ConceptBuilder" in metric stepper causes broken behavior

**To Reproduce**
1. Go to Metrics step in new Experiment
2. Select `MasteryWorkspace` or `ConceptBuilder` metric type.
3. Click outside of form control focus.
4. Re-Select `MasteryWorkspace` or `ConceptBuilder` metric type.
5. See video for the weird behaviors, it adds ghost fields and dropdowns populate with unexpected values.

**Expected behavior**
It should ignore re-selection of same value, and toggling between the complex metric options should just reset the fields as it does when toggling between simple and complex metric options.

**Screenshots**

https://user-images.githubusercontent.com/97542869/181619905-1ab47b69-fb9b-4612-af98-b6a24e49f573.mov

**Comment by ppratikcr7** [comment]
Looking into this.
