### ISSUE TITLE
Have relative weights to eliminate decimal weights discrepancies

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#500]
**Is your feature request related to a problem? Please describe.**
When selecting equal weights checkbox, we get issues with rounding off and fixed single decimal view in frontend. Also, checking sum to be equal to 100 is another concern.

**Describe the solution you'd like**
We don't want any total calculation. So if user is entering manual values for weights, it can be any number and we won't do any validation as such. But if user selects equal weights checkbox then we will assign same number(10 as an example) but it can be any number.

**Comment by danoswaltCL** [comment]
I would think we do still need frontend 100 sum validation when `Weight Equally` is `false`. Users can be expected to enter numbers that will equal 100. If they want to enter multiple decimals for those weights that's their math problem to figure out. UI would send the `Weight Equally` boolean as well as exact numbers as it does currently.

In case of `Weight Equally` is `true`, then no validation for 100 sum, UI sends the `Weight Equally` boolean and the numbers are irrelevant, we wouldn't need to send anything at all. Unless we want some trivial number in there like 1 or 10 just to avoid revising that request object. But either way the backend can take care of assigning that weight.

**Comment by mswartzCL** [comment]
We could entirely move away from the "sum to 100" concept and go with the ratio even when `Weight Equally` is `false`. If the user thinks of it as 1, 1, 2, or 25, 25, 50, it will all be the same in the end. It also allows 1, 1, 1, or 33, 33, 33 without issue even when `Weight Equally` is `false`.

**Comment by amurphy-cl** [comment]
We no longer get a validation error unless the tenths place is edited manually to be **over 100**. Let's look into what is happening with the code, but otherwise we don't have a problem with the minimal amount of rounding.

**Comment by ppratikcr7** [comment]
@amurphy-cl So, we have new ticket to track that issue now. Can we close this ticket if we dont need relative weights?

**Comment by amurphy-cl** [comment]
Sounds good. Closing it out.
