### ISSUE TITLE
Decision Point Condition Alias UI

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#512]
**User Story**
Write an informal, general explanation of a feature written from the perspective of the end-user or customer. 
 - User **researcher** needs to **provide an alias for condition** so that **the alias can be passed to the client instead of the condition name**.

**Acceptance Criteria** (can be added later)
Provide the conditions that the product must satisfy to be accepted by the end-user, customer, or other stakeholders.
 - Scenario: **Experiment stepper**
     - Given **creating a new experiment or editing an existing experiment**, when **using the stepper Design step**, then **a new substep called "Aliases" should be available where the user can provide an alias for each decision point & condition, and the alias will default to the condition name**.

**Design Document**

**Comment by mswartzCL** [comment]
@zackcl @danoswaltCL Please update the issue with the relevant design and any other detail you want to capture. Thanks!

**Comment by ppratikcr7** [comment]
Updated Gist for backend changes: https://gist.github.com/ppratikcr7/b4c5c18154994a650d29cc952fa3804f

**Comment by danoswaltCL** [comment]
@zackcl is working on styling this up to match figma specs so we should leave open for now
