### ISSUE TITLE
Speedbump for clicking 'Close' research design modal

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#513]
**Is your feature request related to a problem? Please describe.**
Currently work in progress is not saved until clicking the final button (or 'Update' in edit mode). It's pretty easy to do a lot of work in the experiment design stepper modal accidentally click 'Close' and lose your work, especially with the close button being right next to the 'Next' button.

**Describe the solution you'd like**
Some kind of 'Are you sure' speedbump, whether that's a dialog that pops up, or some other thing that happens what clicking close to verify the action is intentional and a message saying you'll lose your work.

There's a valid question as to if it's awkward to have an 'are you sure' speedbump modal appear over the top of another modal... but that would be the simplest approach.

**Comment by jreddig** [comment]
Tested in staging. Marking as done!
