### ISSUE TITLE
GetAllExperimentConditions should never return "default"

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#52]
Currently, GetAllExperimentConditions returns "default" as the condition, in some circumstances. In others, the experiment is omitted from the return value (so the client provides the default condition).

The return value from GetAllExperimentConditions should only include experiments where the user has a condition - never "default."

**Comment by msandbothe** [comment]
Calling /mark with condition value "default" results in a 500 server error.

**Comment by VivekFitkariwala** [comment]
Added a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/54) for filtering experiments which are not assigned any condition.
