### ISSUE TITLE
UpGrade should not allow users to define a condition called "default"

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#53]
"Default" is a reserved word, so it shouldn't be allowed as a condition name (case-insensitive - so Default, DEFAULT, etc. are also forbidden).

The user should get an error message if they try.

**Comment by VivekFitkariwala** [comment]
I think this is not necessary as now we are not returning any unassigned experiment which means client will only get experiments which are assigned to a condition so if we define 'default' as a condition client application will get 'default' as the condition assigned and for the experiment in which user is excluded we will get null.

**Comment by nirmalpatel** [comment]
@VivekFitkariwala so do you mean to say that if we define an experiment with two conditions "default" and "variant" then only the student assigned the condition "variant" will get their assignment information? And everyone assigned "default" will simply not receive their assignment from the getAllExperiments() ?

**Comment by VivekFitkariwala** [comment]
No. "default" will be treated just as any other condition. So a user assigned to "default" condition will get "default" on the application end when called `getExperimentCondition`.
The users which are excluded from the experiment will receive `null` for that experimentId and experimentPoint. 
Server will not return any condition and on the client side when application calls `getExperimentCondition` it will get `null` in response.

**Comment by nirmalpatel** [comment]
But I thought "default" was a reserved keyword, and in case of some error some issue, the user would get assigned the "default" condition which is the original learning experience... so maybe we should never let UpGrade assign "default" but only fall back on "default" in case of some error...

But then we have revert to "default" which would explicitly return "default" to users?

**Comment by SritterCL** [comment]
I agree with Vivek's comment that this isn't strictly necessary, but I still think it's a good idea. "Default" is used at the user level (in "revert to default") and in things like documentation (when we talk about the user experience, it makes sense to say things like "students who are excluded from the experiment get the default condition").

So there's no technical reason to exclude default but it could prevent some confusion.

**Comment by ppratikcr7** [comment]
[PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/64) has been raised for this issue.
