### ISSUE TITLE
Potential performance issues w/ Segments, client API

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#542]
**Describe the bug**
Despite caching of segments, load-testing in latest code is showing latency for segments service calls when tested with the large exclusion lists that we need for upcoming experiments. The database seems to be executing queries quickly though, so we are looking into potential code logic in the API services related to `/assign` especially that doesn't scale with high inputs such as many rows of individual exclusions.

Please see https://carnegielearning.slack.com/archives/CTD5UG8R2/p1663091113707669 and the main thread for the details. Load-testing results files are at bottom of thread. Though we realized that the production code did not have the caching mechanism implemented for optimizing segments queries, load-testing in staging where caching is present is still showed a similar pattern with around 2.5 s latency despite queries executing in milliseconds.

This may cause issues with upcoming experiments that need large exclusion lists.

**Comment by danoswaltCL** [comment]
Follow up from mtg this morning (9/14):

First goal is to ensure we can launch MEME experiment, and it was felt that current production code without segments caching would not be ready for this, and latest was too untested to just push straight to prod right now, SO:

1) Today: We'll look into possibly cherry-picking the segments caching commit and test a 'hotfix' release. If load-testing looks positive we can push this to prod.

2) Later: Need to profile client service call classes to see if there are bottlenecks that can be worked out to further improve latency.

While load-testing was showing < 3s response times with the caching in place in latest code, it was felt that this is still a little too high for comfort, so in next couple weeks, once summer-release-2 major functionality is finished, Playpower can look into optimizations while CL works on QA'ing and readying production for MEME and XPrize experiments.

@amurphy-cl @mswartzCL @ppratikcr7 @jreddig @RidhamShah @zackcl @VivekFitkariwala @nirmalpatel please let me know if there is anything missing from this takeaway

**Comment by danoswaltCL** [comment]
I'm not sure this is an issue at this point, we can close this.

**Comment by amurphy-cl** [comment]
Closing this but noting that we're still having latency issues (but may be an AWS issue).
