### ISSUE TITLE
/mark unhandled error: "TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#575]
**Describe the bug**
Seeing this for markExperimentPoint sometimes in QA/Prod logs:

"TypeError: Cannot read property 'id' of undefined"

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/97542869/197228599-27dc3852-0f8b-47e6-9e94-98be862c9d6a.png">

**To Reproduce**
I'm not sure, it's easy to see exactly where and why the error happens codewise, but I'm not sure how to reproduce or what it means if this is unexpectedly undefined.

```typescript
if (experimentDecisionPoint.length) {
        let selectedExperimentDP = experimentDecisionPoint.filter( dp => dp.experiment.id === experimentId);
        const decisionPointId = selectedExperimentDP[0].id; //<---- oops, selectedExperimentDP can be undefined
```

**Expected behavior**
Handle the error w/o 500 internal error throw

**Screenshots**
<img width="695" alt="image" src="https://user-images.githubusercontent.com/97542869/197229948-a9ea168a-7e06-42ac-964e-b6169555f695.png">

**Comment by danoswaltCL** [comment]
I was able to reproduce this. This would be when marking without sending the `experimentId`, as is how it is currently used by Mathia.

A user who is technically eligible for at least 1 experiment loaded into upgrade in that environment that marks a valid decision point in an experiment that they are excluded from will get the above error.

The experiment they are eligible for can be in "Enrolling" or "Enrollment Complete" state.
The experiment they are excluded from can be in any state, even in "Inactive".

This allows them to follow a specific path through the code where they will hit this line of code:

```typescript

      if (!experimentId) { 
        if (filteredExperiments.length > 1) {
          const random = seedrandom(userId)();
          experimentId = filteredExperiments[Math.floor(random * experiments.length)].id;
        } else {
          experimentId = filteredExperiments[0] ? filteredExperiments[0].id : ''; // <--- filteredExperiments can be empty 
        }
      }
```

Which then fails on this line, because it can't find any experiment id that equals empty string. (Sidebar, how come typescript allows this?? The types are defined for these arrays just fine...)

```typescript
if (experimentDecisionPoint.length) {
        let selectedExperimentDP = experimentDecisionPoint.filter( dp => dp.experiment.id === experimentId);
        const decisionPointId = selectedExperimentDP[0].id; // <---- undefined, throws 500 error
```

in local, you can try this:

1. Create an experiment with include ALL and a single decision point (Experiment A)
2. Create another experiment with a different decision point, Include ALL except a user with id "Test" (Experiment B)
3. Start Experiment A enrolling.
4. Initialize "Test" user.
5. `/mark` user at the valid decision point in experiment B
6. You should see this error.

If you delete Experiment A, the error will not happen.

**Comment by danoswaltCL** [comment]
@ppratikcr7 is this something you can look into as a priority? It may be a simple fix, but it feels like it should get a deeper look to make sure things are getting handled correctly. We may need to have this patched into the current release.

**Comment by ppratikcr7** [comment]
@danoswaltCL Yes, looking into this.

**Comment by jreddig** [comment]
Seeing this in production again, both /mark and v1/mark apis are failing (rarely, but still failing) with Cannot read property 'id' of undefined. Haven't tried to reproduce locally yet, but wanted to call it out asap
