### ISSUE TITLE
Remove Experiment Consistency

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#576]
**Is your feature request related to a problem? Please describe.**
Properly working `exclude_if_reached` functionality makes experiment consistency obsolete now, it would be good to remove this option so it doesn't become a confusing artifact that we continue to maintain / test scenarios around.

Note: This is not also true of Individual / Group Consistency.... those options still come into play when `exclude_if_reached` is `true` for at least 1 decision point because when a user marks that decision point before enrollment, Individual / Group consistency will determine whether others in that user's `workingGroup` will also get excluded (if `Individual`, then only that individual will continue to get default, whereas if `Group`, everyone in that group will get default).

**Describe the solution you'd like**
First simply remove option from UI, but then we should to determine the work required to remove this enum and the logic tied to it in backend.

**Comment by zackcl** [comment]
Closing this issue as it has been fixed: https://github.com/CarnegieLearningWeb/UpGrade/pull/577

**Comment by jreddig** [comment]
Tested in staging. Option has been removed. Marking as done!
