### ISSUE TITLE
"Users with ids ... already associated with other users" error message should list existing and new users

### ISSUE THREAD

**Issue by jerith666** [CarnegieLearningWeb/UpGrade#58]
Summary pretty much says it all.  It's pretty hard to diagnose this error without knowing both:

1. what user IDs are those alt IDs already associated with?
2. what user IDs is the client asking that they be newly associated with?

**Comment by VivekFitkariwala** [comment]
Created a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/60) with additional error logs.
