### ISSUE TITLE
Workflow / tools updates

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#582]
Before we launch into lots of new heavy feature work, I would love a "sprint" or so of time to pump the brakes a minute and take care of some housekeeping, with the aim of preventing future marathon bug triage and delayed feature releases, but also, make dev workflow nicer and less error-prone by default.

We are a split team with no real hierarchy or dedicated QA professionals, we all code differently and have no real documentation on coding standards. We could spend a lot of time discussing and writing documentation on standards, enforcing it in code reviews, and writing even more tests... but we also have lots of tools that we could crank up to 11 to do 90% of that work for us before we even hit commit.

Below is a shortlist of quality-of-life improvements to dev workflow that I hope will help us catch careless or hard-to-spot bugs and also standardize our code style so that things are easy to read for anybody. That way this stuff doesn't need ever really come up in code reviews and we can focus on the important stuff.
             
- [ ]  Enable stricter Typescript configs (especially `noImplicitAny` and `strictNullChecks`)
           - Frontend
           - JS Client LIb #617
           - Backend
           - Types
- [ ]  Get SonarQube hooked up in Github Actions
           ✅  DEVOPS ticket created: https://carnegielearning.atlassian.net/browse/DEVOPS-2417
           - Implementation #604
- [x]  Bring Swagger up to full functionality and full documentation coverage of API request/response models.
           ✅  Specifically, the Client SDK section of the Swagger docs would be extremely useful to have complete information on data models and response expectations #602 
- [x]  Fully enforce Prettier in across the board and require it on commit (i.e. autocorrect formatting on commit).
           ✅  Frontend #590
           ✅  JS Client LIb #601
           ✅  Backend #603
           ✅   Types #609
- [x]  Migrate to ESLint in all packages (TSLint is deprecated, EsLint is the thing nowadays)
            ✅  Frontend #590
            ✅  JS Client LIb #601
            ✅  Backend #603 
            ✅  Types #609 
- [ ]  [insert your own! I'm sure there are other good ideas, maybe there's even better stuff out there]

For all of these, we should just use whatever the Carnegie Learning Engineering's standards are (whether they real or aspirational standards, I'm not sure these are all strongly documented).

**Comment by jerith666** [comment]
This sounds like a great idea to me.  I wouldn't limit prettier usage to just the frontend -- it's all typescript code, it should all be formatted the same.

**Comment by jerith666** [comment]
Also, SQ is licensed by lines of code, we can create as many users as we want.  And we're nowhere near our LOC limit at the moment.  Mike's got it hooked up to GitHub Enterprise, so there might be some extra work to hook it up to GitHub "central".  I would just open a DEVOPS ticket like "enable SonarQube for UpGrade" and hopefully Mike can get to it soon.
