### ISSUE TITLE
experimentId should be included in the assigned condition

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#586]
**Describe the issue**
The `experimentId` property should be included in a condition when creating an experiment. And the `assignedCondition` should contain the `experimentId` property when `api/assign` is requested.

**Comment by RidhamShah** [comment]
@zackcl Can you elaborate on this issue?

As the UUID of Conditions are unique to a particular experiment only so I don't think we need to give experimentId with the condition 
also, we are changing assign call responses to
```
{ 
  site,
  target,
  condition
}

```
So there will be no more `assignedCondition` details

**Comment by zackcl** [comment]
@RidhamShah I'm not 100% sure if the `experimentId` should be included in a condition when creating an experiment because UpGrade can internally know what experiment the condition belongs to.

But I believe decided to included the `experimentId` in the `assignedCondition` when `api/assign` is requested like the following example:

Response to `api/assign`:
```
[
    {
        "site": "geometry",
        "target": "colored_shape",
        "twoCharacterId": "GC",
        "assignedCondition": {
            "createdAt": "2022-10-26T15:57:24.779Z",
            "updatedAt": "2022-10-26T15:57:24.779Z",
            "experimentId": "xxxxx-24dc-427b-yyyy-zzzzzzzzz",
            "versionNumber": 1,
            "id": "223106b2-24dc-427b-9999-079c1dd0e1d3",
            "twoCharacterId": "CB"
            "name": "",
            "description": null,
            "condition": "Color=Blue; Shape=Triangle",
	      "alias": "Color=Blue; Shape=Triangle",
	      "factors": [
                {
                    "name": "Color",
                    "site": "geometry",
                    "target": "colored_shape",
                    "level": "Blue"
	          },
	          {
        	    "name": "Shape",
                    "site": "geometry",
                    "target": "colored_shape",
        	    "level": "Triangle"
	          }
	      ],
            "assignmentWeight": 16.7,
            "order": 1
       }
    }
]
```
I think this is because now we also require `experimentId` in the `api/mark` request?

**Comment by VivekFitkariwala** [comment]
In coordinated decision point if `experimentId` exist in `assignedCondition` of the post body then it should be used to mark the experiment instead of using the algorithm for finding experiment in coordinated decision point scenario.

**Comment by ppratikcr7** [comment]
@zackcl We checked again, and this issue is being handled in our current dev branch. We can close this.
