### ISSUE TITLE
api/mark should require assignedCondition structure instead of condition string

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#587]
**Describe the feature**
When requesting `api/mark`, the body should require the whole `assignedCondition` object/structure instead of a `condition` string.

Example:
```
{
   "experimentPoint": "add-point1",
   "partitionId": "add-id1",
   "userId": "u1",
   "assignedCondition": {
            "createdAt": "2022-10-26T15:57:24.779Z",
            "updatedAt": "2022-10-26T15:57:24.779Z",
            "experimentId": "xxxxx-24dc-427b-yyyy-zzzzzzzzz",
            "versionNumber": 1,
            "id": "223106b2-24dc-427b-9999-079c1dd0e1d3",
            "name": "",
            "description": null,
            "condition": "variant",
	    "alias": "numberline_variant"
            "assignmentWeight": 50,
            "order": 1
       }
}
```  
I'm not sure if some of the properties in `assignedCondition` can be optional (e.g. createdAt, updatedAt, description, order, etc)

**Comment by ppratikcr7** [comment]
@zackcl Is this issue completed now?

**Comment by zackcl** [comment]
@ppratikcr7 @VivekFitkariwala Can UpGrade know which experiment is being marked only with the condition string (which the `markExperimentPoint()` currently requires), when there is more than one experiment using the same decision point and conditions?

**Comment by jreddig** [comment]
Now that we've added the condition uniquifier, is this ticket still relevant? The `assignedCondition` also includes both the condition code and experiment ID

**Comment by ppratikcr7** [comment]
@zackcl Should we close this now?
