### ISSUE TITLE
The repeated categorical metric doesn't have an option to select what to count

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#591]
**Describe the bug**

If a categorical metric is selected in the Metrics step UI, there should be an option to select what value (e.g. Graduated, Promoted) to count.

For a simple metric, all options correctly appear in the UI:
<img width="600" alt="Screen Shot 2022-10-27 at 4 16 49 PM" src="https://user-images.githubusercontent.com/90279765/198389417-6f993ee8-3edf-4864-93b5-4392cff99374.png">

However, when using a repeated metric, the options to set the comparison (Equal, Not Equal) and what value (e.g. Graduated, Promoted) to count are missing in the UI:
<img width="600" alt="Screen Shot 2022-10-27 at 4 20 40 PM" src="https://user-images.githubusercontent.com/90279765/198390048-55a08717-1589-46d5-a46c-77858b75dfac.png">

Therefore, we need to find a way to add these 2 options to the metric table row. So far, I thought of 2 ways to do this:

<img width="600" alt="Experiments - Add Experiment-04-18" src="https://user-images.githubusercontent.com/90279765/198390578-a519cc6f-68c5-4d58-baa2-03d7772500f7.png">

<img width="600" alt="Experiments - Add Experiment-04-18 (1)" src="https://user-images.githubusercontent.com/90279765/198390745-93bfb244-7fa2-4982-af0b-b09b6b60b113.png">

And since none of these seems like a great option, I would suggest (@SritterCL and @amurphy-cl also suggested) revisiting the redesigns of the metrics table that I've discussed previously with @danoswaltCL and @jreddig, and also thinking about other new ideas. Here's the link to the discussion post on Slack: https://carnegielearning.slack.com/archives/C02QA168MNW/p1657905578489829

I think we've come up with 4 different redesign ideas:

1. Metric (key) selection without category
<img width="600" alt="version 2" src="https://user-images.githubusercontent.com/90279765/198393015-56ec7a81-8acd-4885-9602-0c41b5bb10e3.png">

2. A separate KEY column (Overall key means simple metric)
<img width="600" alt="version 3" src="https://user-images.githubusercontent.com/90279765/198393209-c863c809-7f4e-458f-b4ec-c954676a4bf7.png">

3. Like 2 but Key and Metric fields are placed vertically
<img width="600" alt="version 4" src="https://user-images.githubusercontent.com/90279765/198393397-e55428b9-849f-48fd-936d-c0ab50d0cdf7.png">

4. A list of cards instead of a table
<img width="750" alt="image" src="https://user-images.githubusercontent.com/90279765/198393589-9f43c981-2fed-4b2a-bb6e-d7ebd5b98c64.png">

I'm not sure if any of these designs would make it easier to add the missing options (comparison, value) to a table row though. I would like to further discuss this with other people on the team.

**Comment by ppratikcr7** [comment]
@zackcl I guess you are using the the `masteryWorkspace` metric with a `continuous` type in `workSpaceCompletionStatus`. That's the reason it won't show the options to set the comparison (Equal, Not Equal) and what value (e.g. Graduated, Promoted) to count. I tried replacing the metrics definition in the .env file and it works as expected as shown below. You can try out this metric string in `.env` to see what you expect in this ticket: 

`{ "groupClass": "masteryWorkspace", "allowedKeys": [ "calculating_area_various_figures", "Compare_functions_diff_reps_quadratic" ], "attributes": [{"metric": "workspaceCompletionStatus","datatype": "categorical", "allowedValues": ["GRADUATED", "PROMOTED"]}]}

<img width="846" alt="Screenshot 2022-10-31 at 12 17 40 PM" src="https://user-images.githubusercontent.com/33730817/198948932-94573960-4940-4b08-8342-74185a96cf0d.png">
`

**Comment by zackcl** [comment]
@ppratikcr7 Wow, that worked, thank you!

Hey @jreddig, can you check if the type was correctly set for the metrics being used in the AA experiments in PROD? (I tried to see https://upgradeapi.carnegielearning.com/api/metric but forgot how to authorize it)

**Comment by jreddig** [comment]
Here's the response from https://upgradeapi.carnegielearning.com/api/metric . I see categorical for workspaceCompletionStatus in both masteryWorkspace and conceptBuilderWorkspace

```
{
       "key":"conceptBuilderWorkspace",
       "children":[
          {
             "key":"recognizing_growth_and_decay",
             "children":[
                {
                   "key":"timeSeconds",
                   "children":[
                   ],
                   "metadata":{
                      "type":"continuous"
                   },
                   "allowedData":null
                },
                {
                   "key":"hintCount",
                   "children":[
                   ],
                   "metadata":{
                      "type":"continuous"
                   },
                   "allowedData":null
                },
                {
                   "key":"errorCount",
                   "children":[
                   ],
                   "metadata":{
                      "type":"continuous"
                   },
                   "allowedData":null
                },
                {
                   "key":"completionCount",
                   "children":[
                   ],
                   "metadata":{
                      "type":"continuous"
                   },
                   "allowedData":null
                },
                {
                   "key":"workspaceCompletionStatus",
                   "children":[
                   ],
                   "metadata":{
                      "type":"categorical"
                   },
                   "allowedData":[
                      "GRADUATED"
                   ]
                },
                {
                   "key":"problemsCompleted",
                   "children":[
                   ],
                   "metadata":{
                      "type":"continuous"
                   },
                   "allowedData":null
                }
             ],
             "metadata":{
                "type":"continuous"
             },
             "allowedData":null
          },
```

**Comment by SritterCL** [comment]
Not sure if this is related to the bug, but we shouldn't have workspaceCompletionStatus for concept builders (since there's no concept of mastery). It looks like there's only one allowedValue for it ("Graduated"), which is weird, so maybe that's a clue.

**Comment by jreddig** [comment]
removed workspaceCompletionStatus from conceptBuilderWorkspace, still seeing the issue in production

**Comment by zackcl** [comment]
Do you mean the options to set the comparison (Equal, Not Equal) and what value (e.g. Graduated, Promoted) to count are still missing in the UI even when `masteryWorkspace`, `simplify_exponents_3_prod_quot_power`, and  `workspaceCompletionStatus` are selected?

**Comment by jreddig** [comment]
Yeah, if you copy the bearer token from the network calls in Chrome, you can authenticate in Postman to double check the changes in metric metadata. But, I don't see the options to set the comparison and value.
I see this when I `GET /metric` but I don't see the options in the UI. The script to update the metric metadata is in the GHE research-utilities repository if you'd like to check it out
```
{
  "key": "workspaceCompletionStatus",
  "children": [],
  "metadata": {
      "type": "categorical"
  },
  "allowedData": [
     "GRADUATED",
      "PROMOTED"
  ]
}
```

**Comment by ppratikcr7** [comment]
@zackcl Okay, let me check on this.

**Comment by jreddig** [comment]
Updated metrics in dev/staging and this looks good! QA successful
