### ISSUE TITLE
[backend] Add support for specifying clientApi config with environment variables

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#6]
I'd like to be able to specify values for this part of config.json with two environment variables instead:
```
"clientApi": {
    "secret": "carnegilearning",
    "data": {
      "APIKey": "494ae733-53cb-4c64-a24e-dab23d55eeb4"
    }
  }
```
Similar to how we already do that for context and adminUsers. We'll need two variables, maybe:
CLIENT_API_SECRET
CLIENT_API_KEY

**Comment by JD2455** [comment]
@mfugate1 
I've added variables named _CLIENT_API_SECRET_ and _CLIENT_API_KEY_ in environment variables which is used to validate all client SDK calls coming to upgrade server.

To generate jwt token for client SDK,
`const data = {
          APIKey: env.clientApi.key,
        };
  const tokenSigned = jwt.sign(data, env.clientApi.secret);`
 
 _tokenSigned_ will be passed in the request header for client SDK calls.

**Comment by mfugate1** [comment]
@msandbothe I merged this into main and deployed to QA. I sent you the key and secret in an email, can you test to see if it works?

**Comment by msandbothe** [comment]
@mfugate1 I confirmed that a jwt token created with the key/secret you sent me works on upgrade qa cli. Also verified that an incorrect key/secret hits the authentication error.
