### ISSUE TITLE
Change how metrics lambda from Mathia is triggered.

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#619]
**Is your feature request related to a problem? Please describe.**
Currently metrics lambda fires every time it gets event from SMS, but that ends up being too often, and potentially exacerbates latency issues that we are seeing in prod when the application encounters quick bursts of traffic.

**Describe the solution you'd like**
Fire less frequently, probably good enough once per day in off-peak hours. Potentially re-evaluate other configurations for firing off these requests to /log if that creates a new issue of too many messages queued up in SMS...

**Comment by danoswaltCL** [comment]
@msandbothe we may need your assistance on this one! we've talked about it but I think now it's a boiled frog given prod latency issues, turning it off seems to have helped temporarily (hard to say as traffic in prod has also been slower this week overall, so not sure 100%, but it's a change we should make anyway).

**Comment by amurphy-cl** [comment]
Closed - will not be actively working on this in the near future.
