### ISSUE TITLE
Participants Stepper Tab UI enhancement

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#636]
**User Story**
Now, the end user should not select `Include Specific/Include All Except...` from the dropdown in the Participants Stepper Tab. 
 - User needs to select `type` as `All` in Include list's first row, so that they can enable the Except list.
 - In case the user later changes any other Type to `All`, then it would automatically delete all the other Include list rows as they are not relevant any more.

<img width="516" alt="Screenshot 2022-11-29 at 1 25 35 AM" src="https://user-images.githubusercontent.com/33730817/205064310-d8e39836-830c-45b8-9a96-db420442d239.png">

**Comment by jreddig** [comment]
Exclude does not appear until Include list is selected and 'All' is an option. Closing as done
