### ISSUE TITLE
Terms and Conditions Link is not clickable and Content for the same is not present

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#637]
**Describe the bug**
On the Upgrade Login Page, the `Terms and Conditions` Link is not clickable and the content for the same is not present. Probably we should provide the terms and conditions page for this.

**To Reproduce**
Go to the main Upgrade portal login page. You can try clicking the `Terms and Conditions` Link.

**Expected behavior**
We should provide the terms and conditions page for this.

**Screenshots**
<img width="654" alt="Screenshot 2022-11-24 at 2 40 24 PM" src="https://user-images.githubusercontent.com/33730817/205066716-cad02b76-6d2d-45e6-8d5e-37591e3100f3.png">

**Comment by amurphy-cl** [comment]
Let's remove the text below the login button. Terms and conditions are basically the BSD-3 license, which aren't really relevant to using Google to login.
