### ISSUE TITLE
An imported experiment should always be inactive

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#644]
**Describe the bug**
~Currently, if an enrolling experiment is exported, the exported JSON file contains `"state":"enrolling"`. So if the file is imported, the experiment status is set to "enrolling" making it not possible to edit or schedule the experiment. Therefore, I believe an exported experiment's status should always be "inactive".~

An imported experiment should always be set to "inactive". (updated due to Steve's comment below)

**To Reproduce**
1. Create an experiment in UpGrade
2. Set the experiment status to "enrolling"
3. Export the experiment file in JSON
4. Delete the experiment and try importing the exported file
5. You will see the imported experiment is set to "enrolling"

**Expected behavior**
An imported experiment's status should always be "inactive".

**Video**
https://user-images.githubusercontent.com/90279765/205711101-85a999a2-91e0-47e7-a395-3ef7c95ea80b.mov

**Comment by SritterCL** [comment]
I would allow the export (you might want to document the experiment design or duplicate and modify it for some purpose), but I'd ignore "state" when importing and always set the imported experiment to "inactive".
