### ISSUE TITLE
Change the order of shading in the Aliases table

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#660]
**Describe the bug**
This would be a design enhancement rather than a bug, but I think the order of shading in the Aliases table should be changed so that the shading is not used when there's only one decision point in the table.

Currently, it seems like the shading works from the first decision point like the following:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/90279765/206524980-c87ecaff-16f2-489c-ac60-81ef6f671b6b.png">

And if there's only one decision point, we would see the shading unnecessarily.
<img width="750" alt="Screen Shot 2022-12-08 at 12 43 55 PM" src="https://user-images.githubusercontent.com/90279765/206525197-707ec5c9-050e-4bdf-9a1c-5751d6bc1864.png">

Therefore, I think it's better to start with "Not shaded" and then "shaded" to distinguish different decision points.

**To Reproduce**
Create an experiment with a single decision point and check the Aliases table.

**Expected behavior**
The Aliases table shouldn't have shaded rows if there's only one decision point.

**Additional Context**
This is related to: https://github.com/CarnegieLearningWeb/UpGrade/issues/414

**Comment by danoswaltCL** [comment]
i can just change it to shade the other way around, so the shading starts with the second-indexed set of decision-point rows, np

**Comment by jreddig** [comment]
Shading starts with second-indexed. Closing as done
