### ISSUE TITLE
Statistic drop-down doesn't show the menu until a Metric is selected

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#664]
**Describe the bug**
In the Metrics step in the experiment stepper, the Statistic drop-down doesn't work until a Metric is selected from the list. Once a Metric is selected, then the Statistic drop-down menu appears (even when the Metric field is empty). See the video:

https://user-images.githubusercontent.com/90279765/207723993-febea4aa-92a7-4ec5-a58f-da5d73af940b.mov

**To Reproduce**
1. Go to the Metrics step in the experiment stepper
2. Click on the Statistic drop-down while the Metric field is empty
3. You won't see the Statistic drop-down menu
4. Type in (not select) any valid metric (e.g. totalTimeSeconds) to the Metric field, and click on the Statistic drop-down again
5. You still won't see the Statistic drop-down menu
6. Now select a metric from the Metric drop-down menu
7. Click on the Statistic drop-down again
8. Now you will see the Statistic drop-down menu
9. Delete the row and add a new row
10. Click on the Statistic drop-down menu while the Metric field is empty
11. You will be able to see the Statistic drop-down menu (This should be the default behaviour I think)

**Expected behavior**
The Statistic drop-down menu should appear even while the Metric field is empty and not selected.

**Additional context**
I think the user-entered Metric should still be valid which means typing "totalTimeSeconds" instead of selecting from the drop-down menu should still work. Maybe this is how it works already but I just wanted to make sure.

**Comment by ppratikcr7** [comment]
I feel the statistic options are based on the metric that is selected, so it shouldn't be allowed to be filled before a metric is selected. I will look for the type(not select) and then activate the statistic list. But there is a select event called to set the statistic options, so need to figure out how to trigger an event on just typing and clicking on statistics dropdown. Still I find this not to be a bug. @danoswaltCL @amurphy-cl  @nirmalpatel @VivekFitkariwala Your views on this?

**Comment by amurphy-cl** [comment]
Well if we can activate the statistic list when the field is typed in, that seems fine. But if it operates only like a dropdown, the field should be a dropdown and not allow typed-in response.

**Comment by danoswaltCL** [comment]
@ppratikcr7 I think you're right, the place where there's definitely a bug is that after deleting the row and coming back, the statistics dropdown was selectable before a metric was selected. We do want a valid metric first.

I wonder if there is a good way to get the same function to run on 'blur' event on input field itself. I think that would be the event we would want for typing in a metric. People have wondered about this with mat-autocomplete in [stackoverflow](https://stackoverflow.com/questions/61121364/angular-autocomplete-input-selected-and-blur-event-race-condition), so it's not just us, this for whatever reason is maybe not the intended behavior out-of-the-box with this component, but I think we still do not want a dropdown as there would be too many items.

**Comment by danoswaltCL** [comment]
@amurphy-cl I think we still want the autocomplete, because a dropdown unfiltered could have a bazillion keys to search through with all the workspaces.

i'm playing around with this, it's not so simple of course, as the selection in the menu is really for an object, not a string, so the value in the selection is not the same as what is being typed. Making this work for typing in directly would add some additional functionality and rework to an already pretty overloaded and complex control, it's doing some fancy footwork behind the scenes to allow for different metric types to trigger different controls to show up, etc.

I'm feeling like @ppratikcr7 that this feels like it's basically working as required. Can we just make it clearer to the user that they must make a selection, not just type it out? On blur, we could have a gentle error message that says please make a selection from the menu.

**Comment by zackcl** [comment]
I agree with @danoswaltCL that we should show an error message to make a selection from the menu when the user types something in the Metrics field and clicks somewhere else (on blur) without making a selection from the menu. And maybe we can disable/grey out the Statistic dropdown until a valid Metric is selected to avoid confusion and fix the bug:

> I think you're right, the place where there's definitely a bug is that after deleting the row and coming back, the statistics dropdown was selectable before a metric was selected. We do want a valid metric first.

**Comment by ppratikcr7** [comment]
> @ppratikcr7 I think you're right, the place where there's definitely a bug is that after deleting the row and coming back, the statistics dropdown was selectable before a metric was selected. We do want a valid metric first.
> 
> I wonder if there is a good way to get the same function to run on 'blur' event on input field itself. I think that would be the event we would want for typing in a metric. People have wondered about this with mat-autocomplete in [stackoverflow](https://stackoverflow.com/questions/61121364/angular-autocomplete-input-selected-and-blur-event-race-condition), so it's not just us, this for whatever reason is maybe not the intended behavior out-of-the-box with this component, but I think we still do not want a dropdown as there would be too many items.

Okay, I will handle this bug.

**Comment by zackcl** [comment]
Here are a few suggestions for the error message:

* Please make a selection from the menu for Metric value.
* Metric value must be selected from the menu. Please choose an option.
* Invalid input for Metric value. Please select an option from the menu.
* Please select a valid Metric value from the menu.

And I think the message should be in the same format for the Segment Id/Name input field.

<img width="600" alt="Screen Shot 2023-03-10 at 1 52 50 PM" src="https://user-images.githubusercontent.com/90279765/224401293-38ebc699-7dca-4d03-ab9b-bee6f20086c9.png">

**Comment by jreddig** [comment]
@zackcl I'm having trouble validating this fix in dev region. When you have a chance, could you take a look?

**Comment by zackcl** [comment]
@jreddig I just tested it and I can see the error message when I didn't select a Segment from the menu which is expected. 
<img width="500" alt="Screen Shot 2023-08-11 at 9 42 05 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/45003f02-a9af-4292-b0c3-b9fee16780d9">

However, I don't see any error message when I just type out the metric ID and not select one from the menu.
<img width="500" alt="Screen Shot 2023-08-11 at 9 43 59 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/2c5d3406-fe44-4629-95e4-99498fec5216">

Therefore, I believe the issue has not been completely resolved. It would be nice if we can show an error message for the Metrics table as well (although it could be low priority). @ppratikcr7 @Yagnik56

**Comment by danoswaltCL** [comment]
QA: @zackcl

**Comment by zackcl** [comment]
It is still not fixed, but I'm not sure if it's worth addressing this considering the upcoming design refresh.

**Comment by danoswaltCL** [comment]
@amurphy-cl there was a question of whether this needs to be fixed, due to design changes coming
