### ISSUE TITLE
Excluded user semantics

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#67]
@SritterCL @amurphy-cl I found out that in our current implementation when you start enrolling students in an experiment, you explicitly exclude all of the users who have visited the points/IDs of that experiment. And even if these users don't visit those points/IDs again, they will remain marked as excluded from the experiment. So the current implementation is:

Number of Excluded Users = (Users who visited points/IDs **before** the experiment started enrolling) + (Users who visited points/IDs **before and after** the experiment started enrolling)

@SritterCL I'm not sure whether the total number should include both terms or only the latter. Can you give your take on this?

**Comment by amurphy-cl** [comment]
A note that I think we should avoid double-counting excluded users (or at least report somewhere how many are double-counted), e.g. "before AND after" because otherwise it muddies the picture of how many _participants_ are excluded vs. how many _visits_ are excluded.

**Comment by SritterCL** [comment]
Yeah, I think we should be counting participants, not visits.

I'm also not clear how you're counting students who are in groups, where the group is excluded (do they get counted at mark experiment point or before?)

Also, if the consistency rule is "experiment," then users who have previously been marked at the experiment point should *not* be excluded (not sure if you're checking that).

**Comment by amurphy-cl** [comment]
Do we need to better define exclusion criteria and place those excluded users into bins in the UI? One way to count excluded students is a) students in these categories who reach getAllExperimentConditions, or b) all students in a category who reach markExperimentPoint for a particular experiment 

1. Student reached experiment before enrollment begins
2. Student is on the explicit exclude list 
3. Student's group is on the explicit exclude list
4. Group was excluded for some reason and student is in the group
5. Misc exclusions (to eventually categorize)

**Comment by amurphy-cl** [comment]
@nirmalpatel I think this is addressed in our enrollment codes enums? If so let's close this.

**Comment by nirmalpatel** [comment]
Yes, this will be addressed in the enrollment code enums, and we will know the exact reason for exclusion. So using those codes, we can display the appropriate exclusion count.
