### ISSUE TITLE
GET api/explicitExclude/global/group 404 (Not Found)

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#679]
**Describe the bug**
I get the `GET api/explicitExclude/global/group 404 (Not Found)` error when I log in to UpGrade.

**To Reproduce**
1. Log in to UpGrade.

**Expected behavior**
The error should not happen.

**Screenshots**
<img width="1648" alt="Screen Shot 2023-01-09 at 4 24 10 PM" src="https://user-images.githubusercontent.com/90279765/211411564-1c3dc6ea-3ace-47f4-82a1-bf492ce99ef4.png">

**Comment by jreddig** [comment]
Hm, it looks like the explicitExclude apis are more integrated than I thought with the frontend and more needs removed. I'll see if I can find the rest of it
