### ISSUE TITLE
Experiment Design: Persist condition alias details instead of re-creating table with defaults when changes are made

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#684]
**Is your feature request related to a problem? Please describe.**
In stepper, if changes are made to experiment decision point or condition details, all details in alias table are regenerated with defaults. This was assumed to be the intended behavior or at least a marginal edge-case by yours truly, but in practice it has been shown to be a very annoying and common problem, especially when many custom aliases are required.

**Describe the solution you'd like**
We should be able to intelligently persist condition alias details for combinations in rows that are not changed, as much as is possible. This should be the case for both Simple and Factorial experiments.

**Comment by zackcl** [comment]
Don't we always add the decision points and conditions before updating the aliases? Is there any use case for updating the decision points and conditions after adding the custom aliases?

**Comment by amurphy-cl** [comment]
There is -- let's say you add 10 decision points and their respective aliases, update the experiment. Then another day you decide to add another decision point to the experiment. When you add that new decision point, the alias table clears out and goes back to defaults, which is a big pain especially with a lot of decision points involved. If you persist all the aliases except the new one, you only need to add the new aliases to update the experiment design.

**Comment by danoswaltCL** [comment]
@amurphy-cl I want to make sure that these are the intended requirements for scenarios when the user has entered some decision points and conditions, then enters some custom aliases, then goes back and modifies/adds/deletes decision point or condition data:

Current:

In the above scenario, any modification of the decision point or conditions at all will reset and regenerate the condition table. (NOTE: This will happen for factorial at the moment also. The expectations for these scenarios are probably the same and will need to be updated similarly).

Expected:

1) When a user ADDS a new row (whether that be a condition or decision point), any custom aliases for combinations that previously existed will remain, and new rows will have the default.

2) When a user REMOVES an existing row (whether that be a condition or decision point), any custom aliases for combinations that previously existed will remain, and the rows that involved the deleted elements will also be removed.

3) When a user MODIFIES the values of an existing row (i.e. corrects a typo), the alias table will NOT reset any custom aliases, although it will update any of the changes values.

So another way of stating the above is:

- NEVER wipe out custom aliases unless a row is deleted and the custom alias was attached to a combo that contained a deleted element.

Is that a true statement? I can think of some edge-casey scenarios where scenario 3 could be misleading to the user, but probably not worth worrying about.

**Comment by amurphy-cl** [comment]
This looks right to me!

**Comment by jreddig** [comment]
Tested in staging, looks good! Closing as done
