### ISSUE TITLE
UI: Reimplement new experiment stepper to solve for space issues

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#685]
**Is your feature request related to a problem? Please describe.**
The experiment design stepper is contained in simple modal, but has grown in complexity and space required.

- Text is often severely truncated
- Tables and forms contain more details than can be shown without scrollbars.
- Future features will continue to require extended design discussions and compromises to discover creative ways to fit into constrained spaces.
- Accessibility in modals is a nightmare; it would be interesting to have ours audited by an accessibility expert...

**Describe the solution you'd like**
[Several](https://carnegielearning.slack.com/archives/C02QA168MNW/p1673531555859029) [ideas](https://carnegielearning.slack.com/archives/C02QA168MNW/p1673544769267619) have been [discussed](https://carnegielearning.slack.com/archives/C02QA168MNW/p1671728777569859) w/ @zackcl and @amurphy-cl (and others) that could be combined to mitigate the space concerns:

- Larger modal
- Very large side-drawer (side-nav in Angular Material Library)
- Draggable column widths in tables to allow user to see more of truncated text
- Listing details in "Card"-style widgets vs. tables (to solve for natural text width constraints of table cells / rows).
- Scroll entire content-container of modal to prevent limiting viewable area of tables/form components (versus vertically scrolling within individual table/form components)
- Move stepper out of modal entirely and onto a regular feature content page.

Solutions to keep modal or side-nav are going to be significantly easier to implement, but don't truly solve much about the above issues will still be limiting long-term.

Solutions to move the stepper out of a modal and onto a feature content page will require more technical work as well as probable redesign of certain things, but offers much freer UX and long-term growth of the stepper as new experiment types and features are added.

IMHO: General UX best practice advise against modals except for the simplest interactions, and although there are many good exceptions to this rule, there's no reason to suffer if we don't have to. Moving the stepper to a feature content page ASAP is worth the investment and should offer both better UX and development ease long-term.

**Comment by amurphy-cl** [comment]
Turned into full design refresh.
