### ISSUE TITLE
 The edit/delete icons in the Design step should be disabled when the experiment is enrolling

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#698]
**Describe the bug**
<img width="500" alt="Screen Shot 2023-01-25 at 11 40 25 AM" src="https://user-images.githubusercontent.com/90279765/214623233-6cc17a30-322a-45b7-8edd-ba2fe7cd18d7.png">
Currently, the edit/delete icons for the tables in the Design step are enabled even when the experiment is enrolling. They should be disabled when the experiment status changes to "Enrolling".

**To Reproduce**
1. Create an experiment
2. Set the status to "Enrolling"
3. Click the "Edit" button and go to the Design step 
4. You will see the edit/delete icons for the tables are not disabled

**Expected behavior**
The edit/delete icons for the tables in the Design step should be disabled when the experiment is enrolling.

**Comment by ppratikcr7** [comment]
@zackcl Is this ticket relevant anymore? As we are going ahead with new UI refresh with no stepper. If not needed, we may close this.

**Comment by ppratikcr7** [comment]
> @zackcl Is this ticket relevant anymore? As we are going ahead with new UI refresh with no stepper. If not needed, we may close this.

@zackcl ?

**Comment by amurphy-cl** [comment]
This is ok to close.
