### ISSUE TITLE
Java API should not attempt retry on nonretryable errors

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#70]
Errors like 'x are root user and should not be converted to an alias of y' is not something that a retry should fix and thus should not attempt 3 times. This improvement can be made to the Java and Angular APIs separately.

**Comment by amurphy-cl** [comment]
@nirmalpatel is this still in progress?

**Comment by amurphy-cl** [comment]
Ok - @kawcl do you have a sense of the effort required for this?

**Comment by kawcl** [comment]
@amurphy-cl I am not very familiar with this code so it's hard to say but I think the first thing is that we need to define what we consider `nonretryable errors` and then out of all the errors the application throws determine which meet that definition and then resolve this issue for only those
