### ISSUE TITLE
Link to join Slack channel is expired

### ISSUE THREAD

**Issue by joshling1919** [CarnegieLearningWeb/UpGrade#701]
**Describe the bug**
On the https://www.upgradeplatform.org/about-upgrade/ page, the link to join the Slack channel is expired.

**To Reproduce**
1. Go to [upgradeplatform.org/about-upgrade](https://www.upgradeplatform.org/about-upgrade/)
2. Click 'Go to Slack Channel'

**Additional context**
This platform looks super promising and interesting, and I'd like to try and integrate it into our edtech platform. Having support via a Slack workspace would be tremendously helpful. Thanks!

**Comment by amurphy-cl** [comment]
Hi Josh, thanks for posting this issue. The invite link has been updated. If you're interested in integrating with your platform, feel free to get in touch with me directly: amurphy@carnegielearning.com
