### ISSUE TITLE
Import of old Simple Experiments not working

### ISSUE THREAD

**Issue by RidhamShah** [CarnegieLearningWeb/UpGrade#706]
Import of old Simple Experiments not working

**Comment by amurphy-cl** [comment]
Added to the milestone as this needs to be fixed for the current release.

**Comment by mswartzCL** [comment]
Needs to be QA'd with an old AA experiment

**Comment by amurphy-cl** [comment]
Import doesn't work with this json file from 2021, error is shown in screenshot.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/65311369/230440589-673bb169-e6ab-42fd-b735-43bfa21ae226.png">

json pasted below.

`{"createdAt":"2021-07-02T19:47:55.771Z","updatedAt":"2021-07-08T15:17:19.814Z","versionNumber":7,"id":"fe06349b-92de-4905-86dc-6cc20bf0f343","name":"BKT  - Measure central Tendency 2","description":"measures_central_tendency-2","context":["assign-prog"],"state":"enrollmentComplete","startDate":"2021-07-07T18:34:25.671Z","startOn":null,"endDate":"2021-07-08T15:17:19.808Z","consistencyRule":"individual","assignmentUnit":"individual","postExperimentRule":"assign","enrollmentCompleteCondition":{"userCount":500,"groupCount":0},"endOn":null,"revertTo":null,"tags":["bkt"],"group":null,"logging":false,"partitions":[{"createdAt":"2021-07-02T19:47:55.771Z","updatedAt":"2021-07-02T19:47:55.771Z","versionNumber":1,"id":"measures_central_tendency-2_SelectSection","twoCharacterId":"SS","expPoint":"SelectSection","expId":"measures_central_tendency-2","description":""}],"conditions":[{"createdAt":"2021-07-02T19:47:55.771Z","updatedAt":"2021-07-02T19:47:55.771Z","versionNumber":1,"id":"e574d1df-efca-43bf-af29-92215fa3d7d6","twoCharacterId":"B2","name":"","description":"control condition","conditionCode":"control","assignmentWeight":50},{"createdAt":"2021-07-02T19:47:55.771Z","updatedAt":"2021-07-02T19:47:55.771Z","versionNumber":1,"id":"83aa6728-6ccb-4b3e-b730-0e1a19ce813d","twoCharacterId":"6F","name":"","description":"variant condition","conditionCode":"fitted_skill_params","assignmentWeight":50}]}
`

**Comment by zackcl** [comment]
I'm getting the error `TypeError: Cannot read properties of undefined (reading 'split')` as soon as I choose the old experiment JSON file used for the demo app (created at 2021-11-30). I tried this on the `enhancement/new-factorial-designs` branch as the `dev` branch currently doesn't work for me (https://github.com/CarnegieLearningWeb/UpGrade/issues/762).

<img width="750" alt="Screen Shot 2023-04-06 at 1 33 17 PM" src="https://user-images.githubusercontent.com/90279765/230453527-73fe233f-56e6-4fb5-b51c-c0bac6007c89.png">

JSON pasted below:


`{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:46:00.059Z","versionNumber":3,"id":"ef17583e-32c4-4cc6-978a-fc0798cd9cb2","name":"Area - Concrete or Abstract","description":"","context":["add"],"state":"inactive","startOn":null,"consistencyRule":"individual","assignmentUnit":"individual","postExperimentRule":"continue","enrollmentCompleteCondition":null,"endOn":null,"revertTo":null,"tags":[],"group":null,"logging":false,"partitions":[{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:42:33.459Z","versionNumber":1,"id":"question_type_area","twoCharacterId":"TM","expPoint":"area","expId":"question_type","description":"","order":1}],"conditions":[{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:42:33.459Z","versionNumber":1,"id":"7f36116c-911f-4f2d-a2a4-0ecb8235b646","twoCharacterId":"AL","name":"","description":null,"conditionCode":"Concrete","assignmentWeight":50,"order":1},{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:42:33.459Z","versionNumber":1,"id":"eee2cada-0060-4170-8bdd-1e65a6cf5f73","twoCharacterId":"IN","name":"","description":null,"conditionCode":"Abstract","assignmentWeight":50,"order":2}],"stateTimeLogs":[],"queries":[{"createdAt":"2021-11-30T13:45:43.364Z","updatedAt":"2021-11-30T13:45:43.364Z","versionNumber":1,"id":"6fe20f98-c3e4-49b8-8fa1-5b6cdfcf18e9","name":"Duration in Seconds","query":{"operationType":"avg"},"repeatedMeasure":"MOST_RECENT","metric":{"createdAt":"2021-11-30T13:43:45.135Z","updatedAt":"2021-11-30T13:43:45.135Z","versionNumber":1,"key":"durationSeconds","type":"continuous","allowedData":null}},{"createdAt":"2021-11-30T13:46:00.059Z","updatedAt":"2021-11-30T13:46:00.059Z","versionNumber":1,"id":"ffc07527-5f94-424f-a72a-e046ff799aa7","name":"Percent Correct","query":{"operationType":"avg"},"repeatedMeasure":"MOST_RECENT","metric":{"createdAt":"2021-11-30T13:44:09.547Z","updatedAt":"2021-11-30T13:44:09.547Z","versionNumber":1,"key":"percentCorrect","type":"continuous","allowedData":null}}]}`

**Comment by amurphy-cl** [comment]
This is a relatively recent experiment, but we should not return an error if an import has no factors

<img width="499" alt="image" src="https://user-images.githubusercontent.com/65311369/232074780-1285a6db-761a-4e52-a4e2-c771ceb54872.png">

**Comment by ppratikcr7** [comment]
> I'm getting the error `TypeError: Cannot read properties of undefined (reading 'split')` as soon as I choose the old experiment JSON file used for the demo app (created at 2021-11-30).
> 
> <img alt="Screen Shot 2023-04-06 at 1 33 17 PM" width="750" src="https://user-images.githubusercontent.com/90279765/230453527-73fe233f-56e6-4fb5-b51c-c0bac6007c89.png">
> 
> JSON pasted below:
> 
> `{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:46:00.059Z","versionNumber":3,"id":"ef17583e-32c4-4cc6-978a-fc0798cd9cb2","name":"Area - Concrete or Abstract","description":"","context":["add"],"state":"inactive","startOn":null,"consistencyRule":"individual","assignmentUnit":"individual","postExperimentRule":"continue","enrollmentCompleteCondition":null,"endOn":null,"revertTo":null,"tags":[],"group":null,"logging":false,"partitions":[{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:42:33.459Z","versionNumber":1,"id":"question_type_area","twoCharacterId":"TM","expPoint":"area","expId":"question_type","description":"","order":1}],"conditions":[{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:42:33.459Z","versionNumber":1,"id":"7f36116c-911f-4f2d-a2a4-0ecb8235b646","twoCharacterId":"AL","name":"","description":null,"conditionCode":"Concrete","assignmentWeight":50,"order":1},{"createdAt":"2021-11-30T13:42:33.459Z","updatedAt":"2021-11-30T13:42:33.459Z","versionNumber":1,"id":"eee2cada-0060-4170-8bdd-1e65a6cf5f73","twoCharacterId":"IN","name":"","description":null,"conditionCode":"Abstract","assignmentWeight":50,"order":2}],"stateTimeLogs":[],"queries":[{"createdAt":"2021-11-30T13:45:43.364Z","updatedAt":"2021-11-30T13:45:43.364Z","versionNumber":1,"id":"6fe20f98-c3e4-49b8-8fa1-5b6cdfcf18e9","name":"Duration in Seconds","query":{"operationType":"avg"},"repeatedMeasure":"MOST_RECENT","metric":{"createdAt":"2021-11-30T13:43:45.135Z","updatedAt":"2021-11-30T13:43:45.135Z","versionNumber":1,"key":"durationSeconds","type":"continuous","allowedData":null}},{"createdAt":"2021-11-30T13:46:00.059Z","updatedAt":"2021-11-30T13:46:00.059Z","versionNumber":1,"id":"ffc07527-5f94-424f-a72a-e046ff799aa7","name":"Percent Correct","query":{"operationType":"avg"},"repeatedMeasure":"MOST_RECENT","metric":{"createdAt":"2021-11-30T13:44:09.547Z","updatedAt":"2021-11-30T13:44:09.547Z","versionNumber":1,"key":"percentCorrect","type":"continuous","allowedData":null}}]}`

@zackcl In the old json you are missing the version field, I will handle that. In case version not present, we wont be able to verify the json is old or new. Hope that's fine. ( Missing Field: "backendVersion":"3.0.10")

Also, after resolving version, the old experiments' partition id's where string made of `site_target` and we expect a uuid now, so would handle this while import. We will replace this with a new uuid.
For e.g.:
```
"partitions": [
        {
            "createdAt": "2021-11-30T13:42:33.459Z",
            "updatedAt": "2021-11-30T13:42:33.459Z",
            "versionNumber": 1,
            "id": "question_type_area",
            "twoCharacterId": "TM",
            "expPoint": "area",
            "expId": "question_type",
            "description": "",
            "order": 1
        }
    ],
```

**Comment by ppratikcr7** [comment]
> This is a relatively recent experiment, but we should not return an error if an import has no factors
> 
> <img alt="image" width="499" src="https://user-images.githubusercontent.com/65311369/232074780-1285a6db-761a-4e52-a4e2-c771ceb54872.png">

@amurphy-cl Okay, I will handle this on import.

**Comment by ppratikcr7** [comment]
> This is a relatively recent experiment, but we should not return an error if an import has no factors
> 
> <img alt="image" width="499" src="https://user-images.githubusercontent.com/65311369/232074780-1285a6db-761a-4e52-a4e2-c771ceb54872.png">

Probably this experiment would be having factors but inside partitions key. We now expect factors at root level in experiment json object. Can you please share the JSON for this experiment so that I can verify it if that's the reason.

**Comment by amurphy-cl** [comment]
sure, here's the json (it's too long to paste and json can't be attached directly for some reason)

[XPRIZE_ Indian River.json.zip](https://github.com/CarnegieLearningWeb/UpGrade/files/11333065/XPRIZE_.Indian.River.json.zip)

**Comment by ppratikcr7** [comment]
> sure, here's the json (it's too long to paste and json can't be attached directly for some reason)
> 
> [XPRIZE_ Indian River.json.zip](https://github.com/CarnegieLearningWeb/UpGrade/files/11333065/XPRIZE_.Indian.River.json.zip)

Okay, thanks. I am able to import this with the code changes. I will create a PR soon.
<img width="1242" alt="Screenshot 2023-04-27 at 11 35 06 AM" src="https://user-images.githubusercontent.com/33730817/234776705-834044f8-8730-462a-bdd2-c03af6de8cb9.png">

**Comment by jreddig** [comment]
Import was fixed and is now in production!
