### ISSUE TITLE
Angular API should not attempt retry on nonretryable errors

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/UpGrade#71]
Errors like 'x are root user and should not be converted to an alias of y' is not something that a retry should fix and thus should not attempt 3 times. This improvement can be made to the Java and Angular APIs separately.

**Comment by VivekFitkariwala** [comment]
@amurphy-cl and @msandbothe did you guys verified this?

**Comment by amurphy-cl** [comment]
I think once @ppratikcr7 reviews/approves #78 we can verify this

**Comment by ppratikcr7** [comment]
@amurphy-cl I have reviewed and approved it now. You can verify the PR.
