### ISSUE TITLE
"/userAliases" errors in prod, highly correlated with prod latency Jan 30- Feb 3

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#710]
**Describe the bug**
In production, we can see too many of this error in the  POST `/useraliases` endpoint. It seems to be highly correlated enough with the prod latency issues reported week of Jan 30- Feb 3.

```
QueryFailedError: duplicate key value violates unique constraint "PK_bb6db004eeb82db68de9225e877"
    at QueryFailedError.TypeORMError [as constructor] (/usr/src/app/packages/Upgrade/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/usr/src/app/packages/Upgrade/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/usr/src/app/packages/Upgrade/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:124:57)
    at rejected (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
Not sure how to reproduce

**Expected behavior**
I'm not sure if this indicates a real error or is just noise, but it's noise that should still be handled

**Screenshots**
<img width="651" alt="image" src="https://user-images.githubusercontent.com/97542869/216691283-36fbf48f-b95d-4208-92d4-62bd9d1c9897.png">

**Comment by danoswaltCL** [comment]
@jreddig and i tried to reproduce but it's really hard to nail down how this could happen. The issue may be in using typeorm's save method, that is my best guess at this point https://github.com/typeorm/typeorm/issues/7736

https://github.com/typeorm/typeorm/issues/3772

https://dev.to/rishit/optimizing-typeorm-tips-from-experience-part-1-dont-use-save-4ke9

So `save` is doing a check for doc existence before either doing in `update` or `insert` every time. The workaround for this seems to be to do this manually, if we need that functionality. If we don't need it to check for existence, maybe we do `insert` or `update` instead...

The way I read the bug is that in the `save` implementation with PostGRES and how we are using it in this particular instance there may be a subtle chance of TypeORM trying to do `insert` where it should do `update`, which I think could cause this error?

**Comment by danoswaltCL** [comment]
The only way I have been able to get this error to come up on purpose is to change `save` to `insert` and send in duplicate aliases.

```
if (userAliasesDocs.length) {
      let aliasesUsers = await this.userRepository.save(userAliasesDocs); <--- changed this to insert
      aliasesUsers = aliasesUsers.map((user) => {
        const { originalUser, ...rest } = user;
        return { ...rest, originalUser: originalUser.id };
      });
      return [...aliasesUsers, ...alreadyLinkedAliases];
    }
```

That makes sense if internally typeorm is attempting `insert` when it should have done `update`, but again, I have not been able to find a way to create db + request data to make this happen in local.

**Comment by danoswaltCL** [comment]
Finally figured it out, I can reproduce it. It is a specific sequence.

1. `/init` new User.

```
{
  "id": "testguy",
  "group": {
    "schoolId" : [
      "1234"
    ]
  },
  "workingGroup": {
    "schoolId":"1234"
  }
}
```

2. send in a request with duplicate alias strings:

```
"userId": "testguy",
  "aliases": [
    "testguydupe",
    "testguydupe"
  ]
```

Result: `QueryFailedError: duplicate key value violates unique constraint`

Note that if the user has already had some aliases set, it will NOT fail when sending in dupes.

1. `/init` new User.

```
{
  "id": "testguy2",
  "group": {
    "schoolId" : [
      "1234"
    ]
  },
  "workingGroup": {
    "schoolId":"1234"
  }
}
```

2. send in a request with unique alias strings:

```
"userId": "testguy2",
  "aliases": [
    "testguyA",
    "testguyB"
  ]
```

23 send in a request with duplicate alias strings:

```
"userId": "testguy2",
  "aliases": [
    "testguyA",
    "testguyA"
  ]
```

Result: OK

**Comment by danoswaltCL** [comment]
I am still wondering about misusing `Repository.save` now, but this patch works in my local to just dedupe the array in the request in the ExperimentUserService in the first place, I may push a hotfix with this. @VivekFitkariwala does this seem ok? Or do we feel like this is a band-aid?

```
const dedupedArray = [...new Set(aliases)];
dedupedArray.map((aliasId) => {
      promiseArray.push(
        this.userRepository.findOne({
          where: { id: aliasId },
          relations: ['originalUser'],
        })
      );
});
```

**Comment by danoswaltCL** [comment]
@jerith666 this hypothesis suggests that Mathia is sending duplicate "contextIds" to the request to set alt user ids. Clearly our code needs to anticipate that possibility, but from Mathia perspective, is duplicate aliases wierd? Is that an expected possibility? This particular error started showing up morning of Jan 31.

**Comment by VivekFitkariwala** [comment]
This seems good. I don't think we can remove the duplicates through SQL before inserting so doing it in javascript seems right.

**Comment by jerith666** [comment]
I think the only way that could happen is if a class's syllabus contained the same assignment more than once.  I would've thought the syllabus data service would prevent creation of such a syllabus, but it looks like it doesn't.  :-/

If you change [the API](https://github.com/CarnegieLearningWeb/UpGrade/blob/dev/clientlibs/java/src/main/java/org/upgradeplatform/client/ExperimentClient.java#L382) of `setAltIds()` to take a `Set<String>` rather than a `List<String>`, that'd prevent this in the future (at least from clients using the Java client lib).

**Comment by danoswaltCL** [comment]
I haven't found logging to catch it in the act sending duplicates, if this fix works then it must be.

**Comment by VivekFitkariwala** [comment]
We can use query builder with onConflict for supporting  upsert feature. This will take single db call for the same. Here is an example https://github.com/CarnegieLearningWeb/UpGrade/blob/dd255b123e1acc9e745775e6e9d132f0fea0335d/backend/packages/Upgrade/src/api/repositories/UserRepository.ts#L8
