### ISSUE TITLE
Set experiment group key from context metadata

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#72]
The group keys for class, school, and instructor are right now hardcoded as "class", "school", and "teacher". We need to have a way to define custom keys for class/school/instructor. We can add this detail in the context metadata.

**Comment by SritterCL** [comment]
Yes - the spec here https://docs.google.com/document/d/13SvJajnCcH0cqMD7gPqb5MWmynzJrVqmD5a5tooPeNo/edit#heading=h.ytlzcnrrqnwt has the group types specified in the metadata (for each AppContext).

**Comment by amurphy-cl** [comment]
Closing this; @SritterCL will be opening a related issue.
