### ISSUE TITLE
Small bugs in various metric queries

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#723]
**Describe the bug**
There are bugs in the metrics query results for mixed of continuous and categorical metric at attribute level in a Grouped Metric. The list of bugs are as below:

1. Simple metrics not working fine when passing multiple uniquifier in Grouped metrics
2. Mean and Most Recent Sum Repeat Measure for categorical gives wrong result
3. When we have a continuous metric at the last child node in Grouped metrics, the edit mode has stats dropdown for categorical as we have another categorical metric in the other child node.
4. Metrics Tab categorical metric at child level doesn’t show proper stats
5. Remove Mean Repeat Measure for Categorical Metrics at the attribute level in Grouped Metric.
6. Return 0 result in api ‘log’ to show empty results in Data Tab

**Comment by danoswaltCL** [comment]
@amurphy-cl @mswartzCL will we want these changes in for `Ardent Angle`?

**Comment by mswartzCL** [comment]
I think we should focus on getting factorial done.

**Comment by ppratikcr7** [comment]
This is mostly done, we are testing at our end.

**Comment by jreddig** [comment]
Metrics bugs fixed in QA! Moving to done
