### ISSUE TITLE
Selecting the "Group" Unit of Assignment breaks the app

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#726]
**Describe the bug**
When creating an experiment, if I select "Group" Unit of Assignment in the Overview step, UpGrade stops working, and I see the error message in the console "TypeError: Cannot read properties of undefined (reading 'state')...".

**To Reproduce**
1. Click "Add Experiment"
2. Select "Group" Unit of Assignment in the Overview step
3. Check the developer console

**Expected behavior**
The error should not occur.

**Video**

https://user-images.githubusercontent.com/90279765/223153306-ffce0891-c3e4-4caf-8c5f-4b456197c89e.mov

**Comment by danoswaltCL** [comment]
@zackcl @ppratikcr7 i see this, small thing introduced by merging in the factorial details page code, I have probable fix, will push up
