### ISSUE TITLE
Segment with additional fields for stratified random sampling

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#734]
**Is your feature request related to a problem? Please describe.**
As part of a deliverable, we need to develop a way to use demographic data (imported or via a roster system) to support stratified random sampling.

**Describe the solution you'd like**
An MVP of this could look be a csv upload of data with an anonymous user id mapped to a particular strata. This could be done within a definition of Segment. The Segment could include existing group information such as schoolid, teacherid, or classid, plus additional data as defined in the csv for stratification. However, if this information is static and the roster information is dynamic, how will we deal with conflicts (or should we just exclude users with conflicts)?

**Describe alternatives you've considered**
More complex approaches include acquiring information from the roster service, or building a pipeline to acquire data from some other source (e.g. a public database). 

**Additional context**
Looking at how Pendo manages anonymizing group information might be helpful. 

**Shaping Document**
[Stratified Random Sampling in UpGrade](https://docs.google.com/document/d/1CwP7ugHVy9aG-KfXUVSv9z7fuWzq-XsmCQCwrtBqxic/edit?usp=sharing)

**Comment by zackcl** [comment]
I think one possible approach would be to have the educational app send custom attributes to UpGrade, and apply rules to create a segment as written in my [proposal document](https://docs.google.com/document/d/1FikzXKwK_ppSXUGxSjzLro_vilAp8afql9p1YS8655U/edit?usp=sharing).

Example Code:
```
const attributes = {
    studentId: "JLOmyjM7H8I"
    grade: 4,
    age: 10,
    gender: "Male",
    schoolType: ["Middle School", "Public School", "Charter School"],
    schoolName: "Arsenal School"
    districtName: "Pittsburgh Public Schools",
    operatingSystem: "Windows",
    consentObtained: true,
    workspacesCompleted: ["calculating_area", "compare_functions_diff"],
    date: new Date().toISOString(),
    version: "6.19.12"
}
await upClient.setSegmentMembership(attributes);
```

Example Rule:
```
Include users where "grade" is greater than or equal to 3 AND "schoolType" contains "Elementary School" AND "city" equals "Pittsburgh"
```

**Comment by amurphy-cl** [comment]
Closing this to replace with https://github.com/CarnegieLearningWeb/UpGrade/issues/956
