### ISSUE TITLE
Creating dynamic condition table from factors table

### ISSUE THREAD

**Issue by Yagnik56** [CarnegieLearningWeb/UpGrade#742]
We have function to create condition table from only 2 factors now so I am trying make it dynamic for n number of factors.

I have created function to generate Condition Table row data dynamically, so I wanted ask if we have any design for how to show more than 2 factors column in condition table or we would like to keep only 2 factors there for now? @zackcl @danoswaltCL 

I have added some screenshots to show function's work, 
Added 3 factors each with 2 level with name from factors first two alphabets each
![image](https://user-images.githubusercontent.com/50392803/225040431-da57e77f-6ed1-4857-8f1d-88d7c5d2dcaa.png)

which will generate 8 conditions, because UI doesn't support more than 2 factors yet data repeating there in right order but you can look into alias for all permutations.
![image](https://user-images.githubusercontent.com/50392803/225041332-94b6cc97-0a9d-4758-a81d-9e9ab450e3db.png)

this is a data return from function for creatingConditionTable.
![image](https://user-images.githubusercontent.com/50392803/225042767-98584536-5efb-4eb1-8ec7-38029a06afbd.png)

**Comment by zackcl** [comment]
@Yagnik56 We've decided to make changes to the factorial experiment design. You can check [this comment](https://github.com/CarnegieLearningWeb/UpGrade/issues/392#issuecomment-1466608087) to see the changes in the UI design. And you can read [this document](https://docs.google.com/document/d/1yeK-8mH39RIc7AV5ioY6dcwdGA8RbSWt5e0zLqwavXA/edit?usp=sharing) to understand how the new design works. 

To answer your question, we will replace the factor names in the Conditions table with a single Condition column. The Condition values will be displayed as a semicolon-delimited string, such as `Concrete; Mindset`. You will be able to find the screenshots showing this from the links I shared above.

Please let me know if you have any other questions.
