### ISSUE TITLE
Update Gitbook for v4, versioned documentation

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#744]
**Describe the solution you'd like**
Update Gitbook Developer guide for 4.x
https://upgrade-platform.gitbook.io/upgrade-documentation/

- Introduce versioned documentation in Gitbook
- Update Client SDK and API sections
- Add in missing documentation for Metrics and Context Metadata
- Update other outdated info as I come across it

**Comment by jreddig** [comment]
@danoswaltCL You did an absolutely massive revamp to the Gitbook documentation and imported the updated API signatures. Can we close the v4 ticket and maybe open one for v5?

**Comment by danoswaltCL** [comment]
yeah, that sounds like a plan

**Comment by jreddig** [comment]
Closing v4 documentation!
