### ISSUE TITLE
Response to the api/assign request should be updated

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#745]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the new factorial experiment design ([doc](https://docs.google.com/document/d/1yeK-8mH39RIc7AV5ioY6dcwdGA8RbSWt5e0zLqwavXA/edit?usp=sharing)). 
Related issues: https://github.com/CarnegieLearningWeb/UpGrade/issues/746, https://github.com/CarnegieLearningWeb/UpGrade/issues/392#issuecomment-1466608087

**Describe the solution you'd like**
The response structure should be an array of decision point objects as it is now, and a decision point object should consist of the `site`, `target`, `experimentType`, `assignedFactor`, and `assignedCondition` keys. Also, some unused keys (by the client app) should be removed from the structure. The `payload` can be `null` or `{ type: string | json | csv, value: string }` (only `string` type will be supported for Ardent Angle).

Example response:
```
[
 {
   "site": "geometry",
   "target": "colored_shape",
   "experimentType": "factorial",
   "assignedFactor": {
       "Color": {
         "level": "Blue",
         "payload": null
       },
       "Shape": {
         "level": "Triangle",
         "payload": null
       }
   },
   "assignedCondition": {
     "id": "223106b2-24dc-427b-9999-079c1dd0e1d3",
     "condition": "Color=Blue; Shape=Triangle",
     "payload": {
       "type": "string",
       "value": "img.com/blue_triangle.png",
     }
   }
 }
]
```

**Comment by RidhamShah** [comment]
This structure is present in `v4` versioning of Client-Side APIs, so we can close this issue
