### ISSUE TITLE
Remove Terraform scripts from CL Repo

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#755]
**Is your feature request related to a problem? Please describe.**
CL SRE have copied terraform scripts into a private CL repo that will be maintained by them. I asked if we should remove them from our repo altogether, and the recommendation was yes, so I'd like to remove them.

But I want to discuss this with everyone, maybe this can be a Thursday topic.

Are there compelling reasons to still maintain Terraform scripts in our repo? Should we keep example scripts in there, since that is the only way we've documented cloud hosting it at this point?

**Comment by amurphy-cl** [comment]
@nirmalpatel @VivekFitkariwala do you guys need these scripts?

**Comment by VivekFitkariwala** [comment]
We can get it back from git history whenever we need it. So we can go ahead and delete this.

**Comment by ppratikcr7** [comment]
@danoswaltCL I guess its done, we can close this.
