### ISSUE TITLE
Add API and DB monitoring services in the backend

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#76]
We need to add some off-the-shelf tools into our workflow that can help us monitor API response times and DB load. The first step will be to identify the tools that can help us easily monitor system health. If you have any suggestions for the tools, please mention them.

**Comment by msandbothe** [comment]
@mfugate1 Do you have any insights?

**Comment by mfugate1** [comment]
I'm not familiar with anything other than New Relic, but I'm guessing you're probably looking for free/cheap tools, and New Relic is anything but that. 

I'd think the monitoring available in AWS would be sufficient for showing DB load, although it would be tough to correlate performance there with response times. 

For simple system health, you could create a dashboard in Cloudwatch

**Comment by dhavalocked** [comment]
@mfugate1  Yes NewRelic is costly! as in alternative you can check `[Elastic APM](https://www.elastic.co/guide/en/apm/agent/index.html)`. Integration in Node JS is very easy and it will allow you to add profiling the way you want for the app! You will be able to get API response times and query response times! 

AWS also gives you x-ray-trace to profile your APIs.

**Comment by amurphy-cl** [comment]
@nirmalpatel is your team still looking for these tools? We think AWS can provide most/all of what is needed.

**Comment by nirmalpatel** [comment]
@amurphy-cl we are not looking into this right now. If we are getting this data from AWS by default, we can close this issue for now.
