### ISSUE TITLE
Verify all class-validator decorators using DTO

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#77]
We need to verify all validation decorators for its proper functioning using DTO(Data Transfer Object). Also write unit tests for the same.

**Comment by msandbothe** [comment]
@ppratikcr7 could you assign a priority and describe impact of not having this improvement?

**Comment by amurphy-cl** [comment]
@ppratikcr7 pinging you to provide status/details pls

**Comment by ppratikcr7** [comment]
@msandbothe @amurphy-cl Sorry for the delayed response, missed this notification in the mail. 

Proirity is low as correctly assigned by @amurphy-cl . There is no impact on current working, we just wanted to organize the class validator decorators in a proper DTO (Data Transfer Object) format, so that its easy to manage later.

**Comment by amurphy-cl** [comment]
Checked in about this issue, sticking with low priority, will resume after factorial backend is complete.

**Comment by ppratikcr7** [comment]
@amurphy-cl @mswartzCL @danoswaltCL This seems to be completed. We can close this.
