### ISSUE TITLE
UI Bugs for Factor Table

### ISSUE THREAD

**Issue by mswartzCL** [CarnegieLearningWeb/UpGrade#773]

**Comment by jreddig** [comment]
What needs QA'd to close this issue? I validated the changes made from pr #774 (contains #768 ). Is there anything else?

**Comment by ppratikcr7** [comment]
> What needs QA'd to close this issue? I validated the changes made from pr #774 (contains #768 ). Is there anything else?

I guess that's it. Mainly any frontend bug in factorial feature during QA can also be added to this. If not, we are good to close it.
