### ISSUE TITLE
Disallow factors with identical names in the Factors table

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#779]
**Describe the bug**
Currently, it is possible to create factors with identical names in the Factors table. This could cause issues when using the client method `getFactorLevel(factor)`. As a result, we should not allow the creation of factors with the same names in the Factors table UI.

**To Reproduce**
1. Go to Design Step (Factorial Experiment)
2. Create 2 factors with the same name
3. You will see that the experiment can be created

**Expected behavior**
We should display an error message below the table when two factors with the same name are created and prevent further progress.

**Screenshots**
<img width="600" alt="Screen Shot 2023-04-18 at 2 29 44 PM" src="https://user-images.githubusercontent.com/90279765/232870336-3f088495-99f0-4009-a618-45997f1ce32b.png">

**Comment by jreddig** [comment]
Both levels and factors must be unique with the "must be unique" error message. Verified in dev.
