### ISSUE TITLE
Update validation error message for Factors table when duplicate levels exist

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#780]
**Describe the bug**
Currently, the validation error message for Factors table when duplicate levels exist is not properly written. It's currently shown as `{Factor} factor's {Level}undefined` which doesn't make sense. I think it should be updated to `Level should be unique` (This is how we show the message in the Conditions table in a simple experiment).

**To Reproduce**
1. Go to Design step in a factorial experiment
2. Create a factor and add 2 levels with the same name
3. You will see the weird error message

**Expected behavior**
The validation message should be `Level should be unique`

**Screenshots**
<img width="600" alt="Screen Shot 2023-04-18 at 3 29 31 PM" src="https://user-images.githubusercontent.com/90279765/232884923-e814f45b-e86d-4a2d-946c-13783a10bdcc.png">

**Comment by jreddig** [comment]
Both levels and factors must be unique. Verified in dev.
