### ISSUE TITLE
Some buttons in the Design step are disabled after updating the design type to Factorial Experiment

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#781]
**Describe the bug**
The `+ Add Decision Point` and "Back" buttons in the Design step are disabled after updating the Design Type from Simple to Factorial Experiment. Please see the attached video below:

**To Reproduce**
1. Click Add Experiment
2. Select Simple Experiment design type
3. Move to the Design Step
4. Go back to the Overview step and select Factorial design type
5. Move to the Design step, you will see the `+ Add Decision Point` and "Back" buttons are disabled

**Expected behavior**
The buttons should not be disabled even after changing the design type

**Screenshots**

https://user-images.githubusercontent.com/90279765/232888571-4f2cf897-1f35-4cd4-b80e-1d9462a89324.mov

**Comment by jreddig** [comment]
Verified this is fixed in v5. Moving to done
