### ISSUE TITLE
Update simple data export format

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#786]
The Simple Export format isn't useful as it fails to capture data for experiments with multiple decision points and lacks other useful information for analysis. 

Attached is a modified format that will be more useful for simple analysis.

 
[Simple Data Export.xlsx](https://github.com/CarnegieLearningWeb/UpGrade/files/11276461/Simple.Data.Export.xlsx)

**Comment by VivekFitkariwala** [comment]
@amurphy-cl is this ticket ready for dev?

**Comment by amurphy-cl** [comment]
Yes!

**Comment by amurphy-cl** [comment]
Ok, let me look into an existing experiment to double check -- I think what I was seeing is that we were only getting one line per userid, meaning that if the user visited multiple decision points, that info wasn't captured in the export.

**Comment by amurphy-cl** [comment]
Closing this since we're removing simple export
