### ISSUE TITLE
Replace `ng-pick-datetime-ex` dependency

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#801]
**Tech Debt**
Replace `ng-pick-datetime-ex`, as it has not been maintained in a while and is causing angular compilation headaches

This picker shows up as `OwlDateTimeModule` in the typescript code, and is used to pick dates with a calendar in these components:

`experiment-schedule.component`
`experiment-end-criteria.component`
`experiment-status.component`

**Acceptance Criteria**
1) A well-maintained and popular npm date-picker package should replace this aging dependency and function essentially the same way. 
2) Spec tests should be updated where applicable

**Comment by ppratikcr7** [comment]
@danoswaltCL Are you working on this?

**Comment by danoswaltCL** [comment]
nope, go for it, I guess any up-to-date date picker for material design should be fine

**Comment by Yagnik56** [comment]
hey @danoswaltCL, 
I have tried to find alternative package to replace `ng-pick-datetime-ex ` but most are above 2-2.5 MB in size which are quite bigger compared current one so do you have any specific name in mind we could use?
This one I find nice among all I found till now, 
https://www.npmjs.com/package/@danielmoncada/angular-datetime-picker

**Comment by danoswaltCL** [comment]
that I think is exactly what we want! it looks like it's the same picker just updated and optimized for latest angular, so please try it out, it may be very much the same. it even has a plugin for `dayjs` instead of `moment`, which we just also replaced.

https://www.npmjs.com/package/ng-pick-datetime-ex this is what we're currently using, and it's the same size as an npm module as a whole, but really that wouldn't matter, because Angular will only build the required modules we use from it and once that is zipped it will be light as a feather.

Try this also: You can actually go into the frontend directory and run `npm run analyze` in there that will give you this visual diagram of the frontend's build components, which is pretty interesting to investigate from time to time! One of blue squares there in shows `ng-pick-datetime-ex` and it's unpacked build size is around 220kb. That seems reasonable for a calendar widget.

<img width="1784" alt="image" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/a83e3c00-6eea-47f3-8b1c-8b86a2aea914">
