### ISSUE TITLE
Angular 15 enhancement: Typed Forms

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#802]
**Is your feature request related to a problem? Please describe.**
Angular 14+ allows "Typed" Forms, which has always been a community gripe with Angular Forms (many methods are loosely types). We should use them, but it's probably easier said than done.

https://angular.io/guide/typed-forms

The migration process introduces "UnTyped" form components, and "Typed" form components... it gives us the "UnTyped" modules after migration by default, and it's on us to manually migrate to Typed Form components.

Currently there's around 124 references.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/97542869/234362887-5ece2b17-a06c-4367-be3d-e8aa3779edf3.png">

**Acceptance Criteria**
Devs can verify: References to "Untyped" Form components such as `UntypedFormGroup`, etc, should be minimized and replaced with their "Typed" counterparts.

**Comment by amurphy-cl** [comment]
Closing as "will not do".
