### ISSUE TITLE
Node 18

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#804]
**Is your feature request related to a problem? Please describe.**
Time to update node in all the things!

Not urgent yet, but we are on 16, which ends active support later this year (2023).

<img width="962" alt="image" src="https://user-images.githubusercontent.com/97542869/234367014-53d9705c-c5b5-4216-8dea-0862f1f08c39.png">

**Comment by bcb37** [comment]
Spawned: https://github.com/CarnegieLearningWeb/UpGrade/issues/982
