### ISSUE TITLE
Create a Demo App for Testing the Java Client Library

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#817]
**Is your feature request related to a problem? Please describe.**
It would be nice to create a demo app that allows us to test whether the Java client library is functioning as expected.

**Describe the solution you'd like**
The Java app should include API endpoints that redirect requests to UpGrade via the client library methods.
For instance, if a `/init` request is made to the demo app, the app should invoke `clientLibrary.init();` and return the response.

**Describe alternatives you've considered**
An alternative approach would be to create something more akin to the JavaScript demo app that we already have.

**Comment by amurphy-cl** [comment]
@danoswaltCL were you working on this? status?

**Comment by amurphy-cl** [comment]
Closing, will take different approach moving forward.
