### ISSUE TITLE
Context Metadata / Metadata should be scoped within app context

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#82]
The context metadata is specific to the appContext. So, the group types are specific to the app context, since different apps might have different groupings. For example, one app might know about classes and schools, while another knows about cities and states. An experiment defined for one app could have different groups available than an experiment defined for a different app.

The same is true of experiment points and ids. They're specific to the appContext.

**Comment by nirmalpatel** [comment]
@SritterCL Hey is it fine to make a simplifying assumption for now that one experiment would only run within one context?

**Comment by SritterCL** [comment]
@nirmalpatel - yes. Someday, we'll need to worry about experiments spanning contexts but we don't need to think about that now.

**Comment by amurphy-cl** [comment]
@RidhamShah can you show us an example structure of `CONTEXT_METADATA`? Is this just the same as the json structure that gets sent in the API?

**Comment by RidhamShah** [comment]
JSON format
```
CONTEXT_METADATA = {
    add: {
        EXP_IDS: [add-id1, add-id2],
        EXP_POINTS: [add-point1, add-point2],
        GROUP_TYPES: [add-group1, add-group2]
    },
    sub: {
        ...
    }
}
```

Stringify format I am using 

CONTEXT_METADATA = {"add":{"EXP_IDS":["add-id1","add-id2"],"EXP_POINTS":["add-point1","add-point2"],"GROUP_TYPES":["add-group1","add-group2"]},"sub"{...}}

**Comment by SritterCL** [comment]
I think it makes sense to merge the ID/Point pair within an experiment site, and also list the conditions available at each site (so they can be validated).

We should also add a "description" field to the experiment site and also to the groups. These descriptions will be used as tooltips for UpGrade users, so they know what each experiment site and group-type should be used for (see 


Something like this:
  {
    "appContext": "assign-prog",
    "contextDescription": "the service in Mathia that manages student transitions between sections (workspaces) within an assignment (module)",
    "groupTypes": [
        {"name": "Class", "description": "Students in a class”},
        {"name": "Teacher", "description": “Students of a teacher”},
        {"name": "School", "description": "Students in a school”},
        {"name": "District", "description": "Students in district”},
    ]
    "Experiment sites": [
        {
         “Point”: {“name”: “selectSection”,
                   “Description”: “MATHia selecting workspace”,
                  }
         “IDs”: [
                 {“id”:”calculating_area_various_figures”,
                  “name”: "Calculating Area of Various Figures",
	             “description”: “Mastery workspace used for area”,
                  “conditions”: [{“ID”:”stat_dgm”,
                                  “name”:“static diagram”},
                                 {“ID”:”anim_001”,
                                  “name”:”animation number one”, ] },
                 {“name”: "Compare_functions_diff_reps_quadratic",
                  “conditions”: [“version1”,”version2”,”version3”] },
                ]
        }
        {
         “Point”: {“name”: “getHint”,
                   “Description”: “student asks for hint”,
                  }
         “IDs”: [
                 {“name”: "hint",
			  “Description”: “Student asked for a hint”,
                  “conditions”: [“dialog”,”tutorbot”] },
                ]
        }
    ],
  },

**Comment by SritterCL** [comment]
Also - we should add some metadata to the condition to indicate whether the condition is identical to "default."

**Comment by nirmalpatel** [comment]
@SritterCL we had a discussion and it seems like conditions nested within the IDs can cause an issue. For example, if you are doing a two-site experiment and both sites (or point-ID pairs) can have a different set of possible conditions. In our current UX design, the conditions are independent from the sites...

**Comment by RidhamShah** [comment]
I customize the API call of Context Metadata as per the new JSON format of `CONTEXT_METADATA`. Now on changing the `app-context` in UI the `group-types` will also change according to it. Also, it will change the `exp-points` & `exp-ids` on the experiment-design page. If `group-types / exp-points / exp-ids` are already selected for an `app-context`, and on changing, the values of all will become null and new options will allocate to them according to the `app-context`. 
Also solved some bugs around this.

In some time the PR will be created for this.

**Comment by RidhamShah** [comment]
With the change in the format of CONTEXT-METADATA there are some changes to be done in UI and backend for excluding groups.

**Comment by nirmalpatel** [comment]
We are testing the new terraform variables that we added to solve this issue. Code changes have been done.

**Comment by RidhamShah** [comment]
Everything is completed. Also, the problem of opening old experiments after the new context-metadata throws error is solved.

**Comment by ppratikcr7** [comment]
@msandbothe @mfugate1 You need to add the following variable value either to your elastic beanstalk backend or reploy infrastructure terraform scripts for context_metadata to populate. We are using the below value:

`CONTEXT_METADATA        = "{'add':{'EXP_IDS':['add-id1','add-id2'],'EXP_POINTS':['add-point1','add-point2'],'GROUP_TYPES':['add-group1','add-group2'],'CONDITIONS':['add-con1','add-con2','add-con3']},'sub':{'EXP_IDS':['sub-id1','sub-id2'],'EXP_POINTS':['sub-point1','sub-point2'],'GROUP_TYPES':['sub-group1','sub-group2'],'CONDITIONS':['sub-con1','sub-con2','sub-con3']},'mul':{'EXP_IDS':['mul-id1','mul-id2'],'EXP_POINTS':['mul-point1','mul-point2'],'GROUP_TYPES':['mul-group1','mul-group2'],'CONDITIONS':['mul-con1','mul-con2','mul-con3']},'div':{'EXP_IDS':['div-id1','div-id2'],'EXP_POINTS':['div-point1','div-point2'],'GROUP_TYPES':['div-group1','div-group2'],'CONDITIONS':['div-con1','div-con2','div-con3']}}"`

**Comment by mfugate1** [comment]
I added it, but that's not why the backend deployment keeps failing. https://github.com/CarnegieLearningWeb/UpGrade/pull/141 needs to be merged

**Comment by ppratikcr7** [comment]
Okay, but still we would need to merge this [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/156) once approved to add new terraform script changes that are missing.
