### ISSUE TITLE
UpGrade query performance

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#84]
Query UpGrade for metrics data and enrollment data on the UI is still very laggy. 
Step 1: CL will provide PP exported data to recreate on their end.

**Comment by msandbothe** [comment]
@mhglover You have a workflow for exporting our Upgrade data from Production? Could you provide that data to Playpower?

**Comment by amurphy-cl** [comment]
@mhglover pinging you for that workflow if you can still provide it

**Comment by mhglover** [comment]
We want to provide the data, not just the process for exporting it, right?  I've dumped the prod database using the command below and I've sent April the link to download it from S3.  This export was only about 55MB, does that sound right?

`pg_dump --file "upgrade-prod-postgres-2021-07-08" --host "production-cli-upgrade-production-postgres.c0ehk0fl3zte.us-east-1.rds.amazonaws.com" --port "5432" --username "postgres" --verbose --format=d  -j 16`

**Comment by nirmalpatel** [comment]
@amurphy-cl can you share the S3 download links with us?

**Comment by amurphy-cl** [comment]
Shared - let us know what else you need for progress on this.

**Comment by nirmalpatel** [comment]
Vivek has done testing locally where he is not facing any issues. He will be testing this in our AWS infrastructure soon.

**Comment by VivekFitkariwala** [comment]
The query function was calling the database twice and that was the reason the result was slow for query. Have fixed the issue in the [PR-108](#108 )
