### ISSUE TITLE
The arrow icons are not properly displayed in the By Condition section

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#845]
**Version where bug was found:**
4.3.0

**Describe the bug**
On the experiment details page, under the Data tab, the arrow icons are not properly displayed in the By Condition section.

**To Reproduce**
1. Go to experiment details page
2. Select the Data tab
3. Check the By Condition section at the bottom

**Expected behavior**
The arrow icons should be displayed properly. 

**Screenshots**
<img width="750" alt="Screen Shot 2023-05-10 at 2 28 02 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/b1a5c546-314f-4977-a703-7b5b246c0ff3">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by jreddig** [comment]
Validated in dev
