### ISSUE TITLE
JS Client Lib not working in Node

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#867]
**Version where bug was found:**
all published npm library versions

**Describe the bug**
The library will not build in Node (outside of browser envs). Some versions say "window" is not defined, and other say "self" is not defined in the webpacked `bundle.js`

**To Reproduce**
`ReferenceError: window is not defined
  at Object.<anonymous> (/Users/zlee/Desktop/code/clientlib_test/node_modules/upgrade_client_lib/dist/bundle.js:1:224)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async loadESM (node:internal/process/esm_loader:88:5)`

**Comment by zackcl** [comment]
Just want to share what I've tried (but failed). Running the following code seemed to print fine (version: 4.2.0):

Code:
```
const crypto = require("crypto");
if (!global.crypto) {
  global.crypto = {
    getRandomValues: function (buffer) {
      return crypto.randomFillSync(buffer);
    },
  };
}
global.self = global;
const UpgradeClient = require("upgrade_client_lib").UpgradeClient;
const studentId = "student1";
const hostUrl = "http://localhost:3030";
const context = "add";
const upClient = new UpgradeClient(studentId, hostUrl, context);
console.log(upClient);
``` 
Output:
```
{
  api: {
    init: 'http://localhost:3030/api/v4/init',
    getAllExperimentConditions: 'http://localhost:3030/api/v4/assign',
    markExperimentPoint: 'http://localhost:3030/api/v4/mark',
    setGroupMemberShip: 'http://localhost:3030/api/v4/groupmembership',
    setWorkingGroup: 'http://localhost:3030/api/v4/workinggroup',
    failedExperimentPoint: 'http://localhost:3030/api/v4/failed',
    getAllFeatureFlag: 'http://localhost:3030/api/v4/featureflag',
    log: 'http://localhost:3030/api/v4/log',
    logCaliper: 'http://localhost:3030/api/v4/logCaliper',
    altUserIds: 'http://localhost:3030/api/v4/useraliases',
    addMetrics: 'http://localhost:3030/api/v4/metric'
  },
  group: null,
  workingGroup: null,
  experimentConditionData: null,
  featureFlags: null,
  userId: 'student1',
  hostUrl: 'http://localhost:3030',
  context: 'add',
  token: undefined,
  clientSessionId: '9b724701-9e0d-4c23-9824-149e96a49f85'
}
```

However, if I actually try to get a decision point assignment, I get an error which doesn't say anything.

Code:
```
const visitDecisionPoint = async () => {
    try {
        await upClient.init();
        const site = "add-point1";
        const target = "add-id1";
        const assignment = await upClient.getDecisionPointAssignment(site, target);
        const condition = assignment && assignment.getCondition();
        console.log(condition);
    } catch (error) {
        console.log("upClientError:", error);
    }
}
visitDecisionPoint();
```
Output:
```
upClientError: Error: {}
    at /Users/zlee/Desktop/code/upclient_test/node_modules/upgrade_client_lib/dist/bundle.js:1:8485
    at Generator.next (<anonymous>)
    at a (/Users/zlee/Desktop/code/upclient_test/node_modules/upgrade_client_lib/dist/bundle.js:1:22250)
```

**Comment by zackcl** [comment]
Forget about my previous comment. Making these changes seem to work fine (using node-fetch instead): https://github.com/CarnegieLearningWeb/UpGrade/commit/5f52f45a1972a13eaaf55811920dc93e3a175fdd

**Comment by VivekFitkariwala** [comment]
I have added a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/868).
@zackcl can you check this?
