### ISSUE TITLE
Add checks and failsafe measures to the experiment scheduler

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#9]
Some additional measures to make experiment scheduling more robust and error free:

- Double check the experiment start/end date when automatically starting/ending the experiment
- Return HTTP response code to the Lambda that gets triggered at the time of the schedule so that the Lambda can retry experiment start/top if the initial call fails
- Add transactions wherever needed in this process

**Comment by amurphy-cl** [comment]
@VivekFitkariwala will take a look at this in case some work has already been completed

**Comment by nirmalpatel** [comment]
@amurphy-cl this issue was solved by PR #73 Pratik has checked Scheduler after this PR. If any issues arise again, we can create a new issue.
