### ISSUE TITLE
UI bug: deleting rows in stepper

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#919]
**Version where bug was found:**
v.4.17 (current staging env)

**Describe the bug**
Deleting rows appears to remove them, but when you exit the experiment detail view and bring it up again, the empty rows reappears.

<img width="994" alt="image" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/92067a48-9938-499b-9fda-24cb64a56c47">

**Comment by danoswaltCL** [comment]
I believe @Yagnik56 already caught this and change is made in the larger within-subjects pr

**Comment by Yagnik56** [comment]
I think we can close this issue as withinsubject branch is merged with dev and that isn't there anymore so...
