### ISSUE TITLE
Figma prototype for SRS UI changes

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#958]
**User Story**
 - Team needs to review a prototype of the UI to decide on details

**Acceptance Criteria** 
 - Meets requirements, including the following: 
 
- Uploading the CSV ([Example upload file](https://docs.google.com/spreadsheets/d/1cgFllXv0KTe2TROp4TKbJxPRfO0NAdrXqYtFKnd3wVk/edit#gid=0))

- Tab in Participants (after clicking left menu item): Stratification
- Page inside the tab includes the following:
    - Button to upload csv
      -  Field to add description or name to stratification csv
    - Upload must match format with two columns
      -  Column headings will contain “uuid”, and “stratification factor”
      - Rows are the student uuids
    - After upload, summary view: N uuids, N values in stratification levels
    - Button to download previously-uploaded csv
    - Delete button removes csv
- Re-uploading csv will overwrite existing one
- No need to view table after upload

**Defining Stratified Random Sampling within experiment stepper**
- Under Conditions, new Checkbox next to “weight equally” box
- Select Stratification (checkbox) 
- After checkbox, select from a dropdown of factors available, from stratification csvs uploaded
- Only available for Simple Experiment

**Comment by ppratikcr7** [comment]
@zackcl This is moved to Done column, can we please close this?
