### ISSUE TITLE
[UI] Add Stratification Data Tab and Upload Button to Participants Content View

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#964]
**User Story**
As a user, I want a view in the UI where I can manage stratified-sampling settings.

(🟠  Link to design when ready)

**Dependencies:**
#958

**Links***
Figma Screen Recording
https://carnegielearning.slack.com/files/U02DS8JDP0Q/F05NH1DS0EP/screen_recording_2023-08-18_at_1.28.54_pm.mov

**Acceptance Criteria**
GIVEN I'm an experimenter,
WHEN I can click on Participant's tab in sidebar navigation
THEN I will see a tab to the right of "Participants" that says "Stratifications"
AND when I click on this tab, I will see the content page as visualized in design doc 
AND I will see a an upload csv button "+ IMPORT"

GIVEN No stratification data exists in the database
THEN The content should show a 'blank' state -  the content page as visualized in design doc, with an empty, headings-only table

**Notes**
This is intended as a UI-only task for positioning elements. Adding table and Upload button functionality will be handled in other tasks.

**Comment by zackcl** [comment]
QA: Passed

<img width="500" alt="Screenshot 2023-11-20 at 8 59 59 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/1074d44b-3916-4d2a-8dc9-d580ef63512a">
