### ISSUE TITLE
[UI] Add CSV import modal component (blank state)

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#965]
**User Story**
As an experimenter, I want to click on Import CSV button in Stratification tab and see a modal to choose a file.

**Dependencies:**
#958
#964 

**Links***
Figma Screen Recording
https://carnegielearning.slack.com/files/U02DS8JDP0Q/F05NH1DS0EP/screen_recording_2023-08-18_at_1.28.54_pm.mov

**Acceptance Criteria**

GIVEN an experimenter clicks on the upload csv button in the Stratification tab of Participants page in UI
THEN they will see an import csv modal (see design prototype) in a "blank" state (no file chosen),
AND they will see a "Choose file" button that is enabled [🟠 button text needed],
AND they will see a message that explains that they need to choose a csv file [🟠 message needed],
AND they will see a "Cancel" button that is enabled.
AND they will see a "Import" button that is disabled until a selection is made.

**Notes**
Modal button functionality to be handled in separate tasks.

**Comment by Yagnik56** [comment]
hey @bcb37 are you working on this issue ? otherwise I can take this

**Comment by zackcl** [comment]
QA: Passed

<img width="750" alt="Screenshot 2023-11-20 at 11 10 36 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/d0013a01-faa1-430d-ae48-021d3e80e787">
