### ISSUE TITLE
[UI] CSV Import modal: Add "Choose file" button functionality

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#966]
**User Story**
As an experimenter, I can choose a CSV file from my computer to upload via the UI

(🟠 link to figma prototype)

**Dependencies**
#958 
#964 
#965 

**Links**
Figma Screen Recording:
https://carnegielearning.slack.com/files/U02DS8JDP0Q/F05NH1DS0EP/screen_recording_2023-08-18_at_1.28.54_pm.mov

**Acceptance Criteria**
GIVEN a user clicks the "choose file" button
AND a pop-up opens with "choose file" button
THEN I will see an OS dialog to pick one csv file

---
[🟠 does validation need to happen in UI or after submitting?]
GIVEN a user has selected and confirmed a file in the OS dialog
THEN the csv should be validated [🟠 include validation criteria here]

---
[🟠 does validation need to happen in UI or after submitting?]
GIVEN that the csv is valid
THEN the UI should display [ 🟠 insert the text for a confirmation message ]
AND the button to import should be enabled

---
[🟠 does validation need to happen in UI or after submitting?]
GIVEN that the csv is invalid
THEN the UI should display [ 🟠 some helpful text about why it is invalid ]
AND the button to import should remain disabled

---

**Comment by zackcl** [comment]
QA: Passed
