### ISSUE TITLE
[UI] Add POST Imported CSV data functionality (import button click)

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#967]
**User Story**
As an experimenter, I want to send a csv of stratification data to backend via UI

**Dependencies**:
[🟠 API Creation story ]
#958
#966

**Acceptance Criteria**
GIVEN: I've selected a valid csv from my computer
AND: I've clicked on the import button
THEN: I should see a POST request to [🟠 add actual endpoint] with a request body [🟠 add request body details for csv import]

---

GIVEN: The network request is pending
THEN: I should not be able to click the import button again
AND: I should not be able to navigate away from the page while pending
AND: I should see some kind of spinner (🟠 figma?)

[Success and error handling could be a separate story]

---

GIVEN: The request is successful:
THEN: [ 🟠 What ? The show a "success" message, close modal, refetch the csv data so the table is refreshed with the new row?]

---

GIVEN: The request errors:
THEN: [ 🟠 What should the error messaging look like? What scenarios should be considered for error-states on this call? Do we close the modal or leave it open for trying again?]

**Comment by zackcl** [comment]
The feature works fine in terms of making requests to the backend, but the success or error snackbar is not displayed when a CSV file is imported. This needs a discussion. (Related to https://github.com/CarnegieLearningWeb/UpGrade/issues/974#issuecomment-1820146209))

<br>

If I import a CSV file of the following content:
```
UUID,frl
stud1,true
stud2,false
stud3,true
stud4,false
stud5,false
stud6,false
```

The client makes POST request to `/api/stratification` with the following body:
```
[
    {
        "file": "UUID,frl\nstud1,true\nstud2,false\nstud3,true\nstud4,false\nstud5,false\nstud6,false"
    }
]
```
And then makes GET request to `/api/stratification` which retrieves the following:
```
[
    {
        "factor": "frl",
        "factorValue": {
            "false": 4,
            "true": 2
        },
        "experimentIds": [
            null,
            null,
            null,
            null
        ]
    }
]
```

This results in the following UI:
<img width="750" alt="Screenshot 2023-11-20 at 10 55 56 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/903e6109-6123-44b6-a3b0-bde141e4f44d">

**Comment by bcb37** [comment]
Reopening

**Comment by zackcl** [comment]
QA: Passed
