### ISSUE TITLE
[UI] CSV Import Modal: Add Cancel button functionality

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#968]
**User Story**
As an experimenter, I want to cancel out of the Import CSV modal

**Dependencies:**
#958
#964 

**Links**
(🟠 Link design prototype)

**Acceptance Criteria**

GIVEN an experimenter clicks on the Cancel button in the CSV Import Modal
THEN the modal will close and the user will return to Stratification view with no changes

**Comment by zackcl** [comment]
QA: Passed
