### ISSUE TITLE
[UI] Add csv data fetch / cache fetch on app load

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#969]
**User Story**
As an experimenter, when I click on the Stratification tab, I want be able to see what csv data is uploaded to the server.
[🟠 do this data fetch on app load?]

**Dependencies**
#963 

**Links**

**Acceptance Criteria**
SCENARIO: When [🟠 app loads?], a call to the stratification data endpoint will fetch stratification data.

GIVEN: stratification data fetch is successful
THEN: Data will be stored in a new ngrx feature store `stratification-data`

---
GIVEN: CSV Upload data fetch errors
THEN: [🟠 nothing? just fail in background?]

**Notes**
This is just for the data fetch / data store, creating and populating table is another story.

**Comment by zackcl** [comment]
QA: Passed

I can confirm the stratification data is fetched with the `/api/stratification` GET request when the UpGrade `/home` page is loaded.

<img width="700" alt="Screenshot 2023-11-20 at 9 57 55 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/ec805991-7b22-417f-888c-f1be8da21cdc">

<img width="700" alt="Screenshot 2023-11-20 at 10 01 04 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/b63d2e50-cb2c-40b9-a77c-51e7d3c47e79">
