### ISSUE TITLE
[UI] Add table on Stratification tab to show row of strata w/ summary descriptions

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#970]
**User Story**
As an experimenter on the Stratification tab, I want to see a list of the currently uploaded csv files.

**Dependencies**
#958
#964
#969 (can worked around w/ dummy data though if need be)

**Links***
Figma Screen Recording
https://carnegielearning.slack.com/files/U02DS8JDP0Q/F05NH1DS0EP/screen_recording_2023-08-18_at_1.28.54_pm.mov

**Acceptance Criteria**

GIVEN stratified user csv data has been fetched and at least 1 upload exists in db
THEN a table should display csv file according to prototype
AND each row should have the following design:

```
Headers: Stratification factor | Summary  | Action buttons (download / delete )

Rows: “Stratification on FRL (437=“Yes”; 563=“No”)" [for each strata represented, so this could be unknown number of lines long]
```

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/3a757a0b-4300-4ae6-9533-c540dee708fc)

**Notes**
Action button functionality in separate story, for this task the buttons should be positioned w/o doing functionality

[ 🟠 verify that this idea is no longer the desired design] Also note design below, @amurphy-cl mentioned this as the original concept as she imagined it. This is similar but conceptually it may mean storing data in a different way, with a tag to indicate a grouping of UUIDs that were uploaded together. In this design, each row would represent that tagged group, with a summary of the strata breakdown in that group instead of each row = 1 unique strata and a summary of all strata values from all groups. 

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/de21a84b-9537-4042-8b62-859ad519ed5b)

**Comment by zackcl** [comment]
QA: Passed

<img width="700" alt="Screenshot 2023-11-20 at 9 14 41 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/0ee332fc-f7d2-49ca-9f72-f364d4d13fc3">
