### ISSUE TITLE
[UI] Strata Table Row: Add Download Button Functionality

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#973]
**User Story**
As an experimenter, I want to download a csv of stratification data by UUID for all in that strata row in table

**Dependencies:**
#958
#964 

**Links**
(🟠 Link design prototype)

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/c4e17433-bd02-4695-ba4f-452b8d2c5d6c)

**Acceptance Criteria**

GIVEN an experimenter clicks on the download button in a strata table row
THEN call API [ 🟠 include actual endpoint when decided] to download csv for that strata to browser

GIVEN the call is successful
THEN the csv will be downloaded
AND the user will see a Success notification pop up [ 🟠 pic of notification 'toast' with correct text]

GIVEN the call is error
THEN the csv will be not be downloaded
AND the user will see an error notification pop up [ 🟠 pic of notification 'toast' with correct text]

**Comment by zackcl** [comment]
The downloading works fine, but a Success (or Error) notification pop up does not appear. 
Let's discuss if we really need to display the success/error snackbar.

**Comment by bcb37** [comment]
Reopening

**Comment by zackcl** [comment]
QA: Passed
