### ISSUE TITLE
[UI] Design Stepper: Add Stratification Checkbox and Dropdown

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#975]
**User Story**
As an experimenter, I want to choose a stratification factor for my "simple" experiment that is not a "within-subjects" type.

**Dependencies:**
#969 

**Links**
(🟠 Link design prototype)

**Acceptance Criteria**

[ 🟠 all details needed! perhaps a picture will help once Zack has something ready]

The user will see a dropdown of `Assignment algorithm` with `Random` as the default option and `Stratified Random Sampling`. When the user selects `Stratified Random Sampling` another dropdown will appear with selecting the stratification factor.

**Comment by amurphy-cl** [comment]
@VivekFitkariwala please update with current design details

**Comment by zackcl** [comment]
QA: Passed

<img width="500" alt="Screenshot 2023-11-20 at 9 19 02 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/24cebd59-8273-4de6-918f-3026841b2a3f">
