### ISSUE TITLE
[UI] Design-Stepper: Add stratification data to experiment json on submit

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#976]
**User Story**
As an experimenter, I want to create an experiment that uses stratified sampling using the design-stepper

**Dependencies:**
#969
#975 

**Links**
(🟠 Link design prototype)

**Acceptance Criteria**

GIVEN I have made valid stratification choices in my experiment in design-stepper
WHEN I click create experiment
THEN I will send an updated experiment request body to `POST /experiments` that includes stratification data

[ 🟠 show updated experiment json shape here ]

**Comment by zackcl** [comment]
QA: Passed

I can confirm that when an experiment with stratified random sampling is created, the client makes POST request to `api/experiments` that includes the `stratificationFactor`.

<img width="500" alt="Screenshot 2023-11-20 at 9 27 53 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/1358e9a1-b189-4b65-b422-dfde361ebed2">


And the exported experiment JSON file also contains the `stratificationFactorName`.

```
...{"createdAt":"2023-11-21T02:03:05.685Z","updatedAt":"2023-11-21T02:03:05.685Z","versionNumber":1,"stratificationFactorName":"fav_food"}
```
