### ISSUE TITLE
Create an API to delete stratification data

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#980]
**User Story**
 - User developer needs to make an API call so that they can delete stratification data for a given stratification factor.

**Acceptance Criteria** (can be added later)
 - Scenario: A /DELETE API call is made with a stratification factor specified API call will be /stratification/:factor
     - Given There is data associated with the stratification factor, when the call is made, then the data associated with that stratification factor is removed from the database

**Dependencies**
#959
#960 
#961

**Comment by zackcl** [comment]
QA: Passed

I can confirm that stratification factor is removed with the `/stratification/:factor` DELETE API request.
