### ISSUE TITLE
Look into replacing/augmenting npm

### ISSUE THREAD

**Issue by bcb37** [CarnegieLearningWeb/UpGrade#985]
We'd like to have a more modern, full-featured dependency management setup. There's been discussion about using yarn, nx, and others. This is to research the pros and cons of switching to any of them.

To do: choose a reasonable number (2 or 3) of npm replacements, evaluate them w.r.t. simplifying and streamlining the management of dependencies, and come up with a recommendation.

Deliverable: recommendation, with reasoning and possibly a prototype branch

**Comment by amurphy-cl** [comment]
Closing as "will not do".
