### ISSUE TITLE
Experiment List Sorting order is off for mixed lowercase and uppercase experiment names

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#988]
**Version where bug was found:**
e.g "5.0.1"

**Describe the bug**
Experiment List Sorting order is off for mixed lowercase and uppercase experiment names on the home screen.

**To Reproduce**
1. Add few 5-10 experiments.
2. View the order. It should be as per descending name.

**Expected behavior**
Sorting order should be descending name.

**Screenshots**
<img width="1027" alt="Screenshot 2023-08-17 at 4 24 47 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/6dab8f6f-142a-4cbb-a6d7-16bd488c9064">

**Comment by ppratikcr7** [comment]
@amurphy-cl @danoswaltCL This issue is resolved and merged in dev. Should we close this?

**Comment by zackcl** [comment]
I need to QA this.

**Comment by zackcl** [comment]
This issue doesn't seem to be resolved. As you can see, the experiments with lowercase names get sorted first, followed by those with uppercase names. The sorting should happen in a case-insensitive manner.

<img width="750" alt="Screenshot 2023-11-07 at 7 32 37 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/3de5bbfa-18dd-4d20-9a65-cccd1c9fd4f6">

**Comment by ppratikcr7** [comment]
@zackcl Will check this again and let you know. There is a lot of code pushed after the PR for this ticket was merged in dev.

**Comment by danoswaltCL** [comment]
QA: Zak

**Comment by zackcl** [comment]
QA: Passed
