### ISSUE TITLE
Stepper won't progress past Metrics tab when creating new experiment (v5 QA)

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#993]
**Version where bug was found:**
v5.0.2

**Describe the bug**
Creating a new experiment with the stepper, Next button doesn't progress when on Metrics tab. 

**To Reproduce**
Create a new experiment
Progress through the stepper
Get stuck on Metics tab

**Expected behavior**
Stepper should progress even if user doesn't add metrics. 

**Screenshots**
<img width="1078" alt="image" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/65311369/7a806178-1328-410e-88f7-b3cddb40caa4">

**Comment by ppratikcr7** [comment]
@amurphy-cl Can you please send the above experiment JSON?

**Comment by ppratikcr7** [comment]
@amurphy-cl @danoswaltCL Do we still see this issue in QA? If not, can we close this?

**Comment by amurphy-cl** [comment]
I think we can close, iirc this was a backwards-compatibility issue.
