### ISSUE TITLE
QA task: test basic AA experiment to ensure simple experiments are working

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#998]
Test AA1 and or AA2 to ensure enrollment and metrics are being captured appropriately for Simple Experiments

**Comment by danoswaltCL** [comment]
Basic AA tests were thoroughly tested for all back-versions in many scenarios:

https://docs.google.com/spreadsheets/d/1dr_cc9zeHInPPD0bKk4xNkLNPQ_uN-E00kJksHkokX0/edit#gid=891300857
